### ISSUE TITLE
add target density fluctuations to select_mock_targets

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#104]
Related to #90 (include target contamination) and #101 (generate target density fluctuations)...

todo: Implement the target density fluctuations in select_mock_targets itself.

**Comment by forero** [comment]
I noticed in #116 that the function `generate_fluctuations` works with `EBV` only. There is no need to pass other depths. 

Would it be reasonable then (for the mocks) to generate only the reaal `EBV` values from the ra,dec positions for each tile, without trying to invent any `DEPTH` information? In that way we could at least have fluctuations with some spatial correlation.

**Comment by geordie666** [comment]
That's really just a code simplification. I think you need two stages:

(1) pass EBV to generate_fluctuations to obtain fluctuations that are
genuinely spatially correlated with dust
(2) pass one of the DEPTHS to generate fluctuations that are appropriate on
the per-brick level but are not correlated across bricks

Multiply 1 by 2 to get the overall fluctuation...

**Comment by forero** [comment]
all right.
