### ISSUE TITLE
add BGS, MWS, SKY, FSTD, WDSTD target selection flags

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#12]
Creating a ticket so we don't forget about it.  We need to reserve target bits for the Bright Galaxy Survey (BGS), the Milky Way Survey (MWS), sky fibers (SKY), F-type standard stars (FSTD), and White Dwarf standard starts (WDSTD).

From Jeremy Tinker:

> For the BGS, so far we only need two bits. Bright and faint BGS targets. It seems unlikely that we’ll do much more than that, but it’s possible that we might put collided SDSS and BOSS targets as a separate bit in order to give them maximal priority. As with eBOSS QSOs, we might want to have a catalog that includes KNOWN objects, just so we don’t have to go back to some random location to put together the full LSS catalog. Thus, we’d also want to make sure that the tiled bits are an input to the tiling code as well. So the input target catalog has KNOWN in it, but are not assigned fibers. (That may be easy enough by saying that zero observations are required).
>
> So…
>
> BGS_FAINT
> BGS_BRIGHT
> BGS_KNOWN_COLLIDED
> BGS_KNOWN_SDSS
> BGS_KNOWN_BOSS

Connie Rockosi indicated that the MWS may want to group targets by their proper motion in order to use different priorities.  Let's reserve 5 bits, and maybe in a different range to so that we can expand them a bit more if needed.

Also: we need to resolve how targeting bits will be handled for South (DECaM-based) vs. North (Bok+Mosaic based) vs. overlap regions.  One option is to define separate LRG_SOUTH and LRG_NORTH bits, perhaps with a 3rd convenience LRG big that is just the logical OR of LRG_SOUTH and LRG_NORTH.  Ditto for ELG, etc.

Assigning to @moustakas since I definitely want his input on this, though others are also welcome to contribute.

**Comment by rainwoodman** [comment]
Q: Are we going to calculate 'KNOWN' bit in desi-target?

**Comment by sbailey** [comment]
> Q: Are we going to calculate 'KNOWN' bit in desi-target?

I think the answer is "eventually yes".  This would be handled as another input stream of known targets that would be used on a case by case basis for each bit.  People who have actually done this before for SDSS should be consulted for what worked and didn't work.

**Comment by sbailey** [comment]
I just had a very useful chat with Nathalie and David S.  A few things came up:

It should *not* be `LRG = (LRG_NORTH or LRG_SOUTH)` since that effectively creates 3 regions of the survey (north only, south only, overlap).  It should be `LRG = (LRG_NORTH and DEC>=x) or (LRG_SOUTH and DEC<x)` since that defines only 2 regions, while still allowing comparison of selection bits in the overlap.  The concept of "DEC<x" could be a more complicated geometry if needed.

Goals for the target selection flags overall:
* Preserve the ability for a single object to pass multiple cuts (thus motivating bitmasks)
* Don't reuse bits.  If we change target selection for some object type, mint a new bit.
* Have merged bits that do the North vs. South logic as described above, while preserving the individual N/S bits.
* Have explicit commissioning bits (could be a lot)
* Expandability - if we need more bits, we should be able to create more bits
* Prevent name overloading (e.g. MWS and the dark survey might both want to target white dwarfs.  Let's not both call them "WD".
* Track target *priorities* separately from target *selection*.

Open questions:
* How to support back propagation of new bits to areas/targets that were previously observed?  This highlights the difference between *target selection* (why did we put this fiber there) vs *sample selection* (understanding a sample of what was observed post-facto).
* What to do if imaging or reduction versions change mid-survey?

Options:
* Try to make everything fit within a single 64-bit integer
* If we need more integers, use more variables: TARGETFLAGS0, TARGETFLAGS1, ...
* Have an array of 64-bit integers.  This allows us to give names to the indices of the array, e.g.
TARGETFLAGS[DARK] bit X vs. TARGETFLAGS[MWS] bit Y, which might be more understandable than just knowing that TARGETFLAGS0 is for the dark survey and TARGETFLAGS1 is for the MWS, and it is also more extendable than TARGETFLAGS_DARK vs. TARGETFLAGS_MWS...
