### ISSUE TITLE
io.py recursively descends directories to look for sweeps and tractor files

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#120]
This is dangerous. For example, now we have dr3.0 and dr3.1 sweeps directories in the dr3 release, io.iter_files could collect _both_ sets of sweeps instead of just one set. Since we made dr3.1 I've been using this with care to only retrieve one set of sweeps files, but we should probably fix it to insist on better specification of the exact directory of interest.

**Comment by sbailey** [comment]
I'm not sure what there is to do here other than make it clear to users to specify a sweep version subdirectory and not just a top level sweep or data release directory.  It is useful for development to be able to copy an arbitrary set of sweeps or tractor files to another location and use them as-is without select_targets imposing a specific directory structure.

We could cache the filenames that it finds while traversing the directory tree and raise an error if it finds the same filename in two different directories.  That isn't bulletproof, but could help.  Even then, I'd offer an override option to force select_targets to take whatever it finds, including repeats.

**Comment by geordie666** [comment]
I like the option of flagging an error if you traverse two different directories unless the user sends an override flag. Leave that with me. I don't think this is critical...it's just very easy at the moment to process targets twice given our dr3/dr3.1 directory structure.

**Comment by sbailey** [comment]
To be clear: I think the error should be if you find the same filename in two different directories, not just that you were traversing two different directories.  The sweeps happen to be in a single directory per release, but select_targets should also work on tractor files that are grouped into many directories (but without repeated filenames).

**Comment by geordie666** [comment]
Yes...agreed. I worded my response badly.

**Comment by geordie666** [comment]
Closed in https://github.com/desihub/desitarget/pull/229
