### ISSUE TITLE
reduce memory consumption of select_mock_targets

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#126]
Running on the full survey with the whole set of input catalogs`select_mock_targets` takes up 450 GB  (!!) of RAM at its peak. It should take 60GB if we want to run it on Edison as a batch script.

**Comment by sbailey** [comment]
Ouch.  One quick win could be the galaxia mocks: they are by far the largest type of mock (80 GB) and they are currently potentially read in 3 times for MWS_MAIN, STD_FSTAR, and BADQSO.

**Comment by sbailey** [comment]
Another idea: `desitarget.mock.io._load_mock_mws_file` casts the SDSS photometry, d_helio, and v_helio to 'f8', when we would be fine with just 'f4'.  RA and DEC should remain 'f8'.  If in doubt, use the precision listed for the legacy survey sweep files at http://legacysurvey.org/dr3/files/ .

And documenting another conversation with Jaime:
* check if the Galaxia mocks are all sky or just the DESI footprint.  If all sky, we could save a huge amount by just keeping what is in the DESI footprint (we don't have an exact handy utility function for that, but even a conservative approximate cut on galactic latitude could be a huge win).
* The Galaxia mocks appear to be much higher density than we need.  Could we sub-sample them ahead of time?  Subsampling should be random (not the first N entries in a file) in case there is any meaning to the order of the targets in the files.

**Comment by forero** [comment]
We did the updates described in #129
