### ISSUE TITLE
select_mock_targets: get fluxes from data or model

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#130]
Update select_mock_targets to use the Gaussian Mixture Model of target fluxes from PR #128 if a real data target selection catalog is not provided to sample.  i.e.

1. PR #127 added the ability to sample a real data target catalog to add fluxes to mocks if they weren't already there.
2. PR #128 provided a Gaussian Mixture Model of those fluxes.
3. But select_mock_targets doesn't fall back to (2) in the case that (1) isn't provided

**Comment by moustakas** [comment]
This was added in #156 and #173.
