### ISSUE TITLE
update DC2017 mocks to match DESI footprint

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#140]
Update DC2017 mocks to match DESI footprint (or be a modest superset if needed)
* [ ] BGS via MXXL
* [ ] MWS via Galaxia
* [ ] ELG via Gaussian Random Mocks
* [ ] LRG via Gaussian Random Mocks
* [ ] Tracer QSO via Gaussian Random Mocks
* [ ] LyA QSO via J-M Le Goff

desihub/desimodel#37 and related issue desihub/desimodel#35 provides utility code for assessing the footprint based upon the tile definitions.  Wrap that up and merge before updating mocks.

**Comment by moustakas** [comment]
Any updates on this?

**Comment by forero** [comment]
nothing from my side.

**Comment by fjaviersanchez** [comment]
@forero I have full-sky realizations for the Gaussian Random Mocks so, it is easy to update the footprint. Please, let me know the best way to do this. Should I upload the full catalog somewhere or do you prefer that I mask it and upload it to NERSC?

**Comment by forero** [comment]
@fjaviersanchez thanks! actually the best option for us would be having a python function with `ra`, `dec` as inputs and a boolean array as output telling us whether the corresponding `ra`/`dec` are inside/outside the footprint. In that way we can apply the same mask/code to all the input catalogs.

**Comment by dkirkby** [comment]
This already exists in desimodel.  See the relevant PR desihub/desimodel#37 for details.

**Comment by forero** [comment]
if that functions exists, then  @fjaviersanchez'offer is much appreciated, i.e. producing new mocks using `is_point_in_desi`and uploading them on NERSC.

**Comment by moustakas** [comment]
Although I would rather not apply the footprint in the mock code -- it would require reading into memory even more bits than we currently are, which is both slow and cumbersome, especially for testing.  Given that "the footprint" is (should be) a fairly slowly evolving function, I propose we just write out a set of mocks that span the footprint (plus a little border, for edge effects) and just bump up the version number of the mocks, for each spectral class.

**Comment by sbailey** [comment]
Thanks for re-jumpstarting this issue of updating the mocks to match the current footprint.
For simplicity, I suggest *not* adding a little border beyond what is implemented as the default radius in `desimodel.footprint.is_point_in_desi`.  The true DESI tile edge is ragged and any circular radius will be slightly wrong.  The default of the radius of the middle of the outermost positioner seems like a pragmatic choice.

HOWEVER: the default radius is calculated from the actual positioner locations and the desimodel description of that is out of date, though I don't know how big an effect the update will be.  Let's get everything ready to update the mocks but wait until we have updated the positioner locations before actually updating the mocks.  I can do that later this week after I'm back from the commissioning review Tues/Weds.

![tile_radius](https://cloud.githubusercontent.com/assets/218471/23002703/23a32a0a-f3a1-11e6-98e5-2de51227880e.png)

**Comment by apcooper** [comment]
I'm planning to do this update for the MWS/galaxia mock once I'm back from my current travels (about a week from now). This will be matched exactly to the footprint as defined by `is_point_in_desi` with no margin. I'll await news of the version that has @sbailey's blessing for this purpose, per the comment above.

I had a quick look using `is_point_in_desi` before I left, the margin in the v0.0.3 mock is not that big. However, the current footprint is also not quite aligned with my own approximation (which was based on tiles with `IN_DESI == true` in an earlier tile definition file). There are some places where the mock doesn't quite fill to the edge of the footprint.

(The MWS/100pc and MWS/WD mocks are all-sky but tiny, so I don't think any trimming is necessary for those)

**Comment by fjaviersanchez** [comment]
I am using the tiles from `test-0.5.0` and the footprint is smaller than the total DESI area. Are these tiles what I am supposed to be using?

I am doing:

`tiles = load_tiles()`

And then:

`mask = is_point_in_desi(tiles,ra,dec)`

**Comment by sbailey** [comment]
@fjaviersanchez `test-0.5.0` branch has a subset of the total tiles and should just be used for testing, not production work.  Please try master for now; we'll do an update of other aspects of desimodel later this week plus a new tag to use for production work.

**Comment by moustakas** [comment]
Thanks @fjaviersanchez.  Could you also update the `random.fits` (sky) mock catalog in
```
/global/project/projectdirs/desi/mocks/GaussianRandomField/v0.0.1/2048
```
or was this all-sky in the first place?  

Separately, by any chance do you have QA or some other visualization of the target density for each of these mocks?  For example, I'm finding that after assigning spectra and applying target selection the density (targets/deg2) of objects is below the level we need (e.g., 2400/deg2 for ELGs, 1400/deg2 for sky, etc.).  This suggests that we need to start with a more dense sampling of the density field.

**Comment by sbailey** [comment]
Note: I'll update desimodel fiber locations today, which will have some impact on the tile radius and thus the footprint.  I'll report whether it is a large enough difference to matter (and thus require updating mocks).

+1 for target selection QA; @geordie666 has some of that in the works and the code/plots that @fjaviersanchez and @dkirkby developed for the Ohio meeting presentation could also be used as a starting point.  As much as possible we should develop these as real target selection QA that also works on mocks, and keep anything that is specific to the mocks isolated as a separate QA.

**Comment by moustakas** [comment]
My student @kjnapes made [these visualizations](https://github.com/moustakas/siena-astrophysics/blob/master/research/desitarget/dr3_targets_skymaps.ipynb) for DR3 target selection and we could make them for the mocks, but I wanted to see if @fjaviersanchez had them handy already.

**Comment by fjaviersanchez** [comment]
I have some QA tools (just plotting the maps after selecting the footprint -- this can be done with `desiutil.plot.plot_healpix_map` or `desiutil.plot.plot_grid_map`). Do you think that we need more tools for this?

The original density of these mocks is twice the target density in DESI. Originally, we had just the DESI number density. After some discussion we were pointed to include twice as many targets to have the correct number density after target selection. I can change this to some other factor (maybe 2.5?). Please, let me know which factor I should use. 

@sbailey: Are you then updating the `random.fits` file?

**Comment by dkirkby** [comment]
I put all-sky plots of the mock samples in my plenary talk at the Dec
collaboration meeting (p.8) but they might be out of date now.

**Comment by sbailey** [comment]
Heads up: I've been working on restoring our cross-repo tests to a state of self-consistency and haven't gotten around to updating desimodel today, thus minor updates to the footprint edges are still pending.

**Comment by apcooper** [comment]
How's this going, @sbailey? I'm ready to update the MWS mock as soon as it's finalized. And to double check, the preferred radius argument for is_point_in_desi is 1.605 degrees?

**Comment by sbailey** [comment]
Sorry for the delay here.  I got bogged down adding the updated throughputs which don't directly apply here.  I have added the updated positioner locations in my private copy and checked that they have minimal impact on the edge effects, so you could go ahead and update the mocks using the current footprint in desimodel.

`is_point_in_desi()` now calculates a reasonable default for the radius based upon the positioner locations and platescale; that radius happens to be 1.60492, but you shouldn't need to specify it by hand if you have the latest desimodel (code master + svn trunk data).  There is some chance that I will make an updated tag today, so given your timezone @apcooper you could wait for the night and then proceed with or without me on Wednesday morning.

**Comment by apcooper** [comment]
Done: `/project/projectdirs/desi/mocks/mws/galaxia/alpha/v0.0.4`. I used the default radius.

**Comment by apcooper** [comment]
Just so there is a record of this here, Alex Smith (@amjsmith) made a new MXXL BGS mock (v0.0.4) on 27/4/2017 and fixed a bug in the footprint of that same mock on 22/5/2017 (no coverage above +30 deg in the southern part of the footprint)  -- see desi-bgs 653. 

`/project/projectdirs/desi/mocks/bgs/MXXL/desi_footprint/v0.0.4/BGS.hdf5`

**Comment by moustakas** [comment]
@sbailey Can you verify that this issue is safe to close?

**Comment by forero** [comment]
All the mocks we used in the `quicksurvey2017b` matched the footprint except the WD file. `select_mock_targets --no_spectra` trims anyway all files using `is_point_in_desi()`.

**Comment by sbailey** [comment]
Thanks for confirming, Jaime.  Let's close this.
