### ISSUE TITLE
speclite dependency

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#145]
We have now a `speclite` dependency in desitarget. How should that be included in the `travisCI`  configuration file?

**Comment by moustakas** [comment]
Remind me where the dependency appears?

**Comment by forero** [comment]
The dependencies chain is `desitarget`->`desisim`->`desispec`->`speclite`
See how travisCI fails: https://travis-ci.org/desihub/desitarget/jobs/197684291

**Comment by moustakas** [comment]
Oh, but that's on my branch.  I was going to fix this later.

**Comment by forero** [comment]
OK

**Comment by dkirkby** [comment]
In general, you should only need to specify direct dependencies for package installation (`setup.py`), travis or readthedocs, i.e., anything imported as a result of importing a `desitarget` module.  In this case, only the `desisim` dependency would need to be specified.
