### ISSUE TITLE
Tune bright star mask radius

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#155]
A followup to PR #153 which introduced bright star masks:

Tune the exclusion radius for bright stars, especially at the brightest end.  Distinguish between objects that should be flagged as IN_BRIGHT_OBJECT (i.e. set priority to 0 and don't observe because it might saturate the CCD and mess up neighboring objects) vs. objects that should just get an informational NEAR_BRIGHT_OBJECT flag but still be observed.

Design commissioning tests needed to validate this and make sure that the commissioning team is aware of it.

**Comment by geordie666** [comment]
Closing, as this is now essentially a duplicate of #471.
