### ISSUE TITLE
MTL: account for pre-assigned targets when updating list for fiber assignment

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#157]
See [DESI-2728](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=2728) for context about fiber assignment and survey strategy.  This includes the idea of "locking down" the assignments for a given tile.  When updating the Merged Target List (MTL) for future runs of fiber assignment, MTL needs to subtract these locked down assignments from the number of requested future observation, just as it does for subtracting previous successful operations.

**Comment by geordie666** [comment]
If I implemented the layer-based "locked down" targets strategy in MTL in #429, then it was inadvertent. It's possible that MTL does what is needed already, and this is now an issue for fiberassign, but as I'm not the expert on fiberassign I'll let @sbailey decide if this can be closed or shunted to an issue in fiberassign.
