### ISSUE TITLE
Option to skip generation of mock spectra

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#161]
It would be useful to have the option of turning off the generation of mock spectra in `select_mock_targets`, now that @moustakas's code for that is in master. This would allow rapid turnover of experimental catalog-only simulations (like those I'm discussing with @forero in desihub/quicksurvey_example#12).

I'm sure that option will be added eventually, but the sooner the better from my point of view (currently I'm using 0.9.0 for these catalog sims.)

**Comment by moustakas** [comment]
A version of this was done by @forero in #206.
