### ISSUE TITLE
Proposed change in the color range for selecting F-type spectrophotometric standards

### ISSUE THREAD

**Issue by callendeprieto** [desihub/desitarget#162]
We have verified with simulations and real observations from SDSS/SEGUE that the current baseline color cut for spectrophotometric F-type standards is not optimal. Even though it is based in the cuts used in SDSS (aimed for standard stars to be similar to BD +17 4708), lacking the u band lets in too many thick-disk stars at higher metallicity ([Fe/H]~ -0.7). Shifting the midpoint of the g-r range used to select F-type standards to the blue will increase the number of  targets from the metal-poor halo.

We explored first a common shift in both g-r and r-z, which seemed quite useful, and later fine tuned independent shifts in g-r and r-z, finding that leaving r-z alone and shifting the center of the interval in g-r by 0.06 mag would work well.

This is described in more detail on the wiki at
https://desi.lbl.gov/trac/wiki/TargetSelectionWG/STDalgorithms#ProposalforachangeinthebaselineselectionforF-typespectrophotometricstandards

**Comment by geordie666** [comment]
I'm happy to code this into desitarget (cuts.py), although we should probably have a discussion on the targeting telecon about whether this is a "proposed" cut or a "decided" one. If this was decided on the previous telecon, which I missed, then let me know and I'll code it up as soon as I find time.

**Comment by geordie666** [comment]
Closed by https://github.com/desihub/desitarget/pull/167
