### ISSUE TITLE
Travis-CI ?

### ISSUE THREAD

**Issue by rainwoodman** [desihub/desitarget#17]
Shall we add a travis-ci for, at least a top-level integrated test for targetselection.py ?

@sbailey 

I can take care of it -- played quite a bit of travis-ci recently.

**Comment by sbailey** [comment]
Yes, please!

**Comment by weaverba137** [comment]
Please follow the template packages when doing this.

**Comment by weaverba137** [comment]
You might also want to make sure that #15 is resolved first.
