### ISSUE TITLE
fix duplicate TARGETIDs in select_mock_spectra

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#178]
The current method of having select_mock_target work in patches of sky, and then do bricks within that patch results in duplicate TARGETIDs since multiple sub-pieces get the same random seed.  Fix this, e.g. using the recipe in desisim.templates.

In the meantime, we are reassigning TARGETIDs while merging the select_mock_targets into the final bricks, using [two_percent_survey/join_bricks.py](https://github.com/desihub/two_percent_DESI/blob/master/join_bricks.py).

Note: final real data TARGETIDs will be derivable from imaging survey tractor outputs without requiring random numbers.  This problem is specific to generating TARGETIDs for simulated data in parallel.

**Comment by moustakas** [comment]
This was addressed in https://github.com/desihub/two_percent_DESI/pull/2 but may still be happening with the adopted parallelization in #188.
