### ISSUE TITLE
derive target density fluctuations in healpixels, not bricks

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#185]
As the next iteration of #101, the target density fluctuations we use in `select_mock_targets` should be defined in healpixels, not bricks.

**Comment by moustakas** [comment]
Related to this question, should we ask the imaging team to repackage the sweeps (e.g., for DR5) into healpixels as well?  Or should we do that repackaging ourselves?

**Comment by moustakas** [comment]
@geordie666 What are the prospects for closing this issue?  I'm working on https://github.com/desihub/desitarget/issues/192 (among other outstanding issues) and the code I need to write would benefit from this update.

**Comment by geordie666** [comment]
I might be able to get to this early next week, if I prioritize it. Would that sort of timescale work for you?

**Comment by moustakas** [comment]
Yes, toward the end of ~next week would be great, thanks.

**Comment by geordie666** [comment]
Closed in https://github.com/desihub/desitarget/pull/217
