### ISSUE TITLE
desitarget not desiInstall compatible

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#19]
desiInstall at NERSC produces a borked installation of desitarget/0.2.0.  This is likely due to desitarget being non-compliant rather than a problem with desiInstall per-se.  Figure out what is wrong and fix it so that "desiInstall desitarget 0.2.1" will work.

The error from the current desitarget/0.2.0 is:
```
[cori target] time select_targets /project/projectdirs/desiproc/dr2/sweep/ targets-dr2-0.2.0.fits -v
Traceback (most recent call last):
  File "/project/projectdirs/desi/software/cori/desitarget/0.2.0/bin/select_targets", line 8, in <module>
    from desitarget import io
  File "/project/projectdirs/desi/software/cori/desitarget/0.2.0/lib/python2.7/site-packages/desitarget-0.2.0-py2.7.egg/desitarget/__init__.py", line 41, in <module>
    from .targetmask import priorities, obsconditions, obsstate
  File "/project/projectdirs/desi/software/cori/desitarget/0.2.0/lib/python2.7/site-packages/desitarget-0.2.0-py2.7.egg/desitarget/targetmask.py", line 13, in <module>
    with open(_filepath) as fx:
IOError: [Errno 2] No such file or directory: '/project/projectdirs/desi/software/cori/desitarget/0.2.0/lib/python2.7/site-packages/desitarget-0.2.0-py2.7.egg/desitarget/targetmask.yaml'
```

targetmask.yaml is not copied to the installation directory.  I will fix this by hand for the current 0.2.0 installation so that we can make progress with it in the meantime.

**Comment by weaverba137** [comment]
Indeed, this isn't a problem with desiInstall.  It is a problem with the structure of the Python package.  The targetmask.yaml file lives in the py/desitarget directory, but the *default* behavior of setup.py is to ignore everything in the package directory that is not a .py file.

This is easy to fix.  The package needs a setup_package.py file in py/desitarget with these contents:

```python
def get_package_data():
    return {'desitarget': ['targetmask.yaml',],}
```
If additional data files are added, they should also be listed in this file.

See also https://github.com/weaverba137/pydl/blob/master/pydl/setup_package.py

**Comment by sbailey** [comment]
Is there a particular advantage to putting this into desitarget.setup_package.get_package_data(), rather than just putting that info directly into setup.py?  I could see an advantage if it was returning a standardized full path to targetmask.yaml, thus avoiding `_thisdir = os.path.dirname(__file__); _filepath = os.path.join(_thisdir, "targetmask.yaml")`.  But lacking that, is there a reason why it should be a user-importable function vs. tucked away in setup.py as part of the installation instructions?

**Comment by weaverba137** [comment]
The thing about the setup_package.py file is that you can have that file multiple times in various subdirectories of a complex Python package.  If that level of complexity is unlikely to ever be reached, then it doesn't make much difference.

**Comment by sbailey** [comment]
Fixed via setup.py change in PR #18.  If the complexity of the package grows we can refactor to use separate functions as @weaverba137 describes.
