### ISSUE TITLE
rerun target selection on DR3.1 and DR4

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#196]
@geordie666 Now that #179 has been merged, can you please rerun the targeting code on both DR3.1 and DR4 so we can work with a more updated set of LRG targets?  Thanks!

**Comment by geordie666** [comment]
The barrier to running target selection on DR4 is merging the https://github.com/desihub/desitarget/tree/datamodelADM branch. That's the branch that contains the DR3->DR4 conversion. I wouldn't want to run the DR4 "official" targets until that branch is "officially" in master.

**Comment by sbailey** [comment]
Now that we are past the collaboration meeting and have tags of the products that people can work with, let's proceed with merging the DR4 datamodel updates and continue with that.

**Comment by geordie666** [comment]
Give me until the end of the day. I want to add in RELEASE->PHOTSYS
capability, and update our definition of TARGETID to include RELEASE...plus
after my latest merge of master into the datamodelADM branch unit tests are
broken.

**Comment by geordie666** [comment]
Closed with version 0.14.0 of desitarget
