### ISSUE TITLE
Review the columns in the output target files and decide if they're all needed

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#197]
Determine whether we need the `ivar` columns for shape, `fracdev` etc.. And simplify the data model if certain columns are unnecessary downstream.

**Comment by dkirkby** [comment]
We will need the full set of shape parameters to estimate the expected fiber acceptance fraction for each target, including the exp & dev ellipticities (e1,e2) in a frame that can be transformed to DESI focal-plane (x,y).

**Comment by geordie666** [comment]
This should be fixed in #635, where the philosophy would be to use the minimum set of columns for MTL and `desitarget.mtl.inflate_ledger()` to recover additional columns for other purposes. I'll leave this open for now, though, until we've decided to what degree we will implement #635 downstream.
