### ISSUE TITLE
improve select_targets traceability

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#20]
Improve the target selection traceability by tracking the complete list of input files used and their checksums.

The output of select_targets includes the desitarget version, the git revision (if running from a git checkout for testing; otherwise "unknown", though perhaps that should be the tag), and the input directory of files used, e.g.

```
DEPNAM00= 'desitarget'                                                          
DEPVER00= '0.2.0   '           / desitarget.__version__                         
DEPNAM01= 'desitarget-git'                                                      
DEPVER01= 'unknown '           / git revision                                   
DEPNAM02= 'tractor-files'                                                       
DEPVER02= '/project/projectdirs/desiproc/dr2/sweep/'                            
```

but it doesn't actually trace what files it found under /project/projectdirs/desiproc/dr2/sweep/ or what their checksums were (to be able to check whether someone mucked with the files later, e.g. since this isn't the real final locked down publicly released DR2 directory).

Add another bintable HDU that tracks the actual files used as input and their checksums.  In the case of tractor files as inputs instead of sweeps this could be a long list so it requires a table and not just DEPNAM/DEPVER header keywords.  Don't include the common path prefix that is already kept as DEPVER02.

**Comment by geordie666** [comment]
Addressed in #641.
