### ISSUE TITLE
Add r magnitudes into truth for BGS mocks

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#201]
All sorts of interesting QA plots for BGS depend on `r` magnitudes. Having that additional column in the truth makes our life easier.

**Comment by moustakas** [comment]
The data model hasn't been updated but the *noiseless* r-band magnitude is in the `decam_flux[2]` column.  (With the DR4 data model this quantity will be in the `flux_r` column.)

The *noisy* r-band flux is in the same column of the `targets.fits` file.

I would not support mixing the quantities in these two tables (e.g., putting the noisy, "observed" r-band flux in the truth catalog).

**Comment by moustakas** [comment]
I think this issue has been addressed for some time; closing.
