### ISSUE TITLE
Priorities for standard stars

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#205]
Carried over from #169 

STD_WD should have priority over STD_FSTAR (and other types of standard if we add more), but there is no concept of priority for standards in the current code. This probably needs to be implemented in desitarget *and* fiberassign.

**Comment by moustakas** [comment]
It was discussed and decided in #337 and https://github.com/desihub/fiberassign/issues/78 that standard stars would *not* be rank-ordered, in order to not create issues with the selection and priorities of MWS *science* targets.
