### ISSUE TITLE
add additional columns to the targets catalog produced by mock.build.targets_truth

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#209]
This issue is a spin-off of the conversation in #207 to document the set of columns that mismatch between the mock targets catalog and a "real" targets catalog.

The following columns are not currently in the mock targets catalog but we should discuss how to include them.  Many were flagged by @geordie666 as "probably not needed" (particularly if `TARGETID` is generated using `targets.encode_targetid`, which it is) while others will simply require more thought.

* `RELEASE` - "Probably not needed."
* `TYPE` - This should be consistent with the shapes in the catalog (which are based on the GMMs). This could be potentially useful as a spectroscopic prior on star/galaxy.
* `RA_IVAR`, `DEC_IVAR` - We should include these using the astrometric error model of the imaging catalogs; these also may be useful for fiberassignment simulations.
* `DCHISQ` - This could be potentially useful as a spectroscopic prior on star/galaxy.
* `FLUX_W3`, `FLUX_W4` - Our templates don't go red enough (and don't include the dust emission necessary) to synthesize good fluxes in these bands.
* `FLUX_IVAR_[G,R,Z,W1,W2,W3,W4]` - These require some thought. Right now I'm using a constant depth (for each brick) to add variance to the noiseless/true photometry, in which case these could all be set to constant values for all the objects on a given brick.  But we probably want something a little more sophisticated, particularly something that takes into account the Poisson noise of the object itself.  One possibility would be to train a GMM.
* `NOBS_[G,R,Z]` - I'm not sure how these would be defined for a mock but "probably not needed."
* `FRACFLUX_[G,R,Z]` - "Probably not needed."
* `PHOTSYS` - "Probably not needed."

**Comment by moustakas** [comment]
There have been some significant changes in the *targets* data model (in DR6+DR7) since this issue was first raised, so I'm updating it here.  Below is the list of columns which are in the current targeting catalog (specifically, `/global/projecta/projectdirs/desi/target/catalogs/dr7.1/0.23.0/targets-dr7.1-0.23.0.fits` but which are *not* in the *mock* targeting catalog (here, using `/global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/targets.fits`, written as part of the 18.6 software release, I think).

Many of the comments written [here](https://github.com/desihub/desitarget/issues/209#issue-249093705) likely still apply, although I'll try to go through and include as many of the missing columns as possible in a forthcoming refactor of the `select_mock_targets` code.

Some related issues are #352, #339, and #305.

```
RELEASE
TYPE
RA_IVAR
DEC_IVAR
DCHISQ
FLUX_W3
FLUX_W4
FLUX_IVAR_G
FLUX_IVAR_R
FLUX_IVAR_Z
FLUX_IVAR_W1
FLUX_IVAR_W2
FLUX_IVAR_W3
FLUX_IVAR_W4
MW_TRANSMISSION_W3
MW_TRANSMISSION_W4
NOBS_G
NOBS_R
NOBS_Z
FRACFLUX_G
FRACFLUX_R
FRACFLUX_Z
FRACMASKED_G
FRACMASKED_R
FRACMASKED_Z
ALLMASK_G
ALLMASK_R
ALLMASK_Z
FRACDEV
FRACDEV_IVAR
SHAPEDEV_R_IVAR
SHAPEDEV_E1_IVAR
SHAPEDEV_E2_IVAR
SHAPEEXP_R_IVAR
SHAPEEXP_E1_IVAR
SHAPEEXP_E2_IVAR
REF_ID
GAIA_PHOT_G_MEAN_MAG
GAIA_PHOT_G_MEAN_FLUX_OVER_ERROR
GAIA_PHOT_BP_MEAN_MAG
GAIA_PHOT_BP_MEAN_FLUX_OVER_ERROR
GAIA_PHOT_RP_MEAN_MAG
GAIA_PHOT_RP_MEAN_FLUX_OVER_ERROR
GAIA_ASTROMETRIC_EXCESS_NOISE
GAIA_DUPLICATED_SOURCE
PARALLAX
PARALLAX_IVAR
PMRA
PMRA_IVAR
PMDEC
PMDEC_IVAR
BRIGHTSTARINBLOB
PHOTSYS
```

**Comment by moustakas** [comment]
Below is the current data model of the simulated *target.fits* file generated by the #368 version of `select_mock_targets`, which can be compared with the (current `targets-dr7.1-0.23.fits`) data model for the actual targeting catalogs)[https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/targets.html). 

There are a total of 88 columns here, compared to 86 columns in the official catalog.  The additional columns are `PRIORITY` and `NUMOBS` which were added in #346.

I've included some comments below.  @sbailey @geordie666 if these choices look OK I'd like to close this issue.
```
                          RELEASE   int32                      -- fixed at 9999
                          BRICKID   int32                      -- healpix pixel number
                        BRICKNAME  bytes8                      
                      BRICK_OBJID   int32                      -- unique integer array for all science+sky targets in a healpixel
                             TYPE  bytes4                      
                               RA float64                   deg
                              DEC float64                   deg
                          RA_IVAR float32              1 / deg2 -- fixed at 1e8
                         DEC_IVAR float32              1 / deg2 -- fixed at 1e8
                           DCHISQ float32  (5,)                 -- fixed at [0, 100, 200, 300, 400] (to facilitate QSO selection)
                           FLUX_G float32           nanomaggies
                           FLUX_R float32           nanomaggies
                           FLUX_Z float32           nanomaggies
                          FLUX_W1 float32           nanomaggies
                          FLUX_W2 float32           nanomaggies
                          FLUX_W3 float32           nanomaggies
                          FLUX_W4 float32           nanomaggies
                      FLUX_IVAR_G float32       1/nanomaggies^2
                      FLUX_IVAR_R float32       1/nanomaggies^2
                      FLUX_IVAR_Z float32       1/nanomaggies^2
                     FLUX_IVAR_W1 float32       1/nanomaggies^2
                     FLUX_IVAR_W2 float32       1/nanomaggies^2
                     FLUX_IVAR_W3 float32       1/nanomaggies^2
                     FLUX_IVAR_W4 float32       1/nanomaggies^2
                MW_TRANSMISSION_G float32                      
                MW_TRANSMISSION_R float32                      
                MW_TRANSMISSION_Z float32                      
               MW_TRANSMISSION_W1 float32                      
               MW_TRANSMISSION_W2 float32                      
               MW_TRANSMISSION_W3 float32                      
               MW_TRANSMISSION_W4 float32                      
                           NOBS_G   int16                        -- fixed at 2 for all bands
                           NOBS_R   int16                      
                           NOBS_Z   int16                      
                       FRACFLUX_G float32                        -- fixed at 0.0 for all bands
                       FRACFLUX_R float32                      
                       FRACFLUX_Z float32                      
                     FRACMASKED_G float32                        -- fixed at 0.0 for all bands
                     FRACMASKED_R float32                      
                     FRACMASKED_Z float32                      
                        ALLMASK_G float32                        -- fixed at 0.0 for all bands
                        ALLMASK_R float32                      
                        ALLMASK_Z float32                      
                       PSFDEPTH_G float32       1/nanomaggies^2  -- constant PSF/galaxy depth for all bands
                       PSFDEPTH_R float32       1/nanomaggies^2
                       PSFDEPTH_Z float32       1/nanomaggies^2
                       GALDEPTH_G float32       1/nanomaggies^2
                       GALDEPTH_R float32       1/nanomaggies^2
                       GALDEPTH_Z float32       1/nanomaggies^2
                          FRACDEV float32                      
                     FRACDEV_IVAR float32                      
                       SHAPEDEV_R float32                arcsec
                  SHAPEDEV_R_IVAR float32           1 / arcsec2
                      SHAPEDEV_E1 float32                      
                 SHAPEDEV_E1_IVAR float32                      
                      SHAPEDEV_E2 float32                      
                 SHAPEDEV_E2_IVAR float32                      
                       SHAPEEXP_R float32                arcsec
                  SHAPEEXP_R_IVAR float32           1 / arcsec2
                      SHAPEEXP_E1 float32                      
                 SHAPEEXP_E1_IVAR float32                      
                      SHAPEEXP_E2 float32                      
                 SHAPEEXP_E2_IVAR float32                      
                           REF_ID   int64                        -- equivalent to MOCKID in the truth.fits file
             GAIA_PHOT_G_MEAN_MAG float32                      
 GAIA_PHOT_G_MEAN_FLUX_OVER_ERROR float32                      
            GAIA_PHOT_BP_MEAN_MAG float32                      
GAIA_PHOT_BP_MEAN_FLUX_OVER_ERROR float32                      
            GAIA_PHOT_RP_MEAN_MAG float32                      
GAIA_PHOT_RP_MEAN_FLUX_OVER_ERROR float32                      
    GAIA_ASTROMETRIC_EXCESS_NOISE float32                      
           GAIA_DUPLICATED_SOURCE    bool                      
                         PARALLAX float32                      
                    PARALLAX_IVAR float32                      
                             PMRA float32                      
                        PMRA_IVAR float32                      
                            PMDEC float32                      
                       PMDEC_IVAR float32                      
                 BRIGHTSTARINBLOB    bool                      -- False for all objects
                          PHOTSYS  bytes1                      -- N/S based on constant-declination cut
                         TARGETID   int64                      
                      DESI_TARGET   int64                      
                       BGS_TARGET   int64                      
                       MWS_TARGET   int64                      
                         PRIORITY   int64                      
                      SUBPRIORITY float64                      
                           NUMOBS   int64                      
                         HPXPIXEL   int64                      
```

**Comment by geordie666** [comment]
These choices look OK...although, as you know, the data model will change (slightly) again for DR8 (for instance `BRIGHTSTARINBLOB` is being renamed.

One thought is that you might want to use the current `RELEASE` number of `7000` instead of `9999` to illustrate what DR the mocks are currently mocking, in case downstream code cares about the value of `RELEASE`. Alternatively use a "ridiculous" `RELEASE` number like `31999` that we can keep downstream for all time. We will plausibly get to DR9, but I doubt we'll get to DR31. Note (as you will have already surmised) that the largest `RELEASE` number that doesn't break `TARGETID` should be  2**15-1 = 32767.

I'll add `PRIORITY` and `NUMOBS` to the data model now.

**Comment by sbailey** [comment]
A few items (for both mocks and the real target catalog):
* `BRICKID`: let's use the real ra,dec -> brickid mapping rather than the healpix number, especially since we also have a HPXPIXEL column.  Create a `b = desiutil.brick.Bricks(bricksize=0.25)` object, then call `b.brickid(ra,dec)`.
* `TYPE` -> `MORPHTYPE`.  Although we generally don't want to rename columns arbitrarily, there are too many other "types" downstream (spectype, postionertype, objtype, ...) so by the time this gets to the ICS it needs to be "MORPHTYPE".  Let's do this change here at target selection (I would prefer it to even happen upstream in the sweeps or tractor, but that may be a can of worms).
* Let's drop the unused W3 and W4 fields (FLUX_, FLUX_IVAR_, MW_TRANSMISSION_) unless there is a strong science case for keeping them (they aren't used by targeting or the spectro pipeline).

**Comment by geordie666** [comment]
I can work on these changes to the data model (for the real data) today, unless it will conflict heavily with the work that @moustakas is currently conducting on the mocks. @moustakas?

**Comment by moustakas** [comment]
Go for it!

**Comment by sbailey** [comment]
One more: let's keep the `EBV` column from the sweeps so that we don't have to keep looking it up from the dust maps every time we need it (e.g. in flux calibration).

**Comment by moustakas** [comment]
I'm ambivalent about what `RELEASE` should be.  The only place it's used AFAIK is for some target classes in `cuts.apply_cuts` (requiring `RELEASE>5000`), but these cuts are already applied in `select_mock_targets` before the catalogs are written out.

A potentially related issue might be #231, but shouldn't we be using `PHOTSYS` (N/S) to differentiate photometric systems since starting in DR8, `RELEASE=8000` will include photometry from both BASS+MzLS *and* DECaLS(?)

@sbailey Do you have any suggestions or a strong opinion?

**Comment by geordie666** [comment]
Note that `PHOTSYS` is actually directly derived from `RELEASE` using a look-up table. So, they're kinda equivalent-y.

I think that for DR8, BASS/MzLS will have a number like `RELEASE=8001` and DECaLS would have `RELEASE=8000`. Or something like that.

**Comment by moustakas** [comment]
> Note that PHOTSYS is actually directly derived from RELEASE using a look-up table. So, they're kinda equivalent-y.

So why are we carrying both around?  The practical question is:  given that each target will have *one* set of `FLUX_[GRZ]` values, what column indicates the photometric system that those correspond to?  

Establishing `PHOTSYS=N/S` in the target catalogs themselves (i.e., deciding ahead of time which photometric system to adopt in the overlap region) seems much simpler to me for the downstream code (e.g., for flux calibration -- https://github.com/desihub/desispec/issues/680) than having to look up the mapping between `RELEASE` and `PHOTSYS` on the fly.  And it's also much simpler for the mock catalogs.

> I think that for DR8, BASS/MzLS will have a number like RELEASE=8001 and DECaLS would have RELEASE=8000. Or something like that.

So DR8 will have two sets of target catalogs?  I hope not!  I think we need to decide where to split the photometric catalogs (see #353 and #295), setting `PHOTSYS` in, and then calling `south=True/False` in `cuts.apply_cuts` as appropriate.  (This is what I've implemented in `select_mock_targets`.)

Targets in the overlap region can then be studied separately since that region will only be a few hundred sq. degrees.

**Comment by geordie666** [comment]
I think we're actually in complete agreement here.

The missing piece is that ultimately (for the real data) we'll need a resolve to set 'PHOTSYS = N/S' that is applied geographically (e.g., at Declination ~ 32o). It's not clear, yet, whether that resolve will occur in the sweeps themselves or at the level of targeting (with an extra single piece of logic that sets 'PHOTSYS' on `RELEASE` *and* Declination in `cuts.apply_cuts`).

It's clear, though (I think) that targets could have different `RELEASE` numbers depending on whether they come from BASS/MzLS or DECaLS. They already do.

**Comment by geordie666** [comment]
Oh, and my intention is not that you look up the mapping from `RELEASE` to `PHOTSYS` on the fly. My intention is that targeting sets `PHOTSYS` and then downstream code uses `PHOTSYS`. Again, at the moment, target selection just uses a look-up table to do this, but will ultimately have to add a geographic cut to derive `PHOTSYS` (unless there's some sort of separate resolve code in the overlap region).

**Comment by moustakas** [comment]
@sbailey 

> BRICKID: let's use the real ra,dec -> brickid mapping rather than the healpix number, especially since we also have a HPXPIXEL column. Create a b = desiutil.brick.Bricks(bricksize=0.25) object, then call b.brickid(ra,dec).

I finally remembered why we don't do this.  The issue is that healpixels cut across bricks, and so objects on the same brick but on different healpixels will end up with the same `TARGETID` (which is constructed from `BRICK` and `BRICK_OBJID`, the latter of which we take to be an integer array.

As a compromise---if you want---I could use the healpixel number to construct `TARGETID` as we do now but populate `BRICKID` with the correct values.  Please let me know.

**Comment by sbailey** [comment]
@moustakas about `BRICKID`: ugh.  Let's keep it as-is (brickid = hpxpixel in the sims) and fix it later if it actually becomes a problem that the mock `BRICKID` boundaries don't match real data.  I can see that keeping the `BRICK_OBJID` to not collide would be a pain to coordinate across the parallelism.

**Comment by moustakas** [comment]
OK, all requested changes have been done in #368.
