### ISSUE TITLE
make target selection QA plots

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#21]
Make QA plots for target selection as a standard part of the output.

Version 0.2.0 produced target densities considerably different than expected; the first sanity check for bugs is to make the basic color color plots and see what the distributions look like pre- and post- cuts.  The underlying distributions may be much different than expected, or there may be a simple sign error that would be obvious from a plot but easy to miss when reading code.

**Comment by geordie666** [comment]
One necessary piece of QA: Make sure no brick contains more targets than we will encode in `TARGETID`

**Comment by moustakas** [comment]
Initial QA code incorporated by @geordie666 in #210.
