### ISSUE TITLE
add SUBPRIORITY to target catalog

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#221]
fiberassign needs a "SUBPRIORITY" column float [0,1) in the target catalog to use as a way to break ties between otherwise equivalent priority assignments.  For most targets this can be a random number, but it is something that we want encoded in the target catalog itself, not a random choice made by fiber assignment.  The MWS may use subpriority as a meaningful way of fine-gained ranking its targets.

**Comment by geordie666** [comment]
I'm planning on solving some small issues a day or so before I run the official DR5 targets (once DR5 is officially released). I'll add this then. It may even be as soon as Friday.

**Comment by geordie666** [comment]
Closed in https://github.com/desihub/desitarget/pull/229 and by spinning off individual items to https://github.com/desihub/desitarget/issues/230 and https://github.com/desihub/desitarget/issues/231
