### ISSUE TITLE
Healpix pattern in the mock outputs 

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#227]
The current version of `mpi_select_mock_targets --no-spectra` produces an evident healpix pattern in the outputs that were downsampled to have a mean number density

![image](https://user-images.githubusercontent.com/1848618/31419902-64dc7dd0-ae79-11e7-9da6-451e5ff98c12.png)

![image](https://user-images.githubusercontent.com/1848618/31419914-6d221f9a-ae79-11e7-92a7-d77f7f62635d.png)

![image](https://user-images.githubusercontent.com/1848618/31419919-7240d5e8-ae79-11e7-919a-83b04c7fcfe2.png)

![image](https://user-images.githubusercontent.com/1848618/31419926-7c4fb220-ae79-11e7-9eff-a19e6ef2a723.png)

The reason for this is that the parallelization is done on healpixels and the number density is estimated using bricks, for the bricks that are on the boundaries between healpixels the number density estimation is wrong. In other words, the pattern comes from the bricks being cut between two neighboring healpixels.

I am working on a solution and should have a PR ready during the day.

**Comment by moustakas** [comment]
Closed in #228
