### ISSUE TITLE
Incorporate Gaia catalogs for MWS target selection

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#233]
We need to make sure that Gaia catalogs get incorporated with the imaging data releases for:
* MWS target selection
* standard star proper motions
* BGS contamination rejection

The original schedule was that the imaging surveys would do this for DR6 in January 2018.  If that doesn't happen, we need to scope a backup plan or put pressure to make sure that it really does happen for DR7 (July 2018).  It would even be helpful if they would include placeholder column names so that we can start propagating the columns downstream even if they aren't filled in.

**Comment by apcooper** [comment]
Recent discussion among MWS, David Schlegel and @geordie666 came up with the following list of Gaia columns relevant to MWS target selection (copied from @segasai's email desi-milkyway 639):
```
source_id,ra,dec,pmra,pmdec,pmra_err,pmdec_err,parallax_error, g_mag,g_mag_error,
bpmag, bgmag_error,rpmag, rpmag_error, astrometric_excess_noise 
```
It would be good to have these implemented on a similar timescale to #286, pre-Tucson, so we could move forwards with updating the target selection code for MWS.

**Comment by apcooper** [comment]
List above was missing parallax. Full list is:
```
source_id,ra,dec,pmra,pmdec,pmra_err,pmdec_err, parallax, parallax_error, g_mag,g_mag_error,
bpmag, bgmag_error,rpmag, rpmag_error, astrometric_excess_noise 
```

**Comment by moustakas** [comment]
Done in #338 for DR7 (where Gaia/DR2 was used as a prior) and in #340 for DR6 (using coordinate matching).  DR8 will include all Gaia columns needed for targeting and downstream code in a self-consistent way.
