### ISSUE TITLE
Include proper motion information in TS catalogs

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#234]
Related to #233 (include Gaia): we need to propagate proper motion information in the target selection catalogs, and through fiber assignment into the next field selector output to ICS.

Even if Gaia is not yet incorporated into the imaging data releases, we could define placeholder column names based upon Gaia and add those in `desitarget.io.read_tractor` if they are missing from the input files.

**Comment by moustakas** [comment]
Done in #338 and #340 and documented in the data model:
https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/targets.html
