### ISSUE TITLE
Include existing redshifts in target catalog.

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#243]
I believe that the baseline BGS plan is to reobserve galaxies with existing redshifts (e.g., from SDSS) at lower priority and to not(?) re-observe LRG targets with existing redshifts.  Either way, the data model of the target catalog (as well as the code) needs to be updated / enhanced to accommodate one or more external catalogs of galaxy/QSO redshifts.  We also likely need to add more targeting bits to accommodate this change.

This issue is broadly related to #233.

[Forgive me if this issues exists somewhere and I just missed it.]

**Comment by geordie666** [comment]
In the end, we did not implement any prior knowledge of SDSS redshifts.
