### ISSUE TITLE
support the new Buzzard mocks in select_mock_targets

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#249]
@j-dr has produced a new set of DESI mocks which should be suitable for the BGS, ELG, and LRG samples simultaneously.  The mocks are here for those that are interested:
  /global/project/projectdirs/desi/mocks/buzzard

I'm self-assigning this to support these mocks as an option in the various data challenges.

@j-dr If you get a chance could you add some QA to this issue showing the footprint of the mock and perhaps the r-band number counts vs, e.g., the current BGS/MXXL mock, as a point of comparison?

**Comment by shadaba** [comment]
These mocks also have magnitude which needs to be read for calculating number of observations. I have run fibre assign on them to test but using input format: gaussianfield, which only uses RA,DEC, Z_COSMO, DZ_RSD . How can one add additional field like magnitude to be used for calculating number of observations to support these mocks.

Happy to contribute to this if someone can show where to start as it is needed by clustering and C3 groups.

Here is example template file used on NERSC:
/global/cscratch1/sd/shadaba/fibertest/quicksurvey_example/targets/no_spectra/dark/select-mock-targets-dark.yaml

**Comment by moustakas** [comment]
@shadaba @j-dr Is there still an interest in including the Buzzard mocks in the full-pipeline simulations? If so, I have some time to include them -- please let me know.

**Comment by moustakas** [comment]
A reasonable first implementation was done in #427.
