### ISSUE TITLE
Add/organize mock target QA

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#258]
We have various notebooks and emails about mock target QA — organize these into a standardized set of mock target QA numbers and plots similar to `desitarget/bin/run_target_qa` output.

**Comment by moustakas** [comment]
Initial progress was made in #262 but let's keep this open for now.

**Comment by geordie666** [comment]
We decided on today's telecon to close this and track it instead in the various "enhancement" issues that we span off:

https://github.com/desihub/desitarget/issues/266
https://github.com/desihub/desitarget/issues/267
https://github.com/desihub/desitarget/issues/268
https://github.com/desihub/desitarget/issues/269
https://github.com/desihub/desitarget/issues/270
https://github.com/desihub/desitarget/issues/271
https://github.com/desihub/desitarget/issues/272
