### ISSUE TITLE
Scatter plots for QA/mock QA

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#266]
Hexbin color-color plots, e.g. at:

http://portal.nersc.gov/project/cosmo/temp/ioannis/refactor/LRG.html

potentially make it difficult to see bug-gy patterns. Suggest randomly sampling 1000 points from the input target class and producing a scatter plot (in addition to the current hex-plot)

**Comment by moustakas** [comment]
Added in #427.  See, e.g., [here](http://portal.nersc.gov/project/desi/users/ioannis/mock-targets/PR427-dr7.1/).
