### ISSUE TITLE
Include expected redshift distribution in mock QA

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#269]
For the first "True Redshift" plot, e.g., at:

http://portal.nersc.gov/project/cosmo/temp/ioannis/refactor/ELG.html

include the expected N(z) from `desimodel`.

**Comment by moustakas** [comment]
Done in #427.  See, e.g., [here](http://portal.nersc.gov/project/desi/users/ioannis/mock-targets/PR427-spectra-onepixel/).
