### ISSUE TITLE
F-star distribution in mocks appears bimodal

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#270]
For example, in the color-color plots at:

http://portal.nersc.gov/project/cosmo/temp/ioannis/refactor/STD_FSTAR.html

The F-stars seems to occupy two distinct regions in `r-z`. Is this expected behavior?

**Comment by moustakas** [comment]
I think this is a known "feature" due to the fact that we're not interpolating the stellar spectra and that we're selecting standards using SDSS bandpasses and the BOSS selection criteria (see https://github.com/desihub/desisim/issues/315 and https://github.com/desihub/desitarget/issues/256).

**Comment by moustakas** [comment]
Fixed

**Comment by moustakas** [comment]
(Oops, pressed some keyboard combination.)

Fixed in #427 if not earlier.  Various QA output can be inspected [here](https://github.com/desihub/desitarget/pull/427#issuecomment-446658529).
