### ISSUE TITLE
Striping in mock QSO magnitude and redshift distributions

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#271]
For example, in the second "True Redshift" plot at:

http://portal.nersc.gov/project/cosmo/temp/ioannis/refactor/QSO.html

the QSOs occupy distinct bands in Normalization Magnitude. There is also a gap between the redshifts of the tracer QSOs and the Lyman-alpha QSOs (at ~1.7 < z < 2).

**Comment by moustakas** [comment]
The gap in redshift will be corrected with the next version of the CoLoRe mocks, and is being tracked in https://github.com/desihub/desisim/issues/295.  

The gap in normalization magnitude is something I definitely need to track down and I have an idea.

**Comment by moustakas** [comment]
The discretization of the magnitudes was indeed due to a bug (basically, I was reusing the same random seed) which was fixed in #264.  Closing this issue.
