### ISSUE TITLE
ReadTheDocs builds are failing

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#279]
The build of documentation on [ReadTheDocs](http://desitarget.readthedocs.io) is failing for more-or-less the exact same reasons as desihub/redrock#80.

**Comment by geordie666** [comment]
I'm offering [this](https://github.com/desihub/desitarget/compare/ADM-fix-rtd-build) as a possible fix for the failing [ReadTheDocs](http://desitarget.readthedocs.io) build. It's probably not the most elegant solution but (I think) it works. As I'm new to fixing these sorts of builds, I'm not issuing a PR in case there's an obvious flaw.

@weaverba137: Please comment if you can thing of a more elegant fix.
@sbailey: Please scream if this is going to break a bunch of imports elsewhere on desihub.

**Comment by weaverba137** [comment]
It will be much easier to review this if you actually create a pull request.

**Comment by geordie666** [comment]
Done. Although feel free to disregard and close the PR if I'm wildly off-base on my proposed fix.

**Comment by geordie666** [comment]
Fixed in https://github.com/desihub/desitarget/pull/282
