### ISSUE TITLE
code on NERSC

### ISSUE THREAD

**Issue by mehdirezaie** [desihub/desitarget#28]
I am kind of new to the topic. I would like to see some examples (if available any). I have started reading this doc on the wiki (http://desi.lbl.gov/wp-content/uploads/2014/04/tdr-science-biblatex2.pdf). I was wondering if someone could point me out in the right direction. Another question is that how I can find these directory on NERSC?
Thank you,
--mehdi

**Comment by sbailey** [comment]
This moved to emails on desi-data and direct emails.  Closing ticket.  If you still have questions, please email me directly.
