### ISSUE TITLE
Add FRACDEV to target catalog output

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#293]
In order to meaningfully use the SHAPEDEV_* and SHAPEEXP_* parameters, we also need to know the fraction of light assigned to each shape, i.e. FRACDEV.  Add this to the target selection output catalog.  For completeness we could propagate FRACDEV_IVAR too.

The downstream pipeline doesn't yet use these quantities, but in principle in the future we could/should, e.g. to calculate a fiber magnitude given the spectroscopic exposure seeing.

**Comment by moustakas** [comment]
Done in #294.
