### ISSUE TITLE
handling targets in north / south overlap regions

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#295]
Develop a clear documented plan + code for how to handle targets that appear in both southern and northern photometry (i.e. same object with different RELEASE values).  Requirements:

* The input to fiberassign should have one and only one entry per object, i.e. something upstream of fiberassign chooses whether to pass forward the northern or southern version of each object.
* the survey footprint should be split into two areas (north and south) not 3 (north-only, south-only, and overlap).
* files are available to conveniently study the overlap, e.g. to cross compare the measured photometry and target selection efficiencies.

**Comment by geordie666** [comment]
Fully addressed using `--resolve` and `--noresolve` options for all relevant target classes in #497.
