### ISSUE TITLE
allmask_* columns not included in DR5 catalog

### ISSUE THREAD

**Issue by belaa** [desihub/desitarget#298]
I am trying to apply target selection cuts on the dr5 target catalog:

`/global/project/projectdirs/desi/target/catalogs/targets-dr5-0.16.2.fits` 

 but running `desitarget.cuts.appy_cuts()` returns the following error:

`KeyError: 'ALLMASK_G'`

**Comment by geordie666** [comment]
The target code is designed to run on `sweeps-` or `tractor-` files. It is not guaranteed to run out-of-the-box on any file type with any set of columns.

Nevertheless, as `ALLMASK_G` was added to the output file from target selection (the `targets-` file) starting with version 0.20.0 of the code:

https://github.com/desihub/desitarget/pull/294/files

The target code will *probably* run OK on the file `targets-dr5-0.20.0.fits`

**Comment by geordie666** [comment]
Alternatively, if version `0.16.2` of the targets file is critical for some reason, check out version `0.16.2` of `desitarget` and then apply that to the `targets-dr5-0.16.2.fits` file:

`git checkout tags/0.16.2 -b waybackbranch`
