### ISSUE TITLE
desi target mask's unexpected behaviour

### ISSUE THREAD

**Issue by shadaba** [desihub/desitarget#299]
I have been trying to use selec_mock on the mock targets for dark time survey. It seems the desimask to select different dark time target have common objects between ELG and QSO.

Is it correct to expect no object should qualify both QSO and ELG flag in the mtl file? if yes then that is not the case!

Here is an example code producing the issue if used on NERSC.

```python
import numpy as np
from astropy.io import fits as astrofits
from desitarget.targetmask import desi_mask

#The example mtlfile produced using select mock and join target codes
mtlfile='/global/project/projectdirs/desi/users/shadaba/Buzzard/FiberAssign/quicksurvey_example/targets/no_spectra/dark/mtl.fits'

#Compare common object between different target class.
with astrofits.open(mtlfile) as ftmp:
    indsel_ELG=np.where((ftmp[1].data['DESI_TARGET'] & desi_mask.ELG) !=0)[0]
    indsel_LRG=np.where((ftmp[1].data['DESI_TARGET'] & desi_mask.LRG) !=0)[0]
    indsel_QSO=np.where((ftmp[1].data['DESI_TARGET'] & desi_mask.QSO) !=0)[0]

    #intesection of the two target class    
    iEL=np.intersect1d(indsel_ELG,indsel_LRG)
    iLQ=np.intersect1d(indsel_QSO,indsel_LRG)
    iEQ=np.intersect1d(indsel_QSO,indsel_ELG)

   #print results
    print('common objects between ELG and LRG:',iEL.size, iEL)
    print('common objects between LRG and QSO:',iLQ.size, iLQ)
    print('common objects between ELG and QSO:',iEQ.size, iEQ)
```

This produces following output:

common objects between ELG and LRG: 0 []
common objects between LRG and QSO: 0 []
common objects between ELG and QSO: 255451 [ 210343  210344  210345 ..., 1549721 1549722 1549727]

**Comment by sbailey** [comment]
Hi @shadaba .  There definitely is overlap between the ELG and QSO selections, which is part of the motivation for having `DESI_TARGET` as a bitmask that can accommodate that possibility (as well as other overlaps such as standard stars also being MWS targets).

For survey operations, targets with multiple assignments get treated as their highest priority option.  That needs to be accounted for when doing randoms / masks for a correlation function analysis since those ELG/QSO targets got higher priority for observation than typical ELGs.

**Comment by shadaba** [comment]
Hi Stephen,

Thanks for your reply.
But for a mock how does this overlap gets decided? by matching position in the sky?
I mean for the case of mock where I am providing three different files for three classes LRG, ELG, QSO then does select mock assign multiple class to objects within some distance in RA, DEC ? All these questions are coming from an effort to map the objects in MTL file to the object in the original source file and I have tried several methods which I can share with codes depending on the response but none of them works for now. 

I am trying to learn more about how things area propagated and really appreciate your help.

Thanks,
Shadab

**Comment by forero** [comment]
@shadaba You can still make the match from MTL to the source file. If the ELG found in the MTL is not in the ELG source file and it also has the QSO then you can check in the QSO source file.

**Comment by shadaba** [comment]
@forero You mean using RA, DEC match? or using some TARGETID--> MOCKID approach.

I have tried to select everything with either QSO or ELG and matched RA,DEC with object matching radius 1e-6 allowing for precision loss and found out of 22 million objects,~ 5 million in ELG a 16 million in QSO assuming no overlap between the two matches I found about ~500K objects in neither catalogue. What might be a potential reason for those objects in neither ELG or QSO input catalogue but still MTL have them classified either with QSO or ELG.

Here is how i select either QSO of ELG and match them two both catalogs for RA,DEC.
```python
indsel=np.where((mtl_table['DESI_TARGET'] & desi_mask.ELG) !=0)[0]
indsel_2=np.where((mtl_table['DESI_TARGET'] & desi_mask.QSO) !=0)[0]
indsel_12=np.unique(np.concatenate([indsel,indsel_2]))
indsel=np.sort(indsel_12)
```

**Comment by forero** [comment]
@shadaba I mean using TARGETID-->MOCKID

**Comment by moustakas** [comment]
@shadaba, is the issue you've raised here still an issue?  Thanks

**Comment by shadaba** [comment]
@moustakas Thanks for getting back to this issue. The main issue was TARGETID -->MOCKID  was not working as expected. Several people have told me that this got fixed in the later version but I haven't looked at the new version myself. So, probably this is already solved. I can try to have a quick look at it next week if I manage to use the latest version of the code.

**Comment by shadaba** [comment]
It seems TARGETID--> MOCKID is not yet working.
I am trying to read TARGETID from mtl file and get the object in input mock catalog.

Here are the steps to get the mtl.fits first using select_mock:
source /project/projectdirs/desi/software/desi_environment.sh 19.2
cd /global/project/projectdirs/desi/users/shadaba/SV1PFA/Buzzard/FAv1
select_mock_targets --no-spectra -c input.yaml  --nside 8 --seed 10 --tiles 1_percent_20_pass.fits
#To join the mock target
join_mock_targets --mockdir .

Now I want to read TARGETID of object in BGS mocks:
#example showing TARGETID--> MockID doesn't work
from desitarget.targets import decode_targetid
from astropy.io import fits as astrofits
import fitsio as F
#This is the mock used in input.yaml for BGS
source_file='/global/project/projectdirs/desi/users/shadaba/Buzzard/buzzard_BGS.fits'

#mtlfile
zcat_dir='/global/project/projectdirs/desi/users/shadaba/SV1PFA/Buzzard/FAv1/'
mtlfile=zcat_dir+'mtl.fits'

#read the mtlfile and select BGS objects
mtl_hdu= astrofits.open(mtlfile)
#get the mtl data handle
mtl_table= mtl_hdu[1].data

`#select galaxy of given target class
indsel=np.where(mtl_table['BGS_TARGET'] !=0)[0] #This has two cases BGS_FAINT and BGS_BRIGHT

#Now decode the objectid from target id
truth_objid, brickid, release, mock, sky= decode_targetid(mtl_hdu[1].data['TARGETID'][indsel])
#Assuming the values in truth_objid is the index of object in the input mock catalogue

#compare first 5 value of objects in mtl and the mock 
with F.FITS(source_file,'r') as ftmp:
    for ii in range(0,5):
        print('mtl index %d: (RA,DEC)'%ii, mtl_table['ra'][indsel[ii]],mtl_table['dec'][indsel[ii]])
        print('mock id %d  : (RA,DEC)'%truth_objid[ii],ftmp[1]['RA'][truth_objid[ii]][0],ftmp[1]['DEC'][truth_objid[ii]][0])`


and the output is as follows:
mtl index 0: (RA,DEC) 241.83189392089844 14.597805976867676
mock id 0  : (RA,DEC) 44.3956487453353 4.991223487692707
mtl index 1: (RA,DEC) 241.8698272705078 15.0051851272583
mock id 1  : (RA,DEC) 45.89714470799076 1.875130139360678
mtl index 2: (RA,DEC) 241.6254119873047 14.830843925476074
mock id 2  : (RA,DEC) 42.655871295526545 5.38564605601313
mtl index 3: (RA,DEC) 241.7029571533203 14.943293571472168
mock id 3  : (RA,DEC) 45.04913827460498 4.0473453168751945
mtl index 4: (RA,DEC) 241.924072265625 14.906516075134277
mock id 4  : (RA,DEC) 46.316758329388335 6.030604480018511


The fact that RA,DEC of object in the mtl doesn't match with the object in the source file mean TARGETID--> mockid is working as expected?

**Comment by moustakas** [comment]
Thanks for the bug report @shadaba, I'm looking into this now (and #540, which *may* be related).

**Comment by shadaba** [comment]
The mapping works now at least for the BGS with the latest version of software.
This is kindly explained in this notebook by John:
https://github.com/desihub/desitarget/blob/1446b834de3c3bc6193cfedd0ed0a7b21a262fb9/doc/nb/mock-targets-to-mocks.ipynb
