### ISSUE TITLE
desisim.templates.LRG() is broken

### ISSUE THREAD

**Issue by londumas** [desihub/desitarget#301]
`desisim.templates.LRG()` uses `isLRG_colors` that apparently doesn't exist anymore

```
Traceback (most recent call last):
  File "<my_module_name>.py", line 53, in <module>
    tflux, twave, tmeta = LRG().make_templates(nlrg, zrange=(0.0, 0.2), restframe=True, nocolorcuts=True,seed=opts.seed+nelg)
  File "<path_to_there>/Programs/desi/code/desisim/py/desisim/templates.py", line 960, in __init__
    from desitarget.cuts import isLRG_colors as colorcuts_function
ImportError: cannot import name isLRG_colors
```

**Comment by geordie666** [comment]
My fault...I tried to maintain backwards-compatibility when I split the target selections into north v. south functions, but forgot to add an `isLRG_colors()` wrapper. The quick fix is to change the call to `isLRG_colors()` to a call to `isLRG_colors_south()` with the same inputs. I'll try and restore backwards-compatibility later today, though.

**Comment by sbailey** [comment]
Please add a unit test that would have caught this.  I'm surprised that we didn't trip on this with the 18.3 testing.

**Comment by moustakas** [comment]
I should have caught when this broke @londumas, sorry.  Thanks to @geordie666 for fixing this in #302.
