### ISSUE TITLE
ensure consistency in the QSO and Lyman-alpha mock catalog redshift distributions

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#308]
The Gaussian random field QSO mock (`v0.0.7_2LPT/QSO.fits`) extends from `z=0-1.7` (see, e.g., [here](https://github.com/desihub/desitarget/blob/master/doc/nb/mock-qa.ipynb)).  

However, the various Lyman-alpha mocks have different, inconsistent starting redshifts, e.g., `z=2.0` for the `v2.0.2 CoLoRe/UCL` mocks and `z=1.3` for the `v1.1.1 Saclay` mocks.

We need to ensure that the mocks for the two target classes are consistent both on disk and in code so that we don't under-count / double-count the target densities.

**Comment by moustakas** [comment]
@andreufont @julienguy Can you point me to a reasonably current, default Lyman-alpha mock that doesn't have the "feature" documented in this issue?

**Comment by moustakas** [comment]
Sounds good.  Based on the london/v2.0 mocks I went ahead and set `zmin_lya>=1.8` and `zmax_qso<1.8` to ensure no overlap in n(z) but these are now both parameters in the `select_mock_targets` configuration file (although it'd be nice if the split could be discoverable from the data themselves -- maybe a header card?).

**Comment by andreufont** [comment]
Yes, we will add a header card to the transmission files for the next version.

**Comment by moustakas** [comment]
This issue has to be handled in the `select_mock_targets` configuration file using the `zmin_lya` and `zmax_qso` parameters, which were implemented in #368.
