### ISSUE TITLE
HPXPIXEL all 0 in select_mock_targets output

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#314]
The HPXPIXEL column in select_mock_targets output is incorrectly = 0 for all targets.  This was true for the 18.3 release (desitarget 0.20.1) so it isn't a new bug.  This gets propagated all the way to the output redshift catalog, so it is important to get it fixed for the next tag.

**Comment by moustakas** [comment]
I'm fixing this now but note that `BRICKID` also contains the healpixel number.

**Comment by moustakas** [comment]
Fixed in #318
