### ISSUE TITLE
Additional columns for GFA targets

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#319]
Additional columns to add to `select_gfa` output:

  * [x] FLUX_G, FLUX_Z (float32, nanomaggies) [FLUX_R is already there]
  * [x] TYPE (S4, morphological type)
  * [x] BRICKID (int32)
  * [x] BRICK_OBJID (int32) [OBJID in sweep file]

Placeholders for proper motions from Gaia, though these aren't yet in the sweeps:

  * [x] PMRA, PMDEC (float32) default 0.0 (proper motions from Gaia)
  * [x] PMRA_IVAR, PMDEC_IVAR (float32) default 1.0 (inverse variances of PM*)
  * [x] PARALLAX (float32) default 0.0
  * [x] PARALLAX_IVAR (float32) default 1.0
  * [x] Header keyword (not column) REFEPOCH = 2015.5 // Gaia Proper Motion Reference Epoch

Placeholder boolean flags, for now set True if TYPE='PSF' though we may add additional cuts later for isolation, color, etc.

  * [ ] GUIDE_OK  // ok to use for guiding
  * [ ] SEEING_OK  // ok to use for seeing measurements
  * [ ] FOCUS_OK  // ok to use for focusing

**Comment by geordie666** [comment]
@sbailey: At some point I'm going to update the GFAs code so that it can either match to Gaia, or just directly take columns from the sweeps. Do we still need the `PARALLAX` columns? Should I add the `GUIDE_OK`, `SEEING_OK`, `FOCUS_OK` columns, or does that happend downstream?

**Comment by sbailey** [comment]
Implemented by PR #342
