### ISSUE TITLE
GMM magnitude assignment and target selection for read_gaussianfield

### ISSUE THREAD

**Issue by shadaba** [desihub/desitarget#320]
In read_gaussianfield function for say ELG target only RA, DEC, Z is read from file and magnitude is assigned using Gaussian mixture model. Then it is followed by target selection and downsampling if needed.

This works fine if the mocks have much more objects to start with than the expected target density say 2400/deg^2 for ELG. But, if the input mock has just the right number of the object then the target selection applied in this way already reduce the number density to lower than expected values which results in fewer than expected objects in the MTL file.

Is there any easy way to make the GMM assign magnitude, colour etc. such that all objects in the input can be selected after target selection. 

We have EZmock which have just the right target density but due to this issue, our fibres assigned version have fewer than expected object. Any idea/comment will be highly appreciated.

It might be hard to produce very high number density for mocks so this might be generally a useful feature for many of the planned analysis.

**Comment by moustakas** [comment]
@shadaba Is this still an important feature you'd like to have?  I have at least one idea.

**Comment by moustakas** [comment]
@shadaba If this is still a feature you would like to have let's discuss on-list or please create an issue specifically for adding support for the `EZmock` mocks, which I am happy to do.
