### ISSUE TITLE
select_mock_targets much slower with desiconda 20180518-1.2.5-spec than 20180130-1.2.4-spec

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#323]
Filing a ticket so that I don't forget it even though I don't have it turned into a simple example yet.

Running the following command from desitarget master using two different versions of desiconda has very different runtimes (newer is much slower for some target classes but not all):
```
srun -A desi -N 15 -n 30 -c 16 -C haswell -t 00:30:00 --qos interactive mpi_select_mock_targets --output_dir /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets --config ./select-mock-targets.yaml --seed 1 --nproc 16 --nside 64 --tiles /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/test-tiles.fits
```
e.g. for pixel 5262:
```
[cori06 52] grep "Total time" 5262-desiconda-20180130-1.2.4-spec-master/build-64-5262.log
INFO:build.py:491:get_spectra: Total time for BGSs = 1.311 minutes (1499.375 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for ELGs = 2.747 minutes (3142.169 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for FAINTSTARs = 0.075 minutes (86.194 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for LRGs = 0.361 minutes (413.301 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for LYAs = 0.190 minutes (217.634 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for MWS_MAINs = 0.219 minutes (251.029 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for MWS_NEARBYs = 0.055 minutes (62.564 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for QSOs = 0.125 minutes (142.787 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for SKYs = 0.052 minutes (59.569 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for WDs = 0.057 minutes (65.184 cpu minutes/deg2).
[cori06 52] grep "Total time" 5262-desiconda-20180518-1.2.5-spec-master/build-64-5262.log
INFO:build.py:491:get_spectra: Total time for BGSs = 5.048 minutes (5774.461 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for ELGs = 9.461 minutes (10821.526 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for FAINTSTARs = 0.074 minutes (84.123 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for LRGs = 0.330 minutes (377.861 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for LYAs = 0.168 minutes (192.329 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for MWS_MAINs = 0.241 minutes (275.605 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for MWS_NEARBYs = 0.048 minutes (55.184 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for QSOs = 0.121 minutes (138.161 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for SKYs = 0.048 minutes (55.322 cpu minutes/deg2).
INFO:build.py:491:get_spectra: Total time for WDs = 0.054 minutes (61.522 cpu minutes/deg2).
```
Some target classes are about the same, but BGS and ELG in particular are considerably slower.  This is using the same version of desitarget; the difference is in the underlying python libraries or linkage with MKL or something.

**Comment by sbailey** [comment]
John notes that BGS and LRG are the two that are slower, and are also the only two that have velocity dispersions applied.  Profiling that step would be a good place to check first.

**Comment by moustakas** [comment]
Could test this idea by setting `novdisp=True` [here](https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/mockmaker.py#L2792-L2793) for BGS targets in `mock.mockmaker.BGSMaker` and [here](https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/mockmaker.py#L2574-L2575) for ELGs in `mock.mockmaker.ELGMaker`.

Any speed improvement of the velocity dispersion broadening itself (which happens [here](https://github.com/desihub/desisim/blob/master/py/desisim/templates.py#L352-L368)) in `desisim.templates` for all galaxy types would be welcome.

The velocity broadening bottleneck is a long-standing open issue:  https://github.com/desihub/desisim/issues/58.

The ELG and BGS targets are also the only ones that have emission lines...
