### ISSUE TITLE
add Gaia columns to MWS/Galaxia mocks?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#326]
Related to #256 and #324, it would be helpful if the stellar mocks included the same Gaia columns that are now being included in the imaging / target catalogs, so MWS targets can be selected in the same way.

Is this possible and, if not, how would the MWS Working Group like mock targets to be selected?  See [here](https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/mockmaker.py#L3212-L3235) for the current placeholder selection criteria.

**Comment by apcooper** [comment]
I've also been thinking about this. The current situation is that there is a `gaia` file for each v0.0.5 MWS mock file that has some extra columns for Gaia PM, parallax, G etc (both the 'true' value and a value drawn from the error distribution of each star).

Not really optimal to have these in separate files with different column names to tractor etc. I was already thinking of more tractor-like organisation for the next round of mocks.

**Comment by moustakas** [comment]
Tracking this issue now in #352.
