### ISSUE TITLE
missing galaxia files

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#335]
I am running the latest `mpi_select_mock_targets` and I am getting tons of errors for missing galaxia files. The messages look like this. 

`INFO:mpi_select_mock_targets:157:<module>: Logging pixels [44297 44298 44299 44300 44301 44302 44303 44304] to /global/cscratch1/sd/forero/quicksurvey2018a/targets/442/44297/build-64-44297.log
INFO:parallel.py:365:stdouterr_redirected: Begin log redirection to /global/cscratch1/sd/forero/quicksurvey2018a/targets/442/44297/build-64-44297.log at Fri Jul 27 11:48:33 2018
INFO:parallel.py:412:stdouterr_redirected: End log redirection to /global/cscratch1/sd/forero/quicksurvey2018a/targets/380/38005/build-64-38005.log at Fri Jul 27 11:48:34 2018
ERROR:mpi_select_mock_targets:176:<module>: Pixels [38005 38006 38007 38008 38009 38010 38011 38012] failed after 0.5 minutes
ERROR:mpi_select_mock_targets:179:<module>: Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.0/lib/python3.6/site-packages/desitarget-0.21.0-py3.6.egg/EGG-INFO/scripts/mpi_select_mock_targets", line 170, in <module>
    healpixels=rankpix[i:i+n], no_spectra=args.no_spectra)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.0/lib/python3.6/site-packages/desitarget-0.21.0-py3.6.egg/desitarget/mock/build.py", line 606, in targets_truth
    MakeMock=AllMakeMock[ii])
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.0/lib/python3.6/site-packages/desitarget-0.21.0-py3.6.egg/desitarget/mock/build.py", line 174, in read_mock
    dust_dir=dust_dir, mock_density=mock_density)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.0/lib/python3.6/site-packages/desitarget-0.21.0-py3.6.egg/desitarget/mock/mockmaker.py", line 3279, in read
    nside_galaxia=nside_galaxia, magcut=magcut)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.0/lib/python3.6/site-packages/desitarget-0.21.0-py3.6.egg/desitarget/mock/mockmaker.py", line 1027, in readmock
    radec = fitsio.read(galaxiafile, columns=['RA', 'DEC'], upper=True, ext=1)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 87, in read
    with FITS(filename, **keys) as fits:
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 351, in __init__
    raise IOError("File not found: '%s'" % filename)
OSError: File not found: '/project/projectdirs/desi/mocks/mws/galaxia/alpha/v0.0.5/healpix/8/5/593/mock_allsky_galaxia_desi-8-593.fits'
`

Any idea what might be the problem?

Here is the command I am using:

```
time srun -N $NODES -n $NODES -c 32  mpi_select_mock_targets     --seed 1 --nproc 32 --nside 64 --npix 8 --no-spectra     --tiles $DESIMODEL/data/footprint/desi-tiles.fits     --config $BASEDIR/targets/select-mock-targets.yaml     --output_dir $BASEDIR/targets
```

and the input file

```
# mock target configuration file
dust_dir: '{DUST_DIR}/maps'
sources:
    BGS: {
        target_name: BGS,
        mockfile: '{DESI_ROOT}/mocks/bgs/MXXL/desi_footprint/v0.0.4/BGS.hdf5',
        format: durham_mxxl_hdf5,
        magcut: 20.2,
    }
    ELG: {
        target_name: ELG,
        mockfile: '{DESI_ROOT}/mocks/GaussianRandomField/v0.0.7_2LPT/ELG.fits',
        format: gaussianfield,
        density: 2155,
    }
    LRG: {
        target_name: LRG,
        mockfile: '{DESI_ROOT}/mocks/GaussianRandomField/v0.0.7_2LPT/LRG.fits',
        format: gaussianfield,
        density: 480,
    }
    QSO: {
        target_name: QSO,
        mockfile: '{DESI_ROOT}/mocks/GaussianRandomField/v0.0.7_2LPT/QSO.fits',
        format: gaussianfield,
        density: 120,
    }
    LYA: {
        target_name: LYA,
        mockfile: '{DESI_ROOT}/mocks/lya_forest/v2.0.2/master.fits',
        format: CoLoRe,
        nside_lya: 16,
        density: 50,
    }
    MWS_MAIN: {
        target_name: MWS_MAIN,
        mockfile: '{DESI_ROOT}/mocks/mws/galaxia/alpha/v0.0.5/healpix',
        nside_galaxia: 8,
        format: galaxia,
    }
    MWS_NEARBY: {
        target_name: MWS_NEARBY,
        mockfile: '{DESI_ROOT}/mocks/mws/100pc/v0.0.3/mock_100pc.fits',
        format: mws_100pc,
    }
    WD: {
        target_name: WD,
        mockfile: '{DESI_ROOT}/mocks/mws/wd/v0.0.2/mock_wd.fits',
        format: mws_wd,
    }
    FAINTSTAR: {
        target_name: FAINTSTAR,
        mockfile: '{DESI_ROOT}/mocks/mws/galaxia/alpha/0.0.5_superfaint/healpix',
        nside_galaxia: 8,
        format: galaxia,
        magcut: 23.5,
    }
    SKY: {
        target_name: SKY,
        mockfile: '{DESI_ROOT}/mocks/uniformsky/0.1/uniformsky-2048-0.1.fits',
        format: uniformsky,
        density: 1400,
    }

```

**Comment by forero** [comment]
Things seem to be working now without the option `--tiles $DESIMODEL/data/footprint/desi-tiles.fits`

**Comment by moustakas** [comment]
@forero did you track down the underlying issue?  You should definitely be able to run this script with an input `tiles` file.  Perhaps your `desimodel` SVN repository is out of date...?

**Comment by forero** [comment]
I was running on cori, so that repo should be up to date.
I didn't try to track it down. I guess the problem was some kind of boundary issue.

**Comment by apcooper** [comment]
I guess it's pretty likely there'll be boundary issues if the tiles have been changed to the new set from Eddie Schlafly. This should go on my list for the next iteration of the galaxia mocks. Would be interested to know how urgent that is.

**Comment by moustakas** [comment]
The `desi-tiles.fits` file in `$DESIMODEL/data/footprint` hasn't been updated since 2016...
