### ISSUE TITLE
update the mock catalog code to the DR7 data model

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#339]
The changes / improvements in https://github.com/desihub/desitarget/pull/338 very likely broke `select_mock_targets` (and its MPI variant), and also introduced a dependence on Gaia. 

This issue is a reminder to review and implement the necessary code changes to `mock.mockmaker` and `mock.build.targets_truth`.

**Comment by geordie666** [comment]
Note that you can call the individual target classes that do *not* have a dependence on Gaia by passing `tcnames` (or continue to call their functions directly). Also, `isSTD_colors` should work without Gaia, still.

But, yes, those target classes that use Gaia extensively as part of their classification algorithm (`MWS`) will need Gaia columns.

**Comment by moustakas** [comment]
Done in #368.
