### ISSUE TITLE
need the ability to blacklist targets after observation(s)

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#344]
From the discussion on a recent Data telecon (see [desi-data 3720](https://desi.lbl.gov/trac/tracmailman/browser/private/desi-data/2018-August/003723.html) for details):

> Need ability to blacklist targets, e.g.
> - by hand, to not reuse problematic standards or sky positions in future passes;
> - automatic, e.g. QSOs that were classified as stars (right now this is implicitely done by changing PRIORITY and NOBS_MORE, but not explicitely via a flag).

**Comment by geordie666** [comment]
Note that if we fully implemented #635, it would be trivial to blacklist targets by hand, by setting `NUMOBS_MORE` to zero for the appropriate entry in the ledger. I'll leave this open for now, though, until we've decided to what degree we will implement #635 downstream.

**Comment by geordie666** [comment]
This will be addressed using the ledgers as part of #759.
