### ISSUE TITLE
assigning SKY and BAD_SKY targeting bits

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#348]
* In the current version of `desitarget.skyfibers`, sky targets which have imaging data missing in *any* band are assigned the bit `BAD_SKY`, although [this notebook](https://github.com/desihub/desitarget/blob/master/doc/nb/skies-dr7.1.ipynb) shows that most of these are probably fine.  Consequently, consider instead requiring `APFLUX_IVAR_[G,R,Z] == 0` in *all* bands for "bad" skies.  (May be worth also checking to make sure the cut on ivar also captures targets whose *flux* is identically zero -- it should!)

* Related: in the current version of the code, sky targets which have zero flux *and* zero inverse variance still have the `SKY` or `BAD_SKY` targeting bits set (about 4% of the dr7.1 skies).  These should really be excluded from the sky catalog, since presumably we're missing the information we need to assess these as viable sky targets (whether `SKY` or `BAD_SKY`).

**Comment by geordie666** [comment]
A couple of notes:

- Talking with Schlegel offline, a better criterion might be `APFLUX_IVAR_[G,R] == 0` in *both* of `g` and `r` (i.e. place less trust in `z`). Agreed about explicitly checking *flux* as well as *ivar*.

- My understanding of `BAD_SKY` is that it is meant to indicate a location where we can put a fiber, but which the spectroscopic pipeline should not (necessarily) trust for sky subtraction. I think the 4% of the dr7.1 skies that you're talking about should therefore *not* be excluded from the sky catalog and *should* be labeled `BAD_SKY`. I think these are the very definition of locations that we need but that shouldn't (necessarily) be trusted for sky subtraction. If we discard these sorts of locations from the sky catalog, there will be places where we can't place a fiber. I will match these to Gaia to guard against having substantial flux at these "gap" locations.

**Comment by geordie666** [comment]
Addressed in https://github.com/desihub/desitarget/pull/408.
