### ISSUE TITLE
color cut for MWS_STAR simulated data

### ISSUE THREAD

**Issue by crockosi** [desihub/desitarget#35]
Random selection from the stellar templates gives far too many stars with g-r<0 for an old stellar population, which is mostly what we expect for the MWS. A function like isFSTD_colors to cut objects with g-r < 0 would be a quick way to make this better.  There would be a corresponding change to the definition of MWS_STAR in desisim's templates.py

**Comment by moustakas** [comment]
I think this was incorporated long ago -- closing.
