### ISSUE TITLE
what unit should we use for photometric fluxes in units of nanomaggies?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#357]
This question came up in https://github.com/desihub/desisim/pull/409 for the template metadata table, although it's also related to #356, #339, and https://github.com/desihub/desispec/issues/665.

According to astropy/FITS, `nanomaggies` are not an acceptable unit.  Thoughts on what to use, or should we ignore the warnings?

```
import astropy

astropy.units.Unit('nanomaggies', format='fits')
ValueError: 'nanomaggies' did not parse as fits unit: At col 0, Unit 'nanomaggies' not supported by the FITS standard. 

astropy.units.Unit('3.631*10^-6 Jy', format='fits')
ValueError: '3.631*10^-6 Jy' did not parse as fits unit: Numeric factor not supported by FITS
```

**Comment by sbailey** [comment]
I think we should prioritize pragmatism over formality and use "nanomaggies" even if it isn't an officially allowed unit.  Even if we found a way to get astropy to accept "3.631*10^-6 Jy", that is less clear than "nanomaggies" for actually understanding the units.

Ideally we would also wrap astropy I/O routines with something that would hide that warning.

**Comment by moustakas** [comment]
Agreed, thanks.
