### ISSUE TITLE
Add columns to target output files.

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#369]
This is transcribed from https://github.com/desihub/desitarget/issues/209, which was fixed in the mocks but not yet in the real data.

A few items (for the real target catalog):
* `BRICKID`: let's use the real ra,dec -> brickid mapping rather than the healpix number, especially since we also have a HPXPIXEL column.  Create a `b = desiutil.brick.Bricks(bricksize=0.25)` object, then call `b.brickid(ra,dec)`.
* `TYPE` -> `MORPHTYPE`.  Although we generally don't want to rename columns arbitrarily, there are too many other "types" downstream (spectype, postionertype, objtype, ...) so by the time this gets to the ICS it needs to be "MORPHTYPE".  Let's do this change here at target selection (I would prefer it to even happen upstream in the sweeps or tractor, but that may be a can of worms).
* Let's drop the unused W3 and W4 fields (FLUX_, FLUX_IVAR_, MW_TRANSMISSION_) unless there is a strong science case for keeping them (they aren't used by targeting or the spectro pipeline).

**Comment by moustakas** [comment]
> Let's drop the unused W3 and W4 fields (FLUX_, FLUX_IVAR_, MW_TRANSMISSION_) unless there is a strong science case for keeping them (they aren't used by targeting or the spectro pipeline).

I actually think we should get the input of the science working groups on this one.  Of course one could always go from redshift catalogs back to the sweeps to get these fluxes, but that's pretty inconvenient given how the sweeps are organized.  (Maybe we really should post-process them into healpixels...)  Anyway, I can send that email if you want @geordie666, or we could just move on and drop W3,W4.

**Comment by geordie666** [comment]
@moustakas: If you could shoot a quick email to the mailing lists just to check W3/W4 aren't critical, that'd be great.

I say we drop them unless people really need them. Potentially, anyone can ask for any columns in the sweeps, or the Tractor files. I think it would make more sense to have code to match back on `TARGETID` and pick up extra information, rather than carry around all of the columns.

On the post-processing into HEALPixels: One option would be to just write an indexing file that noted which sweeps files needed to be touched to retrieve a HEALPixel. It's easy to traverse the nested tree to different HEALPixel resolutions.

**Comment by forero** [comment]
I am working on adding some columns in `fiberassign` outputs. It seems that the following should come from files written by `select_targets`. 

* [ ] LAMBDA_REF 
* [ ] SECONDARY_TARGET	
* [ ] COMM_TARGET 
* [ ] SV1_DESI_TARGET	 
* [ ] SV1_BGS_TARGET 
* [ ] SV1_MWS_TARGET 


Am I right? If yes, then where is the most up-to-date DR7 `targets` file including those columns?

**Comment by geordie666** [comment]
Only files for commissioning and for SV will include the `COMM_TARGET` column (which is actually called `CMX_TARGET`) and `SV1_` columns. Those columns won't appear in the DR7 files until/unless the commissioning and SV versions of the code are run.

I forgot about the `FIBERFLUX_` and `FIBERTOTFLUX_` columns. I'll add those. Thanks!

I'm not sure where `LAMBDA_REF` would come from. @sbailey?

**Comment by geordie666** [comment]
Most of this was resolved in https://github.com/desihub/desitarget/pull/372, except for the issue of `LAMBDA_REF`, which I'm uncertain about.

**Comment by forero** [comment]
Thanks @geordie666. What is your timescale to produce a new file with `FIBERFLUX_` and `FIBERTOFLUX_` columns?

**Comment by geordie666** [comment]
I'll do it now! It should only take an hour or so.

Note that I'm also pushing on SV this week, so I should have my first
version of the files with the `SV1_` columns early next week.

**Comment by sbailey** [comment]
@forero fiberassign should add `LAMBDA_REF` with a default value of 5400.0 for now.  It is the reference wavelength at which a target should be centered on the fibers on the focal plane.  In principle it could be optimized at a different wavelength, or even different wavelengths for different target classes, though it is unclear whether platemaker will ever support that.  We've put it in the datamodel as a placeholder for that ability.

For the other columns please add some code like
```python
for colname in ['FIBERFLUX_G', 'FIBERFLUX_R', ...]:
    if colname in targets.dtype.names:
        output_columns.append(colname)

outtarget = targets[output_columns]
```
i.e. when they are there in the inputs, propagate them, but if they aren't ok.  I may come to regret this request, but for now it allows you to make progress on fiberassign column propagation without it being closely coupled to desitarget updates and we can later upgrade them to required columns that will crash fiberassign if they are missing.

**Comment by sbailey** [comment]
Clarity update: both of my comment (LAMBDA_REF and "for the the other columns...") were for @forero in fiberassign, even though I'm replying to an issue in desitarget here...

**Comment by geordie666** [comment]
@forero: There's a new file with those columns at:

`/project/projectdirs/desi/target/catalogs/dr7.1/targets-dr7.1-PR372.fits`

**Comment by forero** [comment]
@geordie666 thanks!
