### ISSUE TITLE
How to separate low-z from high-z quasars in survey simulations?

### ISSUE THREAD

**Issue by andreufont** [desihub/desitarget#376]
When running full survey simulations, we need to decide at what redshift do we switch from using low-z quasars from boxes that have both ELG and quasars, and we start using high-z quasars from Lyman alpha mocks. 

From the point of view of Lyman alpha, we would like this transition to be around z=1.8 (or 1.85), since quasars with z > 1.8 are still useful to measure the cross-correaltion with the Lyman alpha forest at z=1.95 where our spectrograph dies.

We can add to the "transmission files" (those used to generate the high-z quasar spectra) a header indicating what is the value of lower redshift used in the run.  

There is a subtlety here. Should this redshift cut be understood as a cut in distance from Earth? Or should it also include redshift space distortions? We currently simulate quasars that are farther away than the comoving distance corresponding to z=1.8, but because of RSD some of the quasars end up having a redshift in the range 1.75 < z < 1.8 or so.
It looks like a subtlety, but I know that @londumas was worried about getting this wrong and the effect that could have in the auto-correlation of the “Lyman alpha” quasars.

As @moustakas mentioned, we could make the cut with either z_rsd or z_norsd, but we should document this either way.

**Comment by moustakas** [comment]
This issue was handled in #368 via a new parameter in the `select_mock_targets` configuration file (see that PR for more details).  And based on discussion on Slack the redshift cut is applied to the QSO/Lya redshifts *including/after* RSD.
