### ISSUE TITLE
standard-star target density in the mocks should be tunable

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#377]
In the `select_mock_targets` configuration file we really need a parameter which sets the (desired) target density of standard stars.  Currently the downstream code requires roughly 30 standards/deg2, so we should make sure this gets achieved.

We've been bitten several times by this issue (i.e., ending up with too few standards).

**Comment by sbailey** [comment]
+1.  The current (as of PR #378) density of 1000/deg2 is way too high to be realistic.

**Comment by moustakas** [comment]
I looked into implementing a new parameter in the configuration file to tune the number of standard stars, but I am confident that the excess was due to the bug which was fixed in #383, so I'm closing this issue.
