### ISSUE TITLE
Give WDs higher priority than BGS galaxies 

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#399]
At the Tucson meeting, BGS and MWS agreed WDs in the science sample (not just WD standards) should be prioritised above BGS (e.g. at priority 3000). This doesn't seem to be implemented yet:

https://github.com/desihub/desitarget/blob/9f7a2571e073ae9e1b7b8eaeae02294247419a7f/py/desitarget/data/targetmask.yaml#L210-L213

**Comment by geordie666** [comment]
Good catch...I'll add this in my next iteration of the code (early next week).

**Comment by geordie666** [comment]
Fixed in https://github.com/desihub/desitarget/pull/408.
