### ISSUE TITLE
Targets that are both LRG+BGS have NUMOBS_MORE always set to 1 even in dark time

### ISSUE THREAD

**Issue by akrolewski** [desihub/desitarget#400]
Hi all,

It appears that all BGS targets have NUMOBS_MORE reset to 1 in calc_numobs().  However, some BGS targets are overlaps with LRGs.  Therefore, these targets will continue to be observed in dark time (e.g. when running quicksurvey) and therefore you wind up with a tail of LRGs that are observed > 2 times in dark time (because they are BGS overlaps).  This doesn't make sense; either these are LRGs, in which case they should be observed once or twice in dark time, or they are BGS, in which case they should be observed in bright time.  The program information Dark, Gray, Bright should be passed to calc_numobs() and calc_priority() to take these cases into account.  More generally, it doesn't appear as if there is a way to properly treat overlapping targets (such as LRG+BGS).  After the first observation, one should know whether they are truly LRG or BGS and then the target can be observed appropriately.

I'm wondering what the best way is to solve this problem (or set of problems).

**Comment by geordie666** [comment]
There is some additional discussion of this in #429. It is possible that we will deprecate this behavior (BGS targets always have `NUMOBS_MORE` reset to 1) completely. Otherwise, we'll have to think carefully about how to achieve the desired behavior in fiberassign.

**Comment by geordie666** [comment]
Addressed by having MTL take an observing condition/layer in #531.
