### ISSUE TITLE
add contaminants to select_mock_targets

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#401]
Including contaminants in `bin/select_mock_targets` is firmly on the critical path, not only to help train Lya QSO identification algorithms but also to help with various fiber-assignment investigations (e.g., wide vs deep).

[Note that I'm creating this new issue in favor of #285, which I intend to close, to more clearly state the problem and the path forward.]

We expect each target class to be "contaminated" with other types of objects that live in that part of color-magnitude space.  The spatial distribution of extragalactic contaminants should be basically random, whereas the level of stellar contamination should depend on Galactic latitude.

Based on various estimates (which may not be the most accurate of up to date!), I roughly expect:

**BGS** - Here we expect just stellar contamination, of order a few percent, which will vary systematically with Galactic latitude.

**ELGs** - Stellar contamination should be of order 5% (see, e.g., [elg-properties-dr7.1.ipynb](https://github.com/desihub/desitarget/blob/master/doc/nb/elg-properties-dr7.1.ipynb)), while contamination from lower-redshift interlopers should be of order 10%-15%.

**LRGs** - Principle contaminants should be M stars (conservative maximum of 5%), while contamination from extragalactic targets should be negligible.

**QSOs** - Contamination from intermediate-redshift galaxies should (very roughly) be about 10%, while stellar contamination should be approximately 25%.  (Please see [SimulateQuasarTargets](https://desi.lbl.gov/trac/wiki/LymanAlphaWG/SimulateQuasarTargets) for a detailed discussion of QSO contaminants.)

To do this right we really want the apparent magnitude distribution, redshift distribution, and space-density (and morphologies!) of the extragalactic contaminants, as well as dedicated templates.  However, the goal is to implement something simple and then improve from there.

For the extragalactic contaminants I intend to use the Buzzard mock (see #249), which, like the BGS/MXXL mock, is flux-limited, but independent of the current default BGS mock.

Please post any additional suggestions and thoughts here.

**Comment by akrolewski** [comment]
I notice in the [targeting QA](http://portal.nersc.gov/project/desi/users/adamyers/desitargetQA-dr6.0-0.22.0/) that there there are ELG/QSO overlaps, suggesting that some of the QSO contaminants are ELGs (and vice versa).

Are these overlaps reflective of reality, or are they merely an artifact of the current targeting scheme and are expected to go away by the final release of imaging/targeting?

Also, it looks like the [ELG MMT observations](https://desi.lbl.gov/trac/attachment/wiki/TargetSelectionWG/TSTeleconMinutes/DESITS180705/20180705-Binospec-ELG-Validation-update.pdf) have ELG efficiency ~65%, lower than the 80% you quote here.  But it appears they are using a higher number density (3000 vs fiducial 2400), so maybe that is the cause of the discrepancy?

**Comment by geordie666** [comment]
Experience from eBOSS suggests that quasars and ELGs overlap in WISE+optical color space, so I'd expect there to be reasonable overlaps between the QSO and ELG target classes. The current level (~15-20% of the QSO targets also being ELG targets) is about what I'd expect.

**Comment by moustakas** [comment]
Done in #427.  I will document outstanding issues and missing features in a separate issue.
