### ISSUE TITLE
MWS-MAIN target definition and priority need to be changed

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#410]
@geordie666 , @moustakas ,

We've found an issue with the MWS target definitions. Here's an explanation and a proposal for a short-term fix.

**Issue**: The MWS section of the target selection page describes a category MWS-MAIN with sub-categories MWS-MAIN-BLUE and MWS-MAIN-RED. This has been coded up in `deistarget` as **three** separate target classes (ignoring the north-south permutations). 

With the definitions used now, the MWS-MAIN class includes all the stars that are not included in the other two classes. In practice, these are the stars that fail the astrometry cuts in MWS-MAIN-RED.  *All three classes are given the same priority in `targetmask.yaml`*.

This isn't what we intended -- we really wanted only **two** classes, MAIN-RED and MAIN-BLUE. The group hasn't made a final decision on whether to target the rejects from MAIN-RED. If we target them, they should have lower priority than the stars in MAIN-BLUE and MAIN-RED. In that case the name MWS-MAIN is too confusing for describing these rejects and should be changed.

**Proposal**: *The MWS-MAIN category should be renamed MWS-BROAD and given a priority of 1400 (below MWS-MAIN-RED and MWS-MAIN-BLUE, which are unchanged).*

 This is a short-term fix that should give us sensible results in targeting tests. If possible we may want to do something different in future (e.g. give all the stars in the MWS-MAIN magnitude range equal priority but sample them at different rates in the space of colour, PM and parllax). That is TBD.

I will fix the ambiguous description on the target selection page.

**Comment by apcooper** [comment]
Target selection page has been updated.

**Comment by geordie666** [comment]
Thanks @apcooper. I'm finishing up at a DOE review of DESI, but I'll hopefully get to that relatively simple change in the next week.

Note that it's trivial to just turn off the `MWS-MAIN` bit and never target the broader range, if needed. But I'll rename that class `MWS-BROAD` for now.

**Comment by moustakas** [comment]
@geordie666 #418 looks good; please feel free to close this issue when that PR has been merged.
