### ISSUE TITLE
Consider adding an option to generate fast ELG/LRG templates when running minitest-lya

### ISSUE THREAD

**Issue by andreufont** [desihub/desitarget#411]
We would like to be able to run simulations of full DESI survey for studies of the Lyman alpha forest.

We could use the standard simulations following the minitest notebook, but I was told last week at the meeting that a major part of the CPU time in minitest is spent generating the galaxy templates. Is that true?

If that was true, we could consider adding an option to not simulate galaxy spectra, since from our point of view we only care about the spectra of quasars, sky fibers and calibration stars. 

I first thought that we could just hack the code to set these spectra to have zero flux (or whatever dummy spectrum), but I wonder whether this would cause trouble further down, since these spectra would not be selected by the target selection code. So the question is:
 - what happens in mini-test if the target selection of ELGs and LRGs return zero targets?
 - if this breaks the code, could we add an option to generate spectra for ELG/LRG that pass the target selection code, but that does not dominate the CPU time budget?

**Comment by andreufont** [comment]
Comments from @moustakas:
- select_mock_targets spends only as much time generating spectra as it needs to (i.e., there are no extraneous calculations that could be turned on or off).

>  - what happens in mini-test if the target selection of ELGs and LRGs return zero targets?
>  - if this breaks the code, could we add an option to generate spectra for ELG/LRG that pass the target selection code, but that does not dominate the CPU time budget?

The minitest notebook has no requirements on the number (or existence) of particular target classes, so this is not an issue.

In the Lyman-alpha version of the minitest notebook do you want ELGs and LRGs as contaminants or for another reason?  If for contaminants, I'm working on that part of select_mock_targets and so we should continue the discussion in https://github.com/desihub/desitarget/issues/401 or in whatever new issue you create.

**Comment by andreufont** [comment]
Hi @moustakas, 

Yes, for our minitest-lya we would like to simulate all quasar target spectra, but this is not what this issue is about. This issue is about what to do with the > 80% fibers that will be empty. Can the desisim code handle unassigned fibers? Is it hardcoded anywhere that there are 10 petals with 500 fibers each?

Things will be more extreme when simulating pass 3-4 observations, where we will only use 25% or so of the fibers between lya quasars, sky and stars.

**Comment by moustakas** [comment]
> Yes, for our minitest-lya we would like to simulate all quasar target spectra, but this is not what this issue is about. This issue is about what to do with the > 80% fibers that will be empty. Can the desisim code handle unassigned fibers? Is it hardcoded anywhere that there are 10 petals with 500 fibers each?

Then this question is more about whether `fiberassign` has the flexibility you need, but anecdotally I've never had an issue running it on a target catalog containing just one class of targets (e.g., BGS), skies, and standard stars with many fibers left unassigned.  There is no requirement (that I know of, but @forero should chime in) that all 5000 fibers get a target.

**Comment by andreufont** [comment]
It's fiberassign, and the rest of the code downstream. I.e., can the actual simulator of spectral noise (I guess it would be FastFrame?) handle a petal with only 120 fibers? This would be a question for @julienguy?

**Comment by sbailey** [comment]
By default fiberassign will try to fill any unused fibers with standard stars and skies, which would give you unrealistically good flux calibration and sky subtraction if you don't include a full density of targets.  I think your best option is:
1. run `select_mock_targets` for just QSOs and standard stars (i.e. fast)
2. within the lya-minitest notebook, add steps to augment the targets and truth files with low priority fake targets with zero flux.  e.g. you could use the ELG bit.
3. proceed as normal.

This will waste a bit of time by simulating noise on zero flux objects, but would result in a realistic distribution of QSO, sky, and stdstar targets across the focal plane.

**Comment by andreufont** [comment]
Thanks @sbailey, this looks like a good plan. Although I would have thought that in 1) we also need to run select_mock_targets for sky fibers, isn't it? Or is this generated somewhere else?

@julianbautista, does this make sense?

**Comment by julianbautista** [comment]
Yes. All this makes sense. I tested with and without LRG/ELGs and everything works through well through fiberassign. I didn't check how many standards or skies were allocated though, I will check.

**Comment by julianbautista** [comment]
Btw, both 18.7 and master are broken for the minitest. I'll wait until master is fixed (if there's anything I can do I'm happy to help)

**Comment by sbailey** [comment]
@andreufont yes you will need skies too, but it sounds like @julianbautista already has done that.

@julianbautista if you still have your 18.7 failure notebook, could you send me the error separately?  i.e. not in this thread.

**Comment by moustakas** [comment]
I believe the issue raised in this ticket has been resolved on the `fiberassign` side of things. If not, please feel free to reopen.
