### ISSUE TITLE
MTL: use less memory

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#415]
Refactor `desitarget.mtl.make_mtl` to use less memory.  The current code doesn't appear to be viable for running a full-footprint targets -> MTL.

For example, `/project/projectdirs/desi/target/catalogs/dr7.1/PR372/targets-dr7.1-PR372.fits` is 29GB and only covers part of the footprint, but running `make_mtl` on that spikes at 211 GB of memory (!), which means that we can't run it on a compute node and we can only run it on a login node if we are lucky and don't get caught.

For starters, using fitsio instead of astropy Tables would probably help a lot, though be careful when adding columns because it could trigger a memory copy.  Or we may need to do it in batches by healpix (or similar) and then re-assemble at the end.  We may also need to revisit the plan of propagating all input target columns into the output MTL.

**Comment by moustakas** [comment]
I also think we should take another hard look at what we really need in the targets catalog--
https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/targets.html

See also https://github.com/desihub/desitarget/issues/197.

**Comment by sbailey** [comment]
Fixed in PR #429.  @moustakas question about what we really need in the output catalog is covered by issue #197 so closing this one.
