### ISSUE TITLE
PSF type requirement missing in MWS-MAIN cuts

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#420]
Sorry @geordie666 , here's another one I only just noticed. The MWS-MAIN-* and MWS-BROAD cuts on the TS page specify `TYPE==PSF`, but I can't see that implemented in `desitarget` (the MWS selection routines don't take `objtype`?).

**Comment by geordie666** [comment]
Fixed in https://github.com/desihub/desitarget/pull/422.
