### ISSUE TITLE
apply bright cut when selecting all target classes?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#428]
Analogous to #296 (for ELGs), are there any arguments against applying a (soft) bright cut when selecting all target classes, especially QSOs and LRGs?

I'm asking in the context of #427, as right now stellar contaminants for QSOs as bright as `r=17` are being selected, which is not what the real target catalogs look like.

@geordie666 @Cyeche

**Comment by geordie666** [comment]
There is already such a cut enforced on the LRGs at about r > 18, e.g.:

https://github.com/desihub/desitarget/blob/master/py/desitarget/sv1/sv1_cuts.py#L109

So, as a bright-end cut already exists for the LRGs and ELGs, the question is really the QSOs.

There are over 300 bright quasars in BOSS with a redshift of greater than 2.5 and r < 18, and I know those are particularly valuable for forest work. There are even a couple of dozen with a redshift of greater than 2.5 and r < 17, and a couple with r < 16!

I think we'd be completely safe with a soft limit of r~15.5. If we want to go to r~17, then that would be a cut for the quasar target selection to explicitly apply to best balance completeness and purity. @Cyeche?

**Comment by Cyeche** [comment]
We are currently applying a cut at 17.5 for the RF selection which is the baseline selection now.
https://github.com/desihub/desitarget/blob/master/py/desitarget/cuts.py#L1277

Cheers, Christophe.

**Comment by geordie666** [comment]
@moustakas: Then I think it might meet your requirements to just add an r > 17.5 cut to the `isQSO_cuts_north` and `isQSO_cuts_south` functions?

**Comment by moustakas** [comment]
Yes, that would be great.  Here's one of the QSO QA plots so you can see that `r>17.5` would toss out the worse offending stars.  And I had missed the bright cut on LRGs, so that works, too.  Thanks.

<img width="350" alt="screen shot 2018-12-03 at 4 47 27 pm" src="https://user-images.githubusercontent.com/1431820/49403747-8c033c00-f71b-11e8-98e4-b40fc9e9d22b.png">

**Comment by geordie666** [comment]
Added an r > 17.5 limit for the quasar color cuts in #433.
