### ISSUE TITLE
Move db directory inside the Python package structure

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#43]
In order for desitarget to work with Anaconda environments, the db/ directory needs to be moved inside the Python package itself, *i.e.* to py/desitarget/db/.

**Comment by sbailey** [comment]
It is possible that the db directory is effectively deprecated, as partially evidenced by there not being any *.dr2 files 5 months after the DR2 release.  Are these schema files actually used by any of the python code, or are they mainly for historical reference?

**Comment by weaverba137** [comment]
@sbailey, who would be able to give a definitive answer to this question?

**Comment by weaverba137** [comment]
In PR #47, I have added a README file to the db directory that states that it is probably deprecated.

**Comment by weaverba137** [comment]
@sbailey, can we close this?  No one seems to be willing to answer the question: do we actually need these files?  I have already added a note that says the directory is probably deprecated.
