### ISSUE TITLE
clarify XYZ_SOUTH/NORTH target bit descriptions

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#431]
Our current SOUTH/NORTH targets bit descriptions are, e.g.
```yaml
    - [ELG_NORTH,   9, "ELG from Bok/Mosaic data", {obsconditions: DARK|GRAY}]
    - [ELG_SOUTH,   17, "ELG from DECam data", {obsconditions: DARK|GRAY}]
```
I think this is incorrect (or at least misleading) and should be
```yaml
    - [ELG_NORTH,   9, "ELG cuts tuned on Bok/Mosaic data", {obsconditions: DARK|GRAY}]
    - [ELG_SOUTH,   17, "ELG cuts tuned on DECam data", {obsconditions: DARK|GRAY}]
```
i.e. the bit definition refers to the *cuts* that are applied, regardless of whether the *data* are from the North or South.  Independent of this issue, we may redefine or deprecate how these bits are used, but we should at least have the descriptions correct for what they currently are.

@geordie666 @moustakas agreed?

**Comment by geordie666** [comment]
I agree...these descriptions should be more specific. I'll update them at some point.

**Comment by geordie666** [comment]
These descriptions were updated in #429.
