### ISSUE TITLE
Can MWS/BGS target classes have only DARK|GRAY obsconditions?

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#434]
In MWS SV we may want some (SV-only) target classes only to be observed only in GRAY|DARK conditions. I'm not sure how to do this, and I wonder if it's even possible with the current code.

I thought it would be trivial, just setting obscondtions for those classes in `targetmask.yaml`  to `GRAY|DARK` rather than `BRIGHT|GRAY|DARK`. Maybe I'm missing something, but I ran into the following problem.

In `make_mtl`, the obsconditions column that gets read by fiberassign is created like this: https://github.com/desihub/desitarget/blob/d09cbbd466737aaaeedd90f5f39e1a046a8d4d74/py/desitarget/mtl.py#L99-L108

All MWS (and BGS) targets have the `MWS_ANY` (or `BGS_ANY`) bit set in `DESI_TARGET`, and these bits have `obsconditions: BRIGHT` in `targetmask.yaml`. So the `|=` in the code above makes all MWS and BGS targets always observable in bright conditions, even if the conditions for an individual MWS or BGS target class are set to something more restrictive.

Maybe I just don't understand how this is supposed to work, but if this is a real problem, then maybe the loop in `make_mtl` should ignore some of the 'special' bits like `MWS_ANY`. For those bits it's not clear how the associated obsconditions should be interpreted. 

That doesn't sound ideal but I can't think of a better solution.

I thought there might be a way to do this within the `targetmask.yaml` but I didn't like either of these options:

* If all MWS and BGS classes were observable in `DARK`, the `xxx_ANY` obsconditions could be changed to `DARK` rather than `BRIGHT`. But that isn't the case, e.g. `BGS_BRIGHT` has `BRIGHT` obsconditions only.

* I also thought about adding a new dummy entry in the obscondition mask specifically for these special `xxx_ANY` `DESI_TARGET` bits (i.e. one that would never show up as the conditions of a real tile) but that seems like a pretty ugly hack.

**Comment by geordie666** [comment]
I think that these sorts of targets could just be included with a `DESI_TARGET` bit instead of an `MWS_TARGET` bit in the `sv1_desi_mask` of the SV yaml file:

https://github.com/desihub/desitarget/blob/master/py/desitarget/sv1/data/sv1_targetmask.yaml

**Comment by geordie666** [comment]
Oh, and note that at some point @kdawson1000 and others will be working on an SV-specific version of MTL, so I suspect that the current `mtl.py` will spin off an `sv1_mtl.py` code that will incorporate some special cases.

**Comment by apcooper** [comment]
OK, thanks. Using the `DESI_TARGET` bits would work for SV, if everyone is happy with that solution.

This approach might get more awkward if we want MWS targets with dark/gray-only conditions in the real survey (no plans for that as yet though). `DESI_TARGET` has relatively fewer bits available for new classes (especially when each science class has `NORTH` and `SOUTH` permutations). It also complicates logic that assumes all the MWS targets have `MWS_ANY`.

I don't think either of those is a problem in SV.

**Comment by apcooper** [comment]
I guess this can be closed, the solution above is fine for MWS SV (also we're not currently planning exclusively dark targets now anyway).
