### ISSUE TITLE
Stale branches in desitarget

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#44]
There are several stale branches in desitarget.  What is the plan for merging or deleting these branches:

* npyquery_crash
* npyquery_crash_fix
* mocks
* dr2

**Comment by rainwoodman** [comment]
I do not oppose.

**Comment by weaverba137** [comment]
Deleting the npyquery branches now.  We need to contact Kaylan to talk about the dr2 branch.  @forero could you please give us an update on the 'mocks' branch?

**Comment by forero** [comment]
This branch only includes a small script in bin/ to create target files from mocks.
That script should actually be in desisim/bin. Should I move it there and delete this branch?

**Comment by moustakas** [comment]
Creating target files from mocks sounds like it belongs under 'desitarget', not 'desisim'.  Why should it be moved to desisim?

**Comment by forero** [comment]
A while ago @sbailey convinced me that if some code/script won't run on real data but only on simulated data, it should in principle go to desisim. That still sounds reasonable to me, but I agree that desitarget 'feels' like a natural place to have that script.

**Comment by moustakas** [comment]
Mocks are our best (simulated) real data, so I definitely think this code belongs here (i.e., in desitarget).

**Comment by weaverba137** [comment]
Do we have a resolution to this question?

**Comment by forero** [comment]
@sbailey What do you think?

**Comment by sbailey** [comment]
I withdraw my knee-jerk reaction that desitarget must remain pure data with no code or knowledge of simulation / mock data.

OK for desitarget to have code for generating / organizing mock target data.  Best if that is isolated within its own desitarget.mocks or similarly named submodule.

However, I will insist that the actual target selection code not know anything about mocks and not have secret back doors to the truth.

**Comment by weaverba137** [comment]
So it sounds like we want to keep the 'mocks' branch.  Beware though, it is now over 100 commits behind master, you'll definitely need to merge it with master before continuing to develop on it.

I'll keep this ticket open until we've confirmed a successful merge of master onto mocks.

**Comment by forero** [comment]
Right we'll keep it. I will merge it with master before continuing any other development.

@sbailey shouldn't we have here as well the script converting "martin's mocks" into target & truth files?

**Comment by sbailey** [comment]
Sure, that would be fine, instead of having it in fiberassign.

Stephen

**Comment by weaverba137** [comment]
The 'mocks' branch is now active & up-to-date, & there is a separate issue, #48, for @kaylanb's branches.
