### ISSUE TITLE
fix mock/data skies file datamodel inconsistencies

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#441]
The sky location files written by select_mock_targets have a very different data model than the ones written for real data.  Update select_mock_targets to match the real data skies file (and if this reveals anything that should be updated for the real data skies, do that too).

* mock skies (93 columns): /project/projectdirs/desi/datachallenge/reference_runs/18.11/targets/sky.fits
* data skies (19 columns):
/project/projectdirs/desi/target/catalogs/dr7.1/0.22.0/skies-dr7.1-0.22.0.fits

**Comment by moustakas** [comment]
For the record, the columns in the "real" skies file are:
```
    RELEASE             i4  
    BRICKID             i4  
    BRICKNAME           S8  
    BRICK_OBJID         i4  
    RA                  f8  
    DEC                 f8  
    APFLUX_G            f4  array[2]
    APFLUX_R            f4  array[2]
    APFLUX_Z            f4  array[2]
    APFLUX_IVAR_G       f4  array[2]
    APFLUX_IVAR_R       f4  array[2]
    APFLUX_IVAR_Z       f4  array[2]
    OBSCONDITIONS       i4  
    SUBPRIORITY         f8  
    TARGETID            i8  
    DESI_TARGET         i8  
    BGS_TARGET          i8  
    MWS_TARGET          i8  
    HPXPIXEL            i8  
```

It should be straightforward to populate all these columns in `select_mock_targets` (which is just using the full target catalog right now ---with mostly empty values) with the exception of `OBSCONDITIONS`.  That should happen in `mtl.make_mtl`, no?
