### ISSUE TITLE
Correctly call $DUST_DIR in randoms.py

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#442]
`randoms.py` currently passes around the dust directory as `dustdir`. Refactor that module to instead read from the `$DUST_DIR` environment variable.

In the mean time, `select_randoms` works just fine by passing the `--dustdir` command line option, as in, e.g.:

```
select_randoms infoo outblat --dustdir project/projectdirs/desi/software/attic/edison/dust/v0_1/map
```

**Comment by sbailey** [comment]
Fine to use `$DUST_DIR` as a default, but it can be convenient to retain the ability to override that with a command line option, especially since that command line option already exists.  i.e. lets *add* the `$DUST_DIR` default, but not remove the existing `--dustdir` option.

**Comment by geordie666** [comment]
Addressed in https://github.com/desihub/desitarget/pull/449.
