### ISSUE TITLE
Fix QA density histogram binning

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#445]
Something went wrong with the density histogram binning of the desitarget/0.27.0 QA on DR 7.1, e.g.

![](http://portal.nersc.gov/project/desi/users/adamyers/desitargetQA-dr7.1-0.27.0/histo-ELG.png)

I'm guessing that there is some pixel with extremely high density that is messing up the auto-binning (and should be inspected too).

**Comment by geordie666** [comment]
Addressed in #584.
