### ISSUE TITLE
calc_priority vs. calc_priority_no_table

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#450]
`desitarget.targets.calc_priority` and `desitarget.targets.calc_priority_no_table` have lots of replicated code and are just begging for us to update one and forget about making the same change to the other.

Is `calc_priority` still needed?  A quick grep only shows calls to `calc_priority_no_table`.  If both are genuinely needed, let's refactor into
```python
def calc_priority(..., copy=False):
    ...
    if copy:
        targets = Table(targets).copy()  #- or perhaps without the Table part...
    ...
```

**Comment by geordie666** [comment]
I left `calc_priority` for backwards-compatibility in case any code outside of `desitarget` was calling it. I'm happy to break that, though and just rename `calc_priority_no_table` to be `calc_priority`, though. I personally know of no other code that is calling `calc_priority` than MTL itself.

**Comment by sbailey** [comment]
I grepped all our repos and `desitarget.mtl.make_mtl` and tests are the only places that call `calc_priority`.  Let's drop current `calc_priority` and rename `calc_priority_no_table` -> `calc_priority` and proceed.

If `calc_priority(_no_table)` alters the input `targets` table (which I presume was the reason for the original copy), please make that very clear in the `calc_priority` and `make_mtl` docstrings.

**Comment by sbailey** [comment]
done in PR #452.
