### ISSUE TITLE
MTL / calc_priority for CMX and SV

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#451]
@geordie666 what's your vision for `desitarget.mtl.make_mtl` for CMX and SV target selections?  In particular we need an updated `calc_priority_no_table` (also see #450 about that vs. `calc_priority`) that knows about SV and CMX.  I'm hoping that will be as simple as adding additional
```python
if 'CMX_TARGET' in targets.colnames:
    from desitarget.targetmask.cmx.cmx_targetmask import cmx_mask
    ...
if 'SV1_TARGET' in targets.colnames:
    ...
```
sections like there is for `DESI_TARGET` et al., but I'm checking with you first to make sure that fits in with the bigger picture plan for CMX and SV.

@Srheft is also interested in this.

**Comment by geordie666** [comment]
I believe that @kdawson1000 has requested that @Srheft work on this.

SV should be easy and, as you say, should require a very minor update with most of the changes relying on different priorities and numobs set in the .yaml file in the SV `desi_mask`.

But, unfortunately, I don't think that we can use the existing `calc_priority` for commissioning. There will just be too many special cases. For instance, commissioning needs tests where the entire field of `targets` is blank sky positions, and the sky files don't have the same properties as the target files.

I suspect, therefore, for commissioning, we'll need to import a range of special `calc_priority` and `calc_numobs` functions from their own module in a new module named `cmx/cmx_targets.py`.

**Comment by sbailey** [comment]
Since commissioning (cmx) is a bunch of special cases, let's *not* force ourselves to have single cmx-aware `make_mtl` and `calc_priorities` functions that tries to capture all cases in one place.  We want to track the code that generated the cmx fields, but that could be a separate special function/script/notebook for each of the special cmx programs.

**Comment by geordie666** [comment]
Note that (early next week) I'll update the main `make_mtl` code in the way you describe so that it works with `CMX_TARGET` and `SV1_TARGET` columns. At some point in commissioning, just prior to SV, we'll be using the "SV-like" CMX bits:

https://github.com/desihub/desitarget/blob/master/py/desitarget/cmx/data/cmx_targetmask.yaml#L10-L11

so I suspect that we will need that functionality.

**Comment by kdawson1000** [comment]
I agree with the earlier point that there will be so many special cases in commissioning that we may want an independent mtl code justfor commissioning.  Some of the code may end up being a simple list of hardwired configurations for specific commissioning programs.  My proposal is for Sarah and I to run a few special commissioning fields using hand-edited mtl files and see just what level of customization is needed within the code.  I think this will be an iterative process, with the long term goal of preserving all algorithms in a single piece of commissioning_mtl code.

**Comment by geordie666** [comment]
Mostly fixed in https://github.com/desihub/desitarget/pull/456, although there will remain special cases.
