### ISSUE TITLE
include non-zero SUBPRIORITY for sky targets

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#453]
As noticed by @tskisner in desihub/fiberassign#165, the skies targets have SUBPRIORITY=0.0, e.g. at NERSC `/project/projectdirs/desi/target/catalogs/dr7.1/0.27.0/skies-dr7.1-0.27.0.fits`.  This isn't necessarily a big problem, but it would assist in reproducible sky fiber assignment if sky targets also have random SUBPRIORITY in [0.0, 1.0).

I believe the current case is that placement is reproducible if you use the same file, but if you shuffle the order of sky targets in the file you would get different placements.  The intension for fiber assignment is that shuffling the order of the input targets shouldn't impact the results since everything should be based upon PRIORITY, SUBPRIORITY, and NUMOBS_MORE and not the order of the targets in the input tiles.

**Comment by geordie666** [comment]
Fixed in https://github.com/desihub/desitarget/pull/456.
