### ISSUE TITLE
What is the origin of desitarget.internal?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#46]
desitarget has a subpackage called internal, which makes no sense because it actually contains copies of code from *external* packages.  The standard Python package convention in these cases is to call such subpackages 'external' or 'extern'.

**Comment by rainwoodman** [comment]
internal means it shall not be used by code that depends on desi-target directly; in that sense it is not external.

**Comment by weaverba137** [comment]
@sbailey please comment.  With the removal of maskbits.py, that subpackage will contain one and only one other module, which we might as well make an actual dependency, which is officially supported in another github repository, rather than deal with the duplicated code.

**Comment by weaverba137** [comment]
We will document the meaning of internal in the `internal/__init__.py` file.
