### ISSUE TITLE
On the skewness in the SKY flux distribution

### ISSUE THREAD

**Issue by Srheft** [desihub/desitarget#463]
Looking at the distribution of APFLUX_R of GOOD skies in 'skies-dr7.1-PR459.fits':

`is_good_sky = sky["DESI_TARGET"] & desi_mask["BAD_SKY"] == 0;
good =sky[is_good_sky]`

![image](https://user-images.githubusercontent.com/32471902/53908525-c2976e00-400c-11e9-9188-d9888715255b.png)

with skewness defined as the distance from the mean AFFLUX_R in positive and negative wings  (in **n** steps of **delta**) of the distibution: 
skew(n) =  [npos(n) - nneg(n)]/[0.5 * (npos(n)+nneg(n))]

There seems to be a positive skewness. For instance for n=40, delta =0.05  in APFLUX_R=[-2,2] : 
skew_R = [-0.0444601 ,  0.04700003,  0.45493355,  0.66909039,  0.58336703, 0.54043521,  0.52040241,  0.5399568 ,  0.54641416,  0.4954347 , 0.4822095 ,  0.52495596,  0.48700817,  0.49659864,  0.47930506, 0.46338798,  0.42008573,  0.46131805,  0.45082681,  0.39855726, 0.39416058,  0.32244009,  0.24165708,  0.3853211 ,  0.3805668 , 0.2832618 ,  0.23946037,  0.47198642,  0.35443038,  0.3125 ,0.24880383,  0.32346241,  0.13407821,  0.57725948,  0.18987342,  0.29126214,  0.31906615,  0.45818182,  0.63565891,  0.08080808]

The idea of imposing a cut in flux distribution in fiberassign inputs comes to mind so that only the core of the distribution is used. 

@kdawson1000: please add your deduced contamination level from the above analysis for further discussion with @geordie666 et al here.

**Comment by kdawson1000** [comment]
This is a return to the discussion of whether to impose any additional cuts on the sky fibers.  Within the core of the distribution, defined as -0.1 < AFFLUX_R < 0.1, there is only 4% difference between the number of positive flux measurements and negative flux measurements.  Almost 99% of targets lie within the range -0.1 < AFFLUX_R < 0.1.

At larger values of abs(AFFLUX_R), the skewness indicates that roughly 25% of the targets are contaminated by some light.  There are 152361 more targets with positive flux than with negative flux in this category.  There are a total of 621545 targets in this category.

The overall contamination does not appear to be large, but we could remove most contaminants and maintain an almost symmetric distribution without significantly reducing the number of sky fibers if we require sky targets to have -0.1 < AFFLUX_R < 0.1.   This is an easy fix which would seemingly have very little negative consequence.  

Is it worth changing the sky fibers in the wings of the distribution to be BAD_SKY?  One could also use the pull distribution to make the cuts, if this were indeed pursued.

**Comment by geordie666** [comment]
I'm happy to make these changes in the code, but will defer discussion to @djschlegel, who argued that we should not make any cuts to the sky locations on the basis of flux in https://github.com/desihub/desitarget/issues/454.

**Comment by geordie666** [comment]
I believe that the consensus on a telecon from a few weeks back was to *not* clean up the skewness in the sky distribution, unless it became critical once the spectroscopic pipeline starts to be run on real data. I'm therefore closing this. We can revisit this later if it proves necessary.
