### ISSUE TITLE
 Handling of targets that are both science and standards

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#464]
Requires a new yaml file to designate what bits in each PROGRAM (DARK/GRAY/BRIGHT/SV1_DARK/GRAY/BRIGHT) are what type of observation (SKY/STD/SCIENCE/SAFE/EXCLUDE). See:

https://github.com/desihub/fiberassign/issues/180#issuecomment-471677075

**Comment by sbailey** [comment]
Detail: this could be a new yaml file, or it could be another section in the existing targetmask.yaml file.

**Comment by geordie666** [comment]
This ended up being implemented fully on the fba side, I think.
