### ISSUE TITLE
Standardize Gaia point source selection

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#465]
For GFA target selection, it would be useful to standardize the cuts for how to select likely point-source targets from Gaia when Legacy Survey / Tractor results are not available (chip gaps, off the edge of the footprint...).

From Dustin via Adam:
```
gaia.pointsource = np.logical_or(
    (gaia.G <= 19.) * (gaia.astrometric_excess_noise < 10.**0.5),
    (gaia.G >= 19.) * (gaia.astrometric_excess_noise < 10.**(0.5 + 0.2*(gaia.G - 19.))))
```

Currently Gaia-only sources have MORPHTYPE='U' = undefined.  Consider making those that pass this cut have MORPHTYPE='GPSF' (other MORPHTYPES are 4-characters, so I'd rather not use a longer name).

**Comment by geordie666** [comment]
Addressed in #467.
