### ISSUE TITLE
Add sky and bad_sky to all programs

### ISSUE THREAD

**Issue by tskisner** [desihub/desitarget#470]
Going forward, we intend to use a single target column (i.e. DESI_TARGET, SV1_DESI_TARGET, CMX_TARGET) for all input files to a single run of fiberassignment.  This means that sky and bad_sky bits should be defined for every program.  I think this is just a matter of updating the yaml files.

**Comment by geordie666** [comment]
Fixed in https://github.com/desihub/desitarget/pull/477.
