### ISSUE TITLE
SKY target density tuning

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#472]
We still have cases where some fibers are unassigned because they don't have any science, sky, or bad_sky targets available in a non-colliding location.  @Srheft can you post some specific examples (input catalogs and tiling and fiberassign run to reproduce, not just pictures)?

These could be mitigated by further increasing the densities of the sky targets, but that could bog down the catalog (and memory) with 2x more sky targets when we need them for only <1% of the actual area.  We're really near our memory limits so I don't want to unnecessarily keep cranking up the densities.

For consideration:

Start with a typical sky density that is good enough for 99% of the area.  Identify locations of unassigned fibers and then have a custom sky script that generates additional (BAD_)SKY locations right around those.  Augment the original sky list with those, and iterate until every fiber is placed.  This makes a subset of the sky target list dependent upon specific tiling patterns with specific target catalogs, but for pragmatic purposes I'm not sure that matters (e.g. I don't think we need to replicate the procedure for every mock catalog).

Thoughts or alternatives?

**Comment by geordie666** [comment]
I believe that #471 requests and guarantees that there will be locations at which no fibers can be placed?

**Comment by sbailey** [comment]
#471 is requesting small exclusion zones, O(10) arcsec across, compared to ~170 arcsec diameter reach of a positioner, which should leave plenty of other area that could be good.  And #471 is only for the case of gridded BAD_SKY locations where we don't otherwise have any other imaging survey knowledge (e.g. to pick a sky location).

**Comment by Srheft** [comment]
@sbailey been linking to examples so many times in so many emails/slides lately that those who look may know the address by heart :). Simply run full dr7 sky catalog on[ these set of tiles](http://www.astro.utah.edu/~u6022465/cmx/allSKY/tiles_allsky.fits) [or better yet any set of 20-50 tiles] and take a look at [the summay json](http://www.astro.utah.edu/~u6022465/cmx/allSKY/qa.json) to see the tiles with one unassigned fibers [in this case there are 2 fibers in 21 tiles].

**Comment by Srheft** [comment]
@sbailey @geordie666:

Inline with the discussion in this ticket,  I ran into another example for lack of density in BAD_SKY regions.  Tile center is at [ra=340, dec=20.](http://www.astro.utah.edu/~u6022465/cmx/cmx_mws/single_tiles/plots/fiberassign_500000.pdf) in a field of cmx targets at 13<GAIA_G<16. 
![image](https://user-images.githubusercontent.com/32471902/56073728-f54c2900-5d65-11e9-93b3-3502fcfb2f6a.png)


Solution in cases like this might be something other than tightening the grid (recalling the discussion on having the positioner redirected to "home" location as the "last resort") but I thought to add this example here.

**Comment by sbailey** [comment]
Documenting verbal discussion with @geordie666 : we'll wait until both DR8 and the secondary target infrastructure is finished, and then deal with these unassigned fibers on a case-by-case basis, likely by adding additional secondary targets at those locations.
