### ISSUE TITLE
Generate Gaia GFA targets for bricks that are only partially covered by imaging surveys

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#473]
Spinning a post-merge discussion from #467 into a new ticket:

Currently `select_gfas` only generates Gaia targets for bricks that are not covered by the imaging surveys at all.  @moustakas asked what happens to bricks that are only partially covered, and indeed there is a gap in the targets generated:

![image](https://user-images.githubusercontent.com/218471/54652115-dca46800-4a72-11e9-875d-5a1d15830df7.png)

Thus if a GFA of an edge tile lands in this gap, it won't have as many targets (worst case is that it confuses acquisition and guiding because the fiberassign GFA_TARGETS will be missing potentially bright objects visible on the GFAs).

Find a way to fill these in with Gaia targets without requiring cross matching Gaia targets on fully covered bricks.

**Comment by geordie666** [comment]
I think I can solve this with a relatively quick match on the imaging surveys `REF_ID` (the Gaia `SOURCE_ID`), although it's possible this will introduce Gaia-Tycho duplicates for sources where the Tycho ID takes precedence over the Gaia `SOURCE_ID`.

**Comment by moustakas** [comment]
We handle this case in the pipeline [here](https://github.com/legacysurvey/legacypipe/blob/master/py/legacypipe/reference.py#L43-L61):  Tycho-2 stars that are also in Gaia are dropped (accounting for proper motion and using a 1 arcsec search radius).

Also note that stars from the two catalogs have different `ref_cat` entries (`T2` for Tycho and `G2` for Gaia/DR2).

**Comment by geordie666** [comment]
I also thought of the `ref_cat` solution and will use it. Although, it's another column that we don't propagate into the sweeps (and probably should for DR8).

**Comment by moustakas** [comment]
Let's be sure to review the columns that go into the sweeps during the Utah workshop -- I think we're propagating more columns than we should / need (and missing ones like `ref_cat`).

**Comment by geordie666** [comment]
Excellent idea. We should definitely do that. I've made a note to myself to bring it up.

**Comment by geordie666** [comment]
Addressed in #488.
