### ISSUE TITLE
Possibly stale branches in desitarget

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#48]
You have been working on two branches in desitarget, "truth" and "dr2".  At present, both are very out-of-date relative to master, and dr2 has been inactive for four months.  Can we delete the inactive dr2 branch?  Remember to merge the truth branch with master before continuing to work on it.

**Comment by weaverba137** [comment]
@kaylanb, can you please take a look at this?

**Comment by weaverba137** [comment]
@kaylanb, can you please take a look at this?

**Comment by kaylanb** [comment]
Hi Ben, @weaverba137

I am very sorry for the delay. In those branches I currently am cleaning up code to upload dr2, dr3, and spectroscopic truth catalogues to the db. Should be done today or tomorrow. Will send pull request(s) and delete the branches after they are merged. 

My github notifications were not set and I just fixed them Friday. So you should see fast responses from me from ow on.

Cheers,
Kaylan

**Comment by weaverba137** [comment]
OK, thanx, closing.
