### ISSUE TITLE
Importing desitarget.cuts should not import matplotlib

### ISSUE THREAD

**Issue by dkirkby** [desihub/desitarget#481]
Currently `import desitarget.cuts` imports `desitarget.geomask` which imports `matplotlib`. The fix is probably to move the `matplotlib` imports inside any functions that actually need them, so that `matplotlib`.

See, for example, [desisurvey.plots](https://github.com/desihub/desisurvey/blob/master/py/desisurvey/plots.py) where this strategy is used.

**Comment by geordie666** [comment]
Good point...this is a simple change and I'll fix it in my next round of updates.

**Comment by geordie666** [comment]
Addressed in #484.
