### ISSUE TITLE
Missing DR7 QSO training files

### ISSUE THREAD

**Issue by dkirkby** [desihub/desitarget#483]
The QSO random forest selection uses two different models based on the legacy pipeline release.

One model was trained on DR3 using `desitarget.train.train_mva_decals`, reading files from `/global/project/projectdirs/desi/target/qso_training/`.

The other model appears to have been trained on DR7 (7.0 / 7.1?) but the corresponding code and inputs files do not seem to be available.

This issue is a request to add the the DR7 training and test sample files to `/global/project/projectdirs/desi/target/qso_training/` and update `desitarget.train.train_mva_decals` to reproduce the resulting random forest models.

**Comment by geordie666** [comment]
Although we never added DR7, the full code that was used to create the final (DR9) model is available.
