### ISSUE TITLE
Add PSF size to the QA page

### ISSUE THREAD

**Issue by rongpu** [desihub/desitarget#485]
It would be good to have PSF sizes (PSFSIZE_G, PSFSIZE_G and  PSFSIZE_Z) in the density vs systematics plots in the QA pages (e.g. https://portal.nersc.gov/project/desi/users/adamyers/0.22.0/desitargetQA-dr6.0-0.22.0/QSO.html). This would be informative on the seeing dependence of the targeting.

**Comment by geordie666** [comment]
Addressed in #490.
