### ISSUE TITLE
missing desitarget.QA.qa_targets_truth

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#499]
`desitarget/bin/select_mock_targets --qa` tries to load `desitarget.QA.qa_targets_truth`, which doesn't exist anymore.
```
if args.qa:
    from desitarget.QA import qa_targets_truth
    qa_targets_truth(args.output_dir, verbose=args.verbose)
    sys.exit(1)
```

```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/master/bin/select_mock_targets", line 93, in <module>
    from desitarget.QA import qa_targets_truth
ImportError: cannot import name 'qa_targets_truth'
```

Was this moved and renamed?  @geordie666 @moustakas @forero?

Also: sys.exit(1) would normally imply exiting with an error, when if it was actually able to find and run qa_targets_truth, it seems it should be a success.

**Comment by forero** [comment]
@sbailey I don't know!

**Comment by moustakas** [comment]
Yeah, that's code rot, corresponding to when the only targeting QA was only of the mock, not real targets. 

You should be able to just do
```
run_target_qa /path/to/mock/targets.fits ./mock-qa --mocks --nosystematics
```
