### ISSUE TITLE
resolve north-south targets at 32.375 or 32.125 degrees north?

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#500]
@geordie666 in #497 (or perhaps earlier) you implemented a constant-declination cut of `32.375` to resolve north/south targets, but in #353 (in the mocks) I implemented a cut of `32.125`, based on earlier work by @djschlegel. 

Is the slight difference due to a more updated analysis?  @djschlegel have you or anyone else looked at this more carefully since the `DR8` CCDs file(s) were in-hand?  If not then I can take a peak.

**Comment by geordie666** [comment]
I based my cut on the advice of @djschlegel in this thread:

https://github.com/desihub/desitarget/pull/462#issuecomment-469924286

Note that it's a one-liner to change the cut here:

https://github.com/desihub/desitarget/blob/master/py/desitarget/io.py#L76-L79
