### ISSUE TITLE
Deprecate the sandbox

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#503]
The sandbox is not under active development, and I'm not sure that anyone is actually using it. I'd therefore like to remove it. It would, of course, remain in earlier tags of the desitarget code.

I'll leave this issue open for about a month before I remove any code related to the sandbox. Please comment on this issue if you *are* using the sandbox.

**Comment by moustakas** [comment]
@geordie666 I agree that it was a good idea when we started out, but (largely because of your outstanding management of both baseline and experimental code!) I agree that the sandbox is basically obsolete (AFAIK).

**Comment by geordie666** [comment]
Addressed in #564.
