### ISSUE TITLE
Targeting QA on SV sim

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/desitarget#511]
Running targeting QA on Stephen's SV sim, I get the following error:

```
INFO:run_target_qa:74:<module>: generating plots on 8 processors
INFO:QA.py:1811:make_qa_page: Start making targeting QA page...t = 0.0s
INFO:QA.py:383:read_data: Read in targets...t = 11.0s
INFO:QA.py:396:read_data: Read in truth catalog...t = 12.0s
INFO:QA.py:1577:make_qa_plots: Start making targeting QA plots...t = 0.0s
INFO:QA.py:1605:make_qa_plots: Calculated HEALPixel for each target...t = 1.0s
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/master/bin/run_target_qa", line 77, in <module>
    imaging_map_file=ns.weightmapfile, tcnames=tcnames, systematics=systematics)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/master/py/desitarget/QA.py", line 2019, in make_qa_page
    cmx=cmx, bit_mask=masks, mocks=mocks)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/master/py/desitarget/QA.py", line 1653, in make_qa_plots
    d_mask, b_mask, m_mask = bit_mask
ValueError: too many values to unpack (expected 3)
```

I'll try to track down what's causing it, but maybe someone (@geordie666?) will figure it out before me...

Launch script is here with DESI permissions:
```
/global/homes/m/mjwilson/desi/survey-validation/svdc-summer2019/targeting_qa.py
```

**Comment by geordie666** [comment]
@michaelJwilson: I know the fix for this bug. I'll fix it in my current branch. In the mean time, try running with the latest stable tag (0.30.1).

**Comment by michaelJwilson** [comment]
Ok, great.  That worked a treat.  Output is here:

/global/cscratch1/sd/mjwilson/svdc2019c/target-qa

Is there anything SV specific that I might have forgotten?  E.g. there's not an SV branch lying around for qa, is there?

**Comment by geordie666** [comment]
As written, QA should detect automatically when a file is an SV file and make the plots that are appropriate for SV. So, no, there is no SV-specific branch lying around...

**Comment by michaelJwilson** [comment]
Ok, perfect.  

p.s.  as a native of the UK and Northern Ireland, the sight of BACKSTOP.html in the qa dir. nearly caused my heart to stop ;)  I dare not open it, but trust that you're working on a withdrawal agreement on the side!

**Comment by geordie666** [comment]
@michaelJwilson: I believe this issue should now be fixed in master. If you could quickly rerun whatever you ran to break the SV QA and confirm the fix, that'd be fantastic.

**Comment by geordie666** [comment]
@michaelJwilson: Can we close this issue?

**Comment by michaelJwilson** [comment]
I have limited memory of this.  Looks like it from above!
