### ISSUE TITLE
Extra targetting bit  BGS_FAINT_HIP

### ISSUE THREAD

**Issue by ShaunMCole** [desihub/desitarget#522]
In BGS, BGS_BRIGHT  (r<19.5) have higher targeting priority than BGS_FAINT (19.5<r<20.0) but we need (explained below) to make a random 10% subset of the faint class of objects the same priority as BGS_BRIGHT.   Adam suggested the way to do this is to assign an additional tragetting bit, say BGS_FAINT_HIP that will be assigned to 10% of the BGS_FAINT objects. Then have the fibre targeting code treat these objects the same as the BGS_BRIGHT objects.

Rationale:
     In BGS there are two (main) target classes BGS_BRIGHT and BGS_FAINT and these are given different priorities when passed to the fiber allocation software.When we first tried this out we realised that our targetting strategy had a flaw that meant the PIP weights (developed by Will and Davide) wouldn't work.  Basically in some overdense regions, i.e. galaxy clusters, there are so many BGS_BRIGHT objects that they saturate the fibers and no matter how many times you run the algorithm none of the BGS_FAINT objects receive a fiber.
This screws up the PIP weights as some pairs have zero probability of being observed and so no correction can be made. One ends up with large bias.

   The fix we came up with in Alex Smith's paper was to promote a random 10% of the BGS_FAINT things to have the same priority as BGS_BRIGHT. This solves the problem. In Alex's paper we did this by hand with our own branch of the target assignment code, but I think we need to find a way of doing this in the official version.

**Comment by geordie666** [comment]
Addressed in #525.
