### ISSUE TITLE
WDs as secondary targets

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#524]
I wonder whether everyone is on the same page re. selecting white dwarfs. Two things have happened 'recently':

- Boris has stated a preference for targeting white dwarfs based on a pre-selected catalog rather than a bunch of Gaia cuts. He has the parent catalog and the code to select subsets of it that we want to target in SV and the main survey. 
- @geordie666 has added the secondary target scheme to `desitarget`. 

So it seems natural enough to use the secondary target code to deal with the WD science samples, but I'm worried that will cause problems or inconsistencies with the selection of WD_STDs. The alternative is to have the main code read the WD catalogs as a special case, but I guess that might be considered ugly given the existence of the secondary target scheme.

I don't think there's any distinction in code yet between the science WDs and the WD_STDs. I guess that won't be the final state. Who's responsible for progress on this?

I think swapping the WDs to secondary targets would break the code because of that hard-wiring.

Sorry for a fuzzy issue here but it seems like we need a focused discussion on this. Apologies if that's already happened/happening elsewhere. Pinging @moustakas, @sbailey and @CManser. I don't think Boris is on github so I'll point him to this by email.

**Comment by BGaensicke** [comment]
Just a bit more details on the WD selection function: we have compiled a catalogue of white dwarf candidates (https://arxiv.org/abs/1807.03315) which provides a probability of a Gaia object being a white dwarf. That probability is mapped into Gaia parameter spaced using SDSS spectroscopy, and hence difficult to add to the DESI targeting software.

I have taken the key selection criteria that only make use of the Gaia data to have a selection that will run in the DESI targeting software, 

https://desi.lbl.gov/trac/wiki/TargetSelectionWG/TargetSelection#WhiteDwarfsMWS-WD

which will add a small number (few %) of contaminants (mainly quasars) as long as we stay away from crowded regions (that's the |b|>20 cut). 

If there is a way to provide the white dwarfs (as science and standard targets) simply in the form of a RA, Dec, proper motions, epoch (with associated Gaia IDs), that would work also well.

**Comment by geordie666** [comment]
I think we will want the WD standards to be run through the primary selection code, and Boris' selection criteria are already coded up here:

https://github.com/desihub/desitarget/blob/master/py/desitarget/cuts.py#L786-L824

It's fine, I think, to have a different class of WDs for standards and for science targets. 

So, I don't think it's a problem for Boris to provide his list of WDs as secondary targets. However, we still have a requirement on complete reproducibility of any targets (including secondary targets), so we'd still need a copy of the code that was used to produce the WD sample.

**Comment by geordie666** [comment]
Addressed (at least a v0 secondary mechanism exists) in #531.
