### ISSUE TITLE
GFA coverage 0.31.1 vs 0.32.0 

### ISSUE THREAD

**Issue by Srheft** [desihub/desitarget#528]
@geordie666 
There has been very good improvements in the GFA coverage between version 0.31.1 and 0.32.0. The number of main survey (20070 tiles with IN_DESI==1) tiles that are covered by dr8 and have missing GFA targets in one or more cameras have dropped from **30 in gfa-v0.31.1** to **8 in gfa-0.32.0**.  Here are those 8 tiles.

TILEID          RA/DEC                        # GAF per cam:
35539  (329.74 , -10.16)     [35, 25, 42, 26, 30, 29, 25, 3, 0, 26]
9608    (124.12 , -1.53)       [79, 0, 82, 99, 91, 57, 54, 57, 68, 62]
32647  (126.2 , -6.1)           [0, 12, 75, 75, 84, 74, 78, 83, 76, 30]
932      (329.29, -11.9)        [24, 0, 27, 28, 40, 0, 21, 28, 26, 26]
12456  (331.46,-11.86)       [24, 18, 28, 17, 26, 0, 23, 19, 28, 29]
9584    (126.67, -6.12)        [0, 95, 98, 91, 78, 88, 65, 80, 87, 89]
32665  (123.67, -1.56)        [0, 0, 86, 82, 76, 68, 69, 86, 81, 84]
32633  (128.69,-7.66)         [0, 88, 66, 92, 66, 68, 76, 62, 69, 87]

Please let me know if more info is needed.

**Comment by geordie666** [comment]
@Srheft: At this point, I'm not sure if this is a `desitarget` issue, unless somebody can identify that there's a bug for me to fix. I suspect that these are just areas of the sky where both URAT and Gaia DR2 are missing proper motion measurements. Some suggestions for the collaboration:

- We tweak the tiling solution.
- We don't observe these 8 tiles until Gaia DR3 is available and then allow an update to the GFAs file.
- We find yet another source of proper motions.
- We allow zero-proper-motion objects to propagate to the GFAs file and cut them during tiling.
- We just see how bad it is to guide with one camera down.

**Comment by geordie666** [comment]
I don't think that this is a `desitarget` issue, at this point, so I'm closing. If we really need another source of proper motions (beyond Gaia and URAT), then we should reopen this later.
