### ISSUE TITLE
add OBSCONDITIONS to mock target catalogs

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#529]
@geordie666 Following up on #523, I should add `OBSCONDITIONS` to the `select_mock_targets`-generated target catalogs. Can you point me to a recent data-generated target catalog so I can compare the data models and make any other updates that I've missed?

We should also update the data model--
https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/targets.html

**Comment by geordie666** [comment]
@moustakas: Any of the files in this directory are up-to-data:

`/project/projectdirs/desi/target/catalogs/dr8/0.32.0/targets/main/resolve/`

I agree that we should update the data model, but things are still in sufficient flux that I'm tempted to leave such updates until we at least have a final version of the SV targeting files.

**Comment by moustakas** [comment]
@geordie666 can you remind me---in the current version of the code is `OBSCONDITIONS` added by `select_targets` or by the `MTL`-generating code? In order words, is this ticket still salient?

**Comment by geordie666** [comment]
`OBSCONDITIONS` is set in `select_targets`, specifically in `desitarget.targets.finalize()`:

https://github.com/desihub/desitarget/blob/c0b31a2fa192de6b84dc8da6ea4bd7c47ce078fb/py/desitarget/targets.py#L802-L803

as `OBSCONDITIONS` is needed to divide targets into files on the basis of `dark` or `bright`.

Note that `OBSCONDITIONS` is also set on every pass through `MTL` (which it always was!), but now it's also set initially before the first pass through `MTL`.

**Comment by geordie666** [comment]
I think this ticket therefore remains salient. But more in the general sense of making sure that the data model for the mocks and the targets stay aligned. There could, of course, always be further changes to the data model prior to going back on sky.

**Comment by moustakas** [comment]
Great, it looks like I already wrap on `desitarget.targets.finalize`--
https://github.com/desihub/desitarget/blob/c0b31a2fa192de6b84dc8da6ea4bd7c47ce078fb/py/desitarget/mock/build.py#L1053-L1066

Let's review the "mocks" vs "real data" data model after DR9---additional updates will definitely be needed in the mocks (e.g., the move to Sersic galaxy photometry).
