### ISSUE TITLE
Discard SUPP_SKY near SKY

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#534]
After discussions with @sbailey about not having `SUPP_SKY` where we don't need them:

In a HEALPixel of `NSIDE` that is appropriate to the density at which `SKY` fibers were generated, discard any `SUPP_SKY` sources if there is already an existing `SKY` in that HEALPixel.

**Comment by geordie666** [comment]
This will ultimately be done in fiberassign instead, I think, via a different category of sky fiber. @sbailey: can we close this?

**Comment by sbailey** [comment]
I'd like to keep this open for now though it's ok to prioritize other tickets instead.  We would like to have fiberassign handle this directly, but we're also near our memory limits for fiberassign so it could be helpful to trim out SUPP_SKY targets that we know fiberassign won't use anyway to save fiberassign time and memory.

**Comment by geordie666** [comment]
Addressed in #621.
