### ISSUE TITLE
Wrapping is_in_box?

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/desitarget#547]
Could we allow wrapping of ra in is_in_box such that lims [350., 10.] are allowed?  I've extended it to include negative ra aswell, but I'm not fussed on this.  I.e. like below, where > 0 is_in_box has evaluated true and zero equates to false.   I'm sure smarter implementations are possible.

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6034066/66174468-fb7edc00-e609-11e9-844a-5bad52309464.png">

```
    _ramin, _ramax, decmin, decmax = radecbox

    def wrap(x):
      ##  Handle that RA is periodic by mapping input to [0. to 360.] from [-180., 360.].                                                                                                                            
      x  = np.asarray(x)
      x[x != 360.] = x % 360.

      return  x

    ramin  = wrap(_ramin)
    ramax  = wrap(_ramax)
    ras    = wrap(objs["RA"])

    # ADM check for some common mistakes.                                                                                                                                                                            
    if decmin < -90. or decmax > 90. or decmax <= decmin or _ramin < -180. or _ramax > 360.:
        msg = "Strange boundaries: [ramin, ramax, decmin, decmax] = {}".format(radecbox)
        log.critical(msg)
        raise ValueError(msg)

    if (ras.min() < -180.) | (ras.max() > 360.):
        msg = "Invalid input RA [-180., 360.]"
        log.critical(msg)
        raise ValueError(msg)

    ii = (objs["DEC"] >= decmin) & (objs["DEC"] < decmax)

    if ramax >= ramin:
      ii  = ii & (ras >= ramin) & (ras < ramax)

    else:
      i1  = (ras >= ramin) & (ras <= 360.)
      i2  = (ras >=   0.0) & (ras < ramax)
      ii  = ii & (i1 | i2)

    return  ii
```

**Comment by geordie666** [comment]
@michaelJwilson : If I find some time this week I can implement your suggestion...but as you've already basically written the code, if you just want to implement it and send a PR for me to review, that'd be fine, too.

I'd suggest having a default `wrap=False` keyword argument to retain the existing "strict" functionality (I can imagine situations where someone would _want_ the code to fail if they don't pass RAs with 0 <= RA < 360). Then, if `wrap=True` the code would divert to your version of the function.

**Comment by michaelJwilson** [comment]
Sounds good.  I can send a PR including the wrap keyword by the end of the week.
My explicit use case was looping through the legacy survey ccd boundaries.
