### ISSUE TITLE
missing REF_EPOCH

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#549]
REF_EPOCH is dropped going from sweeps to target files, but we need that for passing to platemaker.

To make matters worse, sweeps have it as a column with per-object values, while platemaker wants it as a single header keyword with the same REF_EPOCH for every target.

The sweeps mostly have 2015.5 (Gaia DR2), with a smattering of other REF_EPOCHs in 1991.x (Tycho?).  Targets without known proper motion (PMRA = PMDEC = 0.0) have REF_EPOCH = 0.0.  Although Gaia DR2 uses 2015.5 for everything, they reserve the right to have a mix of REF_EPOCHs in future releases if we ever ended up using that.

Options?
1. convince Platemaker to use per-object REF_EPOCH .
2. move everything to a common REF_EPOCH=2015.5

**Comment by sbailey** [comment]
It turns out that PlateMaker has hardcoded 2015.5 instead of using any inputs from us for the epoch.  Let's propagate the REF_EPOCH column (per-object) as-is from the sweeps (Option 1).

**Comment by geordie666** [comment]
Addressed in #551
