### ISSUE TITLE
Help clarifying options in mocks build.py

### ISSUE THREAD

**Issue by andreufont** [desihub/desitarget#566]
I wasn't sure whether to send an email to @moustakas and @alxogm or post an issue, I thought this might be easier. Delete whenever you want though.

While reviewing Alma's PR, I noticed that we do read options (like add_dla) in several places in the code, only to end up passing them to LYAMaker. Why don't we just send the params dictionary to LYAMaker, and let LYAMaker figure out what options to read (add_dla, add_metals...). It would cleanup the rest of the code a fair bit.

**Comment by andreufont** [comment]
Actually, it looks like LYAMaker.add_dla might not be needed, since when we call LYAMaker.make_spectra we pass again an option add_dla. Is this needed because make_spectra might be called from different codes with different setups? If so, it would be useful to document a bit, I found it a bit confusing.

**Comment by alxogm** [comment]
I'm closing this, since the related  PR was already approved...
