### ISSUE TITLE
Memory use in select_sv_targets

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#567]
@geordie666 : `select_sv_targets` is now throwing a MemoryError (on an exclusive node with 128GB) in an effort to do... something... with most/all of the Gaia catalog. This has only started recently. 

I admit this is in a branch where I've added a couple more secondary catalogs in the sv1 targetmask.yaml, but that's all -- nothing I would expect to be related to this. 

Being lazy here and posting this as an issue in the hope of someone having a quick explanation/fix/comments, because I don't have time to look into it just now. 

```
apcooper@nid00089:/project/projectdirs/desi/external/mws> export DESI_LOGLEVEL=DEBUG GAIA_DIR=/project/projectdirs/desi/target/gaia_dr2 PATH=/global/u1/a/apcooper/desi/code/desitarget/bin:$PATH PYTHONPATH=/global/u1/a/apcooper/desi/code/desitarget/py/:$PYTHONPATH; select_sv_targets /global/u1/a/apcooper/projects/ssv_plan/global/sweeps/north /global/u1/a/apcooper/projects/ssv_plan/data/sv_targets.fits --sweepdir2 /global/u1/a/apcooper/projects/ssv_plan/global/sweeps/south --numproc 32 --tcnames MWS,STD --scnddir /project/projectdirs/desi/external/mws/staging/target/secondary --writeall > /global/u1/a/apcooper/projects/ssv_plan/runs/ssv_ref/select_sv_targets.log

Traceback (most recent call last):
  File "/global/u1/a/apcooper/desi/code/desitarget/bin/select_sv_targets", line 145, in <module>
    resolvetargs=not(ns.noresolve), mask=not(ns.nomaskbits))
  File "/global/u1/a/apcooper/desi/code/desitarget/py/desitarget/cuts.py", line 2571, in select_targets
    pixlist=pixlist)
  File "/global/u1/a/apcooper/desi/code/desitarget/py/desitarget/cuts.py", line 2036, in apply_cuts_gaia
    gaiaobjs = rfn.drop_fields(gaiaobjs, "TARGETID")
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/recfunctions.py", line 585, in drop_fields
    output = np.empty(base.shape, dtype=newdtype)
MemoryError
```

And in the log (last lines only):

```
INFO:gfa.py:318:_update_status: 8800/9536 files; 3.9 files/sec...t = 37.4 mins
INFO:gfa.py:318:_update_status: 8900/9536 files; 3.9 files/sec...t = 37.7 mins
INFO:gfa.py:318:_update_status: 9000/9536 files; 3.9 files/sec...t = 38.0 mins
INFO:gfa.py:318:_update_status: 9100/9536 files; 3.9 files/sec...t = 38.4 mins
INFO:gfa.py:318:_update_status: 9200/9536 files; 3.9 files/sec...t = 39.4 mins
INFO:gfa.py:318:_update_status: 9300/9536 files; 3.9 files/sec...t = 39.8 mins
INFO:gfa.py:318:_update_status: 9400/9536 files; 3.9 files/sec...t = 40.0 mins
INFO:gfa.py:318:_update_status: 9500/9536 files; 3.9 files/sec...t = 40.2 mins
INFO:gfa.py:335:all_gaia_in_tiles: Retrieved 331496854 Gaia objects...t = 40.6 mins
```

**Comment by geordie666** [comment]
@apcooper : Yes, our data volume has become large. Since we required Gaia-only "all-sky" targeting, we have a factor of 50x more data to process due to the large Gaia data volume.

Some options:

- pass `--numproc 8` which will use far less memory, at the expense of only minimal additional time.
- don't process the backup objects (by passing `--nobackup`)
- limit your area, either by using the RA/Dec box/cap options or by passing `--healpixel` and `--nside`

I usually run everything in HEALPixels, now, so I don't encounter these memory issues. But, we are at the point where you'll either have to run smaller areas, or turn off the all-sky/backup targets using (`--nobackup`).

**Comment by apcooper** [comment]
@geordie666: many thanks, I'm making progress now with `--numproc 8` and `--nobackup`.
