### ISSUE TITLE
What is DESI_TARGET == 1 supposed to mean?

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#57]
@forero?

In relation to [these lines in targets.py](https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py#L113-L115).

Is `DESI_TARGET == 1` meant to mean that the target is in the dark time survey or that it is in _any_ of the surveys? From its use everywhere else I was expecting the former but that line in `calc_nobs` made me wonder if I might be missing something. 

Asked another way, should MWS  and BGS targets have `DESI_TARGET == 1` or `0`?

**Comment by forero** [comment]
```DESI_TARGET``` is meant to be used for the dark time survey. The line you point to should be changed to include a ```MWS_TARGET``` and a ```BGS_TARGET``` check.

If `DESI_TARGET!=0`, then `MWS_TARGET` and `BGS_TARGET` should in principle be set to `0` meaning that those targets didn't match any class in the other programs.

I couldn't find the line with `DESI_TARGET==1`.

**Comment by apcooper** [comment]
Thanks, that's what I expected. (There was no line with `==1`, that was just the way I asked the question...)
