### ISSUE TITLE
re-enable test_qa by updating basemap

### ISSUE THREAD

**Issue by alxogm** [desihub/desitarget#578]
Travis test "test_qa" has been disabled since we require to update the basemap version it uses as current version (basemap/1.0.7) is not longer available from anaconda (see comment in [PR 565](https://github.com/desihub/desitarget/pull/565#issuecomment-579598769))

If basemap is not present. test_qa fails with the error below, raised by:  

`QA.py: line 1740, in make_qa_plots`  

Traceback (most recent call last):
2322  File "/home/travis/build/desihub/desitarget/py/desitarget/test/test_qa.py", line 57, in test_qa_main
2323    imaging_map_file=self.pixmapfile, tcnames=tcnames)
2324  File "/home/travis/build/desihub/desitarget/py/desitarget/QA.py", line 2016, in make_qa_page
2325    weight=weight, imaging_map_file=imaging_map_file, mocks=mocks)
2326  File "/home/travis/build/desihub/desitarget/py/desitarget/QA.py", line 1740, in make_qa_plots
2327    pool.map(_generate_plots, list(targdens.keys()), reduce=_update_status)
2328  File "/home/travis/build/desihub/desitarget/py/desitarget/internal/sharedmem.py", line 678, in map
2329    raise pg.get_exception()
2330desitarget.internal.sharedmem.SlaveException: No module named 'mpl_toolkits.basemap'
2331Traceback (most recent call last):
2332  File "/home/travis/build/desihub/desitarget/py/desitarget/internal/sharedmem.py", line 265, in _slaveMain
2333    self.main(self, *self.args)
2334  File "/home/travis/build/desihub/desitarget/py/desitarget/internal/sharedmem.py", line 563, in _main
2335    r = realfunc(work)
2336  File "/home/travis/build/desihub/desitarget/py/desitarget/internal/sharedmem.py", line 629, in realfunc
2337    else: return func(i)
2338  File "/home/travis/build/desihub/desitarget/py/desitarget/QA.py", line 1693, in _generate_plots
2339    weights=weights[ii], max_bin_area=max_bin_area)
2340  File "/home/travis/build/desihub/desitarget/py/desitarget/QA.py", line 447, in qaskymap
2341    basemap = init_sky(galactic_plane_color='k', ax=ax[0])
2342  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/desiutil/plots.py", line 378, in init_sky
2343    from mpl_toolkits.basemap import pyproj
2344ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

**Comment by geordie666** [comment]
Test re-enabled in #605.
