### ISSUE TITLE
select_mock_targets does not skip a pixel already processed. 

### ISSUE THREAD

**Issue by alxogm** [desihub/desitarget#582]
I've seen that  select_mock_targets is checking if a pixel has been already processed before by looking for a truth file in a path constructed in [L77](https://github.com/desihub/desitarget/blob/a3ee88ed1d1d7f7d7df308908ef4321837444d20/bin/select_mock_targets#L78) 

However, the truth files are saved in different directories depending on whether the targets are dark or bright... so it is not finding the file it is looking for...  For instance in a run it looks for file: 

`$outdir/260/26031/truth-64-26031.fits
`
but that file don't exist, there are actually two files:

```
$outdir/260/26031/dark/truth-dark-64-26031.fits

$outdir/260/26031/bright/truth-bright-64-26031.fits
```

The instruction I'm using is: 

`select_mock_targets -c select-mock-targets.yaml -O ./outdir/  --verbose --seed 123   --nside 64 --healpixels 26031   --nproc 4 --no-spectra`

And I have the same issue with mpi_select_mock_targets

**Comment by moustakas** [comment]
Thanks for finding this bug, @alxogm, which was not caught when we moved to the bright/dark split. If you could fix in a PR I'd be grateful.

**Comment by alxogm** [comment]
Hi, @moustakas please see if you agree with my proposal https://github.com/desihub/desitarget/tree/check_overwrite 

I thought of other ways, like inferring from the config file the truth files that should exist... however I think this is the simplest solution. I'm always checking if both dark and bright truth files exist in a pixel, if any of them is missing the pixel is processed again. But I allow to specify if we only want to check for one... 

I hope I was clear... 
If you think this is reasonable, I can apply the same to mpi_select_mock_targets and make the PR...

thanks.
