### ISSUE TITLE
QA.py looks for truth.fits instead of truth-dark and truth-bright

### ISSUE THREAD

**Issue by alxogm** [desihub/desitarget#593]
run_target_qa  with --mocks option rises the warning 
https://github.com/desihub/desitarget/blob/fde74f41aeea08dd189f0125091187a75c6eb135/py/desitarget/QA.py#L401

therefore it don't complete some of the plots... It should be easy to fix, will try it tomorrow.

**Comment by moustakas** [comment]
Fixed in #602.
