### ISSUE TITLE
qso densities from select_mock_targtets don't look right

### ISSUE THREAD

**Issue by alxogm** [desihub/desitarget#594]
Not sure it is an issue or I did something wrong... but I got this in a run of select_mock_targets, with the --no-spectra option, with a config file as below... there were no contaminants.  Also I used only darktiles...

@moustakas any idea?

Thanks
 
![mock-nz-QSO](https://user-images.githubusercontent.com/14896082/75308183-60cea600-5813-11ea-8a68-b90aa5c130a5.png)

```
QSO: {
        target_type: QSO,
        mockfile: '{DESI_ROOT}/mocks/DarkSky/v1.0.1/qso_0_inpt.fits',
        format: gaussianfield,
        zmax_qso: 1.8,
        use_simqso: True,
        density: 120,
    }
    LYA: {
        target_type: QSO,
        mockfile: '{DESI_ROOT}/mocks/lya_forest/london/v9.0/v9.0.0/master.fits',
        format: CoLoRe,
        nside_lya: 16,
        zmin_lya: 1.8,
        density: 50,
        use_simqso: True,
        sqmodel: 'default',  #Other options are 'lya_simqso_model_develop' and 'lya_simqso_model' (same as quickquasars)
        balprob: 0.0,
        add_dla: False,
        add_metals: False,    #If adding metals use 'all', this is to keep the same argument as in quickquasars.
        add_lyb: False
        }
```

**Comment by alxogm** [comment]
Or  it is something I don't understand, but seems that my run is consistent with  recent reference runs, see for instance log file below, around line 110: 


`/global/project/projectdirs/desi/datachallenge/reference_runs/19.10/targets/52/5261/build-64-5261.log 
`

```
INFO:build.py:215:read_mock: Target density = 120.00 targets/deg2 (downsampling factor = 0.300).
INFO:build.py:398:density_fluctuations: Dividing each nside=64 healpixel (0.84 deg2) into 4 nside=128 healpixel(s) (0.21 deg2).
INFO:build.py:508:get_spectra: Goal: Generate spectra for 67 QSO targets (79.83 / deg2).
INFO:build.py:584:get_spectra: Done: Generated spectra for 67 QSO targets (79.83 / deg2).
```

where it shows a goal target density lower than requested... same in 19.9, but in 19.2 were different:

```
INFO:build.py:192:read_mock: Target density = 120.00 targets/deg2 (downsampling factor = 0.448).
INFO:build.py:375:density_fluctuations: Dividing each nside=64 healpixel (0.84 deg2) into 4 nside=128 healpixel(s) (0.21 deg2).
INFO:build.py:485:get_spectra: Goal: Generate spectra for 100 QSO targets (119.15 / deg2).
INFO:build.py:561:get_spectra: Done: Generated spectra for 100 QSO targets (119.15 / deg2).

```

**Comment by moustakas** [comment]
This issue is handled here: https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/build.py#L188-L206

@alxogm could you (1) check and make sure your `desimodel/data` checkout is up to date; and (2) check this code for bugs?  

I'll try to take a look later today if I can as well.

**Comment by alxogm** [comment]
Hi @moustakas, I'm using master branch of desicode, and desimodel points to `/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desimodel/master`

I'm checking
