### ISSUE TITLE
Is the "trim" keyword in desitarget.mtl needed?

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#612]
@ashleyjross and @michaelJwilson are concerned that if the `trim` keyword in `desitarget.mtl`:

https://github.com/desihub/desitarget/blob/c0b31a2fa192de6b84dc8da6ea4bd7c47ce078fb/py/desitarget/mtl.py#L19

is ever used, it could potentially make it difficult to track the number of tiles touched by a target, which is critical to constructing LSS catalogs.

@tskisner and @sbailey: Do you know if `trim=True` is used anywhere downstream of `desitarget.mtl`? If I can simply deprecate the `trim` kwarg for safety, then I will.

**Comment by sbailey** [comment]
I'm not aware of any uses of trim=True downstream, though checking with @forero about whether he uses it for his fiberassign studies.  I think the original motivation was only one of optimization to avoid reading/trimming/writing MTL files in simulations of later epochs when most targets had already been "observed" and didn't need to be considered for last-pass fiber assignments.

**Comment by michaelJwilson** [comment]
Given that Stephen has touch on a different issue.  This 

``` reading/trimming/writing MTL files in simulations of later epochs ```

is a massive pain and dominates the runtime.  Is there any form of patching system we can use to stop rewriting the same information out over and over.  You might argue we can archive the actual mtl but saving original + all patches aswell.

**Comment by forero** [comment]
I use`trim=True` in some stand-alone scripts for fiberassign studies.

**Comment by tskisner** [comment]
For my part, I use `make_mtl()` in a soon-to-be-posted fiberassign tutorial, but I do not use the `trim` option.

**Comment by geordie666** [comment]
OK, given that at least one person uses `trim=True`, let's retain the `trim` kwarg but be _really_ careful not to use it in OPS or the Main Survey.
