### ISSUE TITLE
Did something just break?

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/desitarget#613]
Few random imports to hopefully confirm that I'm not an idiot, then pre_or_post_dr8 not importing?

![image](https://user-images.githubusercontent.com/6034066/80763859-4efbce80-8af4-11ea-92e1-9c8b8555fdb9.png)

**Comment by geordie666** [comment]
In that version of master, the relevant function was a local function called `_pre_or_post_dr8` (with an underscore), e.g.:
```
[adamyers@cori04 desitarget]$ grep pre_or_post /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/randoms.py 
def _pre_or_post_dr8(drdir):
    drdirs = _pre_or_post_dr8(drdir)
    drdirs = _pre_or_post_dr8(drdir)
```
In the current version, it's now called `pre_or_post_dr8` (to reflect the fact that it's probably no longer just going to be used locally), e.g.:
```
[adamyers@cori04 desitarget]$ grep pre_or_post ~/git/desitarget/py/desitarget/randoms.py 
def pre_or_post_dr8(drdir):
    drdirs = pre_or_post_dr8(drdir)
    drdirs = pre_or_post_dr8(drdir)
```
So, I think you're just not pointing to the development version of master?

**Comment by michaelJwilson** [comment]
I don't know what the development version of master is?  I've been using 

```source /project/projectdirs/desi/software/desi_environment.sh master```

for long enough that I don't remember where I picked that up.  I was able to pick up Ted's changes to master in fiberassign with this a few days ago?  So I'm confused.

**Comment by michaelJwilson** [comment]
Ok, Stephen explained.  Closing.  Thanks!

**Comment by sbailey** [comment]
For the record for others, what I explained was that the master copy at NERSC is only updated once a day (~1am) and the change Michael was looking at was so new that it hadn't made it to NERSC yet.  Using your own clone is the the best way to stay really really up-to-date when needed, and also to make sure that the ~1am update doesn't break something out from under you if you want recent-but-still-stable for a test that might run overnight.
