### ISSUE TITLE
Add option to create a reduced MTL in join_mock_targets

### ISSUE THREAD

**Issue by alxogm** [desihub/desitarget#629]
Currently I can't generate an MTL on a full footprint mock run of select_mock_targets that included all DARK targets but no contaminants, I get a `MemoryError`,  and given the discussion about using reduced MTL files in fiberassign and updates to MTL tests, it would be useful to have this option. @geordie666 @moustakas  what do you think?

**Comment by geordie666** [comment]
I'm working on streamlining MTL this week and next week. As part of that effort, I'll reduce memory usage in MTL so I hope that this issue will just be solved as part of that refactor. If it isn't solved, you can certainly let me know, though! 

I'll include options for running with a limited set of columns, and options to pass subsets of tiles.

**Comment by alxogm** [comment]
Thanks @geordie666 I'll be pendent of your updates. 

Do you think this will affect runs of select_mock_targets (beyond the merging of the catalog)? 
I was planning to make a new run to include contaminants this weekend, but I can certainly wait. Thanks

**Comment by geordie666** [comment]
The mocks do use `desitarget.mtl.make_mtl()`. I'll try to retain backward compatibility with that function, so I don't think I'll break `select_mock_targets`.

In any case, I don't _think_ anything I'm doing will affect runs of `select_mock_targets` beyond the catalog merge. I expect to be proven wrong when something breaks! Finishing my refactor might take a week or more, though, and may require reviews to check alignment with downstream code. So, you may want to run something this weekend to have in hand while I'm working.

**Comment by geordie666** [comment]
@alxogm: NERSC going down for a few days derailed me on the refactor of MTL. So, I probably won't finishing addressing this issue until the middle or end of next week.

I just wanted to keep you in the loop!

**Comment by alxogm** [comment]
Thanks. Mock is ready for testing. We are now making other tests with them.

**Comment by geordie666** [comment]
@alxogm: I think I addressed this as part of #635. However, as we'll need work downstream of #635 to refactor MTL, the fix is currently "turned off." You can test the new functionality, though, by finding the call to `make_mtl` for the mock targets and passing `trimcols=True`. 

If you need to recover additional target columns after you've run the targets through survey selection, you should be able to do that using `desitarget.mtl.inflate_ledger()`.

Let me know if anything breaks!

**Comment by alxogm** [comment]
Sorry for the late response to this. We are coming back to work on this. @HiramHerrera have checked that the functionality of call make_mtl passing trimcols=True for the mocks works well. 

We will move now to try to use the ledgers... So I'm closing this. Thanks @geordie666
