### ISSUE TITLE
mock QA failing with fitsio 1.x

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#632]
mock QA is failing with fitsio 1.x due to `QA.py` [line 413](https://github.com/desihub/desitarget/blob/e17821a5f435262371ff7907e34f57caf015d3d1/py/desitarget/QA.py#L413):
```python
oo = objtype.decode('utf-8').strip().upper()
```
because now `objtype` is a `numpy.str_` instead of `numpy.bytes_` object.

One potential fix is straightforward:
```python
try:
    oo = objtype.decode('utf-8').strip().upper()
except:
    oo = objtype

extname = 'TRUTH_{}'.format(oo)
```

This highlights a piece of code that is used by the integration tests but not covered by the unit tests.  In addition to the above fix, I suggest adding a lightweight truth.fits file to the test data directory and use that to at least verify that `desitarget.QA.read_data(targfile, mocks=True)` works, and perhaps even more.

But before launching into adding new binary files and mixing mocks and real data testing, I'm pausing for comment.  @geordie666 @moustakas ?

**Comment by sbailey** [comment]
FYI, I'm still chasing other similar cases of mock QA incompatibility with fitsio, but wanted to get this issue into the queue for comment about how to approach testing.

**Comment by geordie666** [comment]
In the non-mock part of the code I'm pretty careful about explicitly checking for types, as I've often been bitten by different `fitsio` versions. For example:

        # ADM add the names of the types to the x-axis.
        # ADM first converting the strings to unicode if they're byte-type.
        if isinstance(types[0], bytes):
            types = [type.decode() for type in types]

But, I haven't touched the "mock" parts of the code much, so I'm not sure I'm the best person to comment.

As you say, in terms of testing, you can probably add a lightweight `truth.fits` file to `resource_filename('desitarget.test', 't/')`. You could simply copy a few rows of an existing truth file into that test directory. @moustakas should probably comment on whether that is likely to need more finesse.

If you add a lightweight `truth.fits` file, please include the code for making that file in `test/make_testdata.py`, which includes the scripts for making the lightweight "real" data files for testing purposes.
