### ISSUE TITLE
Mock target hierarchy?  

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/desitarget#646]
Data (e.g. /project/projectdirs/desi/target/catalogs/dr8/0.39.0/targets/main/resolve/dark/) has form targets-dr?-hp-*.fits, with no sub-directories. 

Mocks (e.g. /global/cscratch1/sd/mjwilson/desi/survey-validation/svdc-fall2020-onepercent/targets/) has form ???/*/dark/targets-dark-64-28331.fits where wildcards are (abbreviated) healpixels. 

Is there a reason these have diverged in hierarchy?  This seems to be confusing make_initial_mtl_ledger.  Apologies if I've gotten confused.

**Comment by moustakas** [comment]
Unfortunately the mocks and data target catalogs *have* diverged, not only on-disk organizational structure but also likely in data model. If this is a show-stopper then I can attempt to do an update of the mocks but if not I'd rather wait until DR9 is released and update the data model at the same time. Let me know the priority level.

**Comment by michaelJwilson** [comment]
I can likely symlink my way out of it in the meantime.  If we could get this sorted by the collaboration meeting, I think that could be helpful - there's a lot of momentum behind getting a 1% sim. in place asap.  At least, the targets related items, if not the DR9 data model.  

There's also the MASKBITS implementation:  my memory was we were intending to revisit the approach (I recall discussing  populating e.g. tables with image properties ahead of or after select_mock_targets, but this would prevent scattering the photometry by the actual depth as I did so I'm slightly confused on that). 

Needless to say, I'm happy to work on any of above if pointed in the right direction.  This is at the top of my to-do list at the minute.

**Comment by moustakas** [comment]
With a ton of data now in-hand, including the full 1% survey data, I believe this ticket is now stale. @michaelJwilson please feel free to reopen if additional work on this issue is needed.
