### ISSUE TITLE
Duplicate TARGETID in skysupp

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#647]
Using `/global/cfs/projectdirs/desi/target/catalogs/gaiadr2/0.43.0/skies-supp/` I found the duplicate `TARGETID` 2882304691935379461. That duplicate TARGETID made `fba_run` crash on cmx tests I was running for `TILEID` 5009.

**Comment by forero** [comment]
Anand in an email:

so I gave a check, I find that:
- there are no duplicates in skies-hp-*.fits
- there are no duplicates between skies-hp-*.fits and skies-supp-hp-*.fits
perfect.

but there are some duplicates inside the skies-supp-hp-*.fits:
- skies-supp-hp-0.fits has 1291 duplicates
- there are some duplicates between the skies-supp-hp-*.fits files (if I
got it right, overall, 4594 out of 354,064,078, with counting the 1291
duplicates from skies-supp-hp-0.fits)

to my understanding, that shouldn t happen, right? or is it expected?

thanks!

anand

ps: I m checking:
/global/cfs/projectdirs/desi/target/catalogs/dr8/0.43.0/skies/skies-hp-*.fits
/global/cfs/projectdirs/desi/target/catalogs/gaiadr2/0.43.0/skies-supp/skies-supp-hp-*.fits

**Comment by geordie666** [comment]
Thanks for the digging @forero (via Anand!). That's definitely a bug. I'll try to look at it later today.

**Comment by geordie666** [comment]
Addressed in #653.
