### ISSUE TITLE
Definition of desi_target bits

### ISSUE THREAD

**Issue by Cyeche** [desihub/desitarget#65]
I have implemented a BDT selection of QSO  in cuts.py. So far there is a hack to use it. I checked that both the target density and the quasar completeness make sense on EDR region and on the whole dr2.

The increase in time to run whole dr2 is still reasonable. I will check it once dr3 sweep will be available. However I have still an open issue. To activate it I have two options:
-either I create a new bit for BDT selection
-or I add an argument in select_targets function, i.e useBT, to activate it.

I prefer the latter option, because we can finish with a few hundred bits for target selections as it is now in BOSS and eBOSS. However I recognize that the SDSS strategy has the advantage to keep the history of the target selection in the collaboration.

Christophe.

**Comment by geordie666** [comment]
Hi Christophe,

We shouldn't create a new target selection bit every time an element of the
target selection code changes. But, we should be able to track which
version of BDT was used on a certain run of the target selection code.

Could you create something that spawns a "version" for the BDT code? That
could then be written to the header of output target files when the TS code
is formally run.

Cheers,

Ad.

**Comment by sbailey** [comment]
+1 for opening an issue to discuss this.  Although I agree with @geordie666 that we shouldn't create a new bit every time the target selection changes at all, the difference between BDT and simple cuts is large enough that they might warrant separate bits anyway.  One of those bits might eventually get deprecated.

The select_targets target catalog output fits file includes header keywords for tracking version dependences including:
```
DEPNAM00= 'desitarget'                                                          
DEPVER00= '0.2.2   '           / desitarget.__version__                         
```
If the result of the BDT training is in the git repo itself (e.g. in py/desitarget/data/), then the that desitarget version should specify which version of the BDT was used.  If the new BDT code depends upon an external BDT training file that isn't tracked in git, then that should be included in the fits headers as a new dependency using `desiutil.depend.setdep()` prior to writing out the target file.

**Comment by sbailey** [comment]
The criteria for when it is ok to cut a new target bit is an ongoing discussion, but the other issues here have been addressed: the random forest (previously referred to as BDT) file is included and tagged with the code itself, and select_targets includes in the output header keywords which QSO selection algorithm it used.  Closing issue.
