### ISSUE TITLE
Ledger code failure for high to low res, e.g. with mock targets.

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/desitarget#650]
Mock targets can be generated with nside=64 & above, while the default ledger is 32. 

This is problematic for the make ledger code in two ways.  While looping through the high res pixels, each appears to write out its own version of the larger pixel file, clobbering not appending.  There's also an apparent race-condition, where two higher res pixels being reduced by separate processes can attempt to write to the same larger pixel file simultaneously.

As discussed with @geordie666, options:

(1) We just set the default ledger to nside=64! To be tested.

(2) change the code to remove above.

Cons:
(1)  does the number of pixel files for this nside get problematic for io?
 
(2)  no real good use case for targets defined at this high resolution, so perhaps not worth the bother. 

Suggest (3):

a)  put in a few asserts in make_ledger that caches resolution higher than 32 and raises an error. 

b)  do the same in select_mock_targets, given that high resolution isn't guaranteed to be supported
     downstream.     

Adam will add (3).  On me is to test that default nside=64 for the ledger works.

**Comment by moustakas** [comment]
@michaelJwilson Unless I'm missing something, `select_mock_targets` can be run with an arbitrary value of `nside` (via the `--nside` optional input). So other than generating larger arrays (in which it's not guaranteed that memory issues may not appear), you are welcome to run with `nside=32` or smaller. Please feel free to reopen with a specific example if this doesn't address the issue.
