### ISSUE TITLE
do not import matplotlib unless/until you have to

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#667]
@geordie666 this is a non-critical feature request.

The latest versions of `matplotlib` try to create a `MPLCONFIGDIR` directory when first imported in order to ostensibly speed things up. This is problematic when using `shifter` because the `MPLCONFIGDIR` directory is not writable. For reference, here's a typical warning:
```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-g8cu53tb 
because the default path (/homedir/.config/matplotlib) is not a writable directory; it is 
highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, 
in particular to speed up the import of Matplotlib and to better support multiprocessing.
```

I can bypass this issue in my code by not importing `matplotlib` until I need to. However, some of the `desitarget` code imports `matplotlib` at the top (module) level.

In my use case, I get this warning with the following import, which has nothing to do with plotting:
```
from desitarget.io import desitarget_resolve_dec
```

Again as a feature request, it would be terrific to separate out the plotting imports from the other functionality in `desitarget`.

**Comment by geordie666** [comment]
@moustakas: I agree with this in principal. In fact, I thought I'd already done it! 

Can you determine from your code how `matplotlib` creeps in as a dependency, here? Although there are some module-level imports in desitarget (most notably in `desitarget.QA`) I've tried to isolate them. I was under the impression that `desitarget.io` did not have a dependency on `desitarget.QA`. If it does, it must be somewhat convoluted.

If you can't track this dependency down, specifically, I'll ensure that `desitarget.QA` is the only module that has `matplotlib` as a top-level dependency and then refactor any code that imports from `desitarget.QA`.

**Comment by moustakas** [comment]
Thanks @geordie666. I'll try to hunt this down but in the meantime you can reproduce (from a login node) with
```
shifter --image docker:desihub/fastspecfit:latest bash
python -c "import desitarget.io"
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-87if_ev5 because the default path (/homedir/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
```

Maybe there's a diagnostic tool to determine the dependency tree of which modules are loaded?

**Comment by geordie666** [comment]
Yep, I can recreate that exact warning using your suggested code! Leave this with me (although it won't make it onto my list of priorities until we're observing in a more "standard" mode for SV operations).

**Comment by moustakas** [comment]
Well this is odd. `desimodel.footprint.radec2pix` (which `desitarget` uses in many places) triggers the same import warning.
```
shifter --image docker:desihub/fastspecfit:latest bash
python -c "from desimodel.footprint import radec2pix ; radec2pix(8, 120, 30)"
```

**Comment by moustakas** [comment]
Looks like it might be `healpy` which is importing `matplotlib` automatically
```
python -c "import healpy as hp"
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-q6vga42v because 
the default path (/homedir/.config/matplotlib) is not a writable directory; it is highly recommended 
to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up 
the import of Matplotlib and to better support multiprocessing.
```

**Comment by moustakas** [comment]
Closing this ticket as "won't fix". I have a work-around now for my own Docker production and if anything this is a ticket for `healpy`.
