### ISSUE TITLE
Can these merged branches be deleted?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitarget#67]
These branches have already been merged, and should be deleted if no one is using them:

* cosmeticChangesQSOCut
* ChYMorphology
* obsconditions

**Comment by weaverba137** [comment]
@Cyeche, can you please delete some of these branches, since they have already been merged?

**Comment by weaverba137** [comment]
@forero, can you please delete the obsconditions branch, which has already been merged?

**Comment by Cyeche** [comment]
Done.

Christophe.

**Comment by forero** [comment]
@weaverba137 done
