### ISSUE TITLE
KeyError: 'BGS_TARGET'

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#71]
Travis is failing with a `KeyError: 'BGS_TARGET'` from the tests on mtl. Full report here: https://travis-ci.org/desihub/desitarget/jobs/161457969 

Any help to understand that error would be appreciated.

**Comment by geordie666** [comment]
Looks like Travis was broken back here:

https://github.com/desihub/desitarget/commit/06046e654a24afa05854fc58698e3e8453d63825

But the merge between the py3 and apc_mocks only just caught up with it? If so, maybe @apcooper  should take a look?

**Comment by geordie666** [comment]
I tried to debug some of these and couldn't fix everything, but did find the following:

in ```mtl.py```:

```MTL_RESERVED_TARGETID_MIN_SKY```

Doesn't match:

```assert(np.all(mtl['TARGETID'] < MTL_RESERVED_TARGETID_SKY))```

and, in ```calc_numobs``` of ```targets.py```

```
    # If it wasn't selected by any target class, it gets 0 observations                                      
    # Normally these would have already been removed, but just in case...                                    
    no_target_class =  targets['DESI_TARGET'] == 0
    no_target_class &= targets['BGS_TARGET']  == 0
    no_target_class &= targets['MWS_TARGET']  == 0
```

fails because there is no requirement that ```targets``` contains the fields ```BGS_TARGET``` and/or ```MWS_TARGET```. These could be fixed by checking for these fields as in:

```
    # If it wasn't selected by any target class, it gets 0 observations                                      
    # Normally these would have already been removed, but just in case...                                    
    no_target_class =  targets['DESI_TARGET'] == 0
    if 'BGS_TARGET' in targets.dtype.names:
        no_target_class &= targets['BGS_TARGET']  == 0
    if 'MWS_TARGET' in targets.dtype.names:
        no_target_class &= targets['MWS_TARGET']  == 0
```

But, these are hacks, and the unit tests still fail for ```mtl``` even after applying them, so I'd rather have @apcooper check these on the current py3 branch

**Comment by apcooper** [comment]
This seems to have got bound up with #60 and #72. I'll comment further under #60.
