### ISSUE TITLE
read_randoms_in_tiles?

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/desitarget#713]
I was hoping something like below would be supported:

![image](https://user-images.githubusercontent.com/6034066/115077474-f400ea00-9eb2-11eb-9fa8-ee3eb9f027b8.png)

Is there an existing way?  Or possibility of a read_randoms_in_tiles?  Perhaps with a realization #.

**Comment by geordie666** [comment]
The `read_targets_in_` I/O functions were really only written to facilitate reading targets distributed across files _split by HEALPixel_. As the randoms aren't split-by-pixel in this way, a separate utility is probably overkill. Particularly as `desitarget.geomask` has utility functions such as `is_in_box`, `is_in_cap`, etc.

You can achieve most of your goal using `desimodel.footprint.is_point_in_desi` for the price of, effectively, one extra line of code, e.g.
```
from desimodel.footprint import is_point_in_desi 
import fitsio 
rands = fitsio.read("/global/cfs/cdirs/desi/target/catalogs/dr9/0.49.0/randoms/resolve/randoms-1-0.fits", columns=["RA", "DEC"]) 
ii = is_point_in_desi(tiles, rands["RA"], rands["DEC"]) 
rands = rands[ii]
```

If you need to build a higher density of randoms then you'd have to loop through the randoms files one-by-one or use the "large" files in `/global/cfs/cdirs/desi/target/catalogs/dr9/0.49.0/randoms/randomsall/`

**Comment by michaelJwilson** [comment]
>distributed across files split by HEALPixel. 
Agreed, it took me a while to realize I was misremembering the files as healpixel split.  I'd still advocate read_targets_in_tiles as a particularly nice wrapper to replicate, pulling columns etc, but this would need the restructuring.  in_desi I knew.  Thanks!
