### ISSUE TITLE
z-band extinction correction

### ISSUE THREAD

**Issue by mehdirezaie** [desihub/desitarget#735]
Hi! I am interested in the extinction coefficients for W1 and W2, used for the calculation of MW_Transmission attributes. I found this function in the repository:
https://github.com/desihub/desitarget/blob/acefce624846c54ac08261a85b297e99ba226da0/py/desitarget/mock/mockmaker.py#L321

However, I noticed that the z-band coefficient does not quite match the value reported in the documentation (Galactic Extinction Coefficients): https://www.legacysurvey.org/dr9/catalogs

**Comment by moustakas** [comment]
That's a typo in the z-band coefficient, @mehdirezaie, thanks (it should be 1.211, not 1.221).

But note that all the "dust" code has been consolidated into `desiutil` now (see https://github.com/desihub/desiutil/pull/169) and so I'll be refactoring this part of the code to use those extinction coefficients (which are consistent with what we used for the imaging).

**Comment by moustakas** [comment]
Fixed in #788.
