### ISSUE TITLE
npyquery crashes and performance issues

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#8]
Branch sjb_multifile_ts refactors targetselection.py to write one target catalog output for for many tractor file inputs.  This uncovered two problems with the npyquery cuts:

**1. It crashes after ~350 input bricks** with "Fatal Python error: deallocating None".  This is not a catchable exception, it is a hard hard fatal crash.  It's likely that the actual bug is in one of the underlying compiled libraries, but the complexity of the npyquery tree code makes it difficult to isolate exactly where and why.

To see this, use branch npyquery_crash, which is a branch off of sjb_multifile_ts that uses the npyquery cuts instead of the workaround vanilla numpy cuts in sjb_multifile_ts:

```
[edison sjbailey] targetselection.py /project/projectdirs/cosmo/data/legacysurvey/dr1/tractor blat.fits --verbose
50 bricks; 22.0 bricks/sec
100 bricks; 22.7 bricks/sec
150 bricks; 21.1 bricks/sec
200 bricks; 24.4 bricks/sec
250 bricks; 23.0 bricks/sec
300 bricks; 24.6 bricks/sec
350 bricks; 27.0 bricks/sec
Fatal Python error: deallocating None
Aborted
```

**2. It is ~2.5x - 9x slower than just naively making cuts on the input numpy structured arrays**.

```
from desitarget.cuts import select_targets as select_oldstyle
from desitarget.cuts_npyquery import select_targets as select_npyquery
import fitsio
from astropy.io import fits

d1 = fitsio.read('tractor-0001m002.fits', 1, upper=True)
d2 = fits.getdata('tractor-0001m002.fits')

#- Using numpy arrays from fitsio, npyquery is 2.5x slower
%timeit x = select_oldstyle(d1)   #- 2.77 ms
%timeit x = select_npyquery(d1)   #- 7.07 ms

#- And using FITS_rec objects from astropy.io.fits, npyquery is 9x slower
#- (and both are much slower than the real numpy arrays from fitsio... grr astropy...)
%timeit x = select_oldstyle(d2)  #- 13.4 ms
%timeit x = select_npyquery(d2)  #- 126 ms
```

The ability to introspect the npyquery cuts to find out what variables are needed, and the potential future ability of having them output SQL is cool, but it seems that we should favor obvious, straightforward (and faster and non-crashing) code over clever code.  I'm leaving the npyquery code available in the repo for now, but the upcoming sjb_multifile_ts pull request will offer alternate numpy based cuts instead while this gets sorted out.

**Comment by rainwoodman** [comment]
The Py_None is likely a bug in numpy; which version do you use?

**Comment by rainwoodman** [comment]
I ran with astropy.fits ~ 500 bricks and saw no crash. So it could be a sloppy return Py_None in fitsio.

**Comment by rainwoodman** [comment]
This indeed is a numpy bug, fixed in https://github.com/numpy/numpy/pull/5789
 I tested npyquery against numpy trunk and the crash is gone.

I will come up with a workaround and investigate the speed issue. 
A factor of 2x~3x is probably still acceptable?

**Comment by rainwoodman** [comment]
At the large file limit (w/ sweep files), npyquery shall become faster/ more viable than plain booleans because of the internal chunking.

But it is unclear if we will ever reach that limit with the many sweep (and many many tractor) file approach. ImagingLSS reached that limit because it first builds a giant single sweep file that contains all objects.
