### ISSUE TITLE
pkg_resources is deprecated

### ISSUE THREAD

**Issue by geordie666** [desihub/desitarget#817]
Migrate `pkg_resources` over to `importlib.resources` as `pkg_resources` is deprecated. The [general guide](https://importlib-resources.readthedocs.io/en/latest/migration.html) might be useful.

**Comment by moustakas** [comment]
@geordie666 in case it's helpful, I did this migration for `desispec` recently in this PR--
  https://github.com/desihub/desispec/pull/2157

**Comment by geordie666** [comment]
Addressed in #829.
