### ISSUE TITLE
place to create unique TARGETID for mocks

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#82]
Where in desitarget should we do the unique TARGETID computation? What logic should we follow to do that if we have hundreds of input mock files?

**Comment by apcooper** [comment]
On the first point, I like @forero's solution in the email discussion, to do the assignment of TARGETIDS in the script that creates the merged Table of targets that gets passed to `make_mtl` (i.e. `mocks_to_fa_input`).

**Comment by geordie666** [comment]
Ultimately, we're going to want to set the unique TARGETID once for all targets, so I think the correct place to do it is before the mtl code. Probably, though, using similar code to encode_mtl_targetid in:

https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py

But with a name like encode_targetid instead (as we want TARGETID to be set before the mtl stage)!

This, of course, does not preclude the code in targets.py being called from the code for the mocks.

Note that @sbailey and I discussed the form of TARGETID late in the summer, and came up with the following schema: 

https://desi.lbl.gov/svn/docs/technotes/targeting/targetID/trunk/

Apologies that this is currently only in SVN, I'll upload it to DocDB later today.

**Comment by sbailey** [comment]
Thanks for distributing that note.  I also recall a conversation with @forero and/or @geordie666 that concluded with a target selection ingestion step that would
* resolve any TARGETID conflicts, creating a mapping of original ID to final TARGETID as needed
* perform QA (e.g. do the targets actually include non-zero fluxes?  Do they vary?)
* write the final "real" target catalogs with the fixed-forever TARGETID following the form that Adam documented in that note.

We flirted with the idea of letting MTL being the one that assigns the TARGETID, but ended up backing off on that idea and letting a pre-MTL pre-targetcatalog step handle it.  Real targets based on Legacy Survey data releases should be easy in that they have a DR+BRICKID+OBJID way to define the TARGETID already; the complications only arise for mocks and ancillary programs where TARGETIDs could collide.

**Comment by forero** [comment]
Good. I believe that the consensus is having TARGETID somewhere pre-mtl. 

There is a new `mocks` branch. I will start coding the suggested TARGETID schema there in a place outside mtl.
