### ISSUE TITLE
Include target contamination

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#90]
`select_mock_targets` needs to output contaminants in addition to real targets.
* See #101 for defining input format for contaminant densities
* Make fake file with random variations to incorporate with select_mock_targets
* Update select_mock_targets to output contaminants for each target class with these densities.

Let's start with all contaminants being stars to start with, and update with more realistic mixes of stars vs. galaxies in a later iteration.

**Comment by sbailey** [comment]
Note: desimodel svn trunk now has a desi-tiles.fits file with a STAR_DENSITY column that could be used as a proxy to vary the contaminant rate.  There will be other types of contaminants, but this is a starter.
