### ISSUE TITLE
The NERSC batch system

### ISSUE THREAD

**Issue by mehdirezaie** [desihub/desitarget#93]
I am opening this issue to see if anyone has already used _desitarget_ on **DECAM DR3**. My objective is to do target selection on the DR3 sweep files on NERSC. The installed desitarget on Nersc is not up-to-date, so it fails somewhere during galactic extinction correction ( I think it is because some sweep files have problematic decam_mw_transmission s eg. please take a look at @@ -271,12 +382,18 @@ def unextinct_fluxes(objects): in #92 ).

Anyway, I just use an updated version that is cloned under my cscratch1 directory which is relatively slower than the installed one (I think). Running the select_target script on a single sweep file takes ~ 12-15ish mins.

This is the bash script I use to submit the job:
```
#!/bin/bash
#SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --job-name=my_job
#SBATCH --time=00:30:00
##SBATCH --qos=normal
#SBATCH --mail-type=END
#SBATCH --mail-user=mehdirezaie1990@gmail.com
#SBATCH --workdir=.
source /project/projectdirs/desi/software/modules/desi_environment.sh
#module load desitarget # wait, it is not updated
export PYTHONPATH=/global/cscratch1/sd/mehdi/github/desitarget/py:$PYTHONPATH
export PATH=/global/cscratch1/sd/mehdi/github/desitarget/bin:$PATH
export indir=/global/project/projectdirs/cosmo/data/legacysurvey/dr3/sweep/3.0
export oudir=/global/cscratch1/sd/mehdi/dr3
export id=0
srun -n 1 python ./select_targets $indir/sweep-170p000-180p005.fits $oudir/decamdr3-section$id.fits --section $id --qsoselection colorcuts
wait
```
--section is something I added to select_target to have it choose a chunk of the sweep files (that is because I was not sure if it can handle all the sweep files all at the same time):

```
from __future__ import print_function, division

import numpy as np

from desitarget import io
from desitarget.cuts import select_targets, qso_selection_options

import warnings
warnings.simplefilter('error')

import multiprocessing
nproc = multiprocessing.cpu_count() // 2

def chunkit(lst,n):
    return [ lst[i::n] for i in xrange(n) ]


from argparse import ArgumentParser
ap = ArgumentParser()
ap.add_argument("src", help="Tractor file or root directory with tractor files")
ap.add_argument("dest", help="Output target selection file")
ap.add_argument('-v', "--verbose", action='store_true')
ap.add_argument('--qsoselection',choices=qso_selection_options,default='randomforest',
                help="QSO target selection method")
### ap.add_argument('-b', "--bricklist", help='filename with list of bricknames to include')
ap.add_argument("--numproc", type=int,
    help='number of concurrent processes to use [{}]'.format(nproc),
    default=nproc)
ap.add_argument("--section", help="section of dataset")
ns = ap.parse_args()
infiles = io.list_sweepfiles(ns.src)
if len(infiles) == 0:
    infiles = io.list_tractorfiles(ns.src)
if len(infiles) == 0:
    print('FATAL: no sweep or tractor files found')
    sys.exit(1)

infiles = chunkit(infiles, 4)[int(ns.section)]
print('size {}'.format(len(infiles)))


targets = select_targets(infiles, numproc=ns.numproc, verbose=ns.verbose, 
                         qso_selection=ns.qsoselection)

io.write_targets(ns.dest, targets, indir=ns.src, qso_selection=ns.qsoselection)

print('{} targets written to {}'.format(len(targets), ns.dest))
```

I started thinking maybe I am not using the desitarget in the most time-efficient way.
I would sincerely appreciate any suggestions or comments.

cheers
Mehdi

**Comment by mehdirezaie** [comment]
I just changed the title of this issue, because I noticed that even for a simple _Hello-World-like_ python code, the time required to import modules is unexpectedly high.

**Comment by dkirkby** [comment]
Can you share a simple test snippet and your timing results?

**Comment by moustakas** [comment]
@mehdirezaie Regarding the Milky Way extinction issue, this is a known problem that @geordie666 raised in [decam-chatter 4042].  A handful of Tractor files (and therefore the corresponding sweeps) were corrupted while being written out.  @dstndstn is going to rerun those and we'll generate a new version of sweep catalogs.

**Comment by geordie666** [comment]
@mehdirezaie The latest version of desitarget has a hack to deal with the zero values of DECAM_MW_TRANSMISSION. In cuts.py line 274 (see https://github.com/desihub/desitarget/commit/291f8250e62c509a843cbd115a5ec9699455bd16).

With this hack in place, I can run the code in < 10 minutes on NERSC, even just running with the defaults for nproc, e.g.:

select_targets /global/project/projectdirs/cosmo/data/legacysurvey/dr3/sweep targets-dr3.fits -v

**Comment by mehdirezaie** [comment]
Thanks so much @dkirkby @moustakas and @geordie666 .
Actually this morning I tried to document the time issue, to share the timing results with you, but everything worked well as @geordie666 mentioned. 

However, I do not know why, but the same issue has appeared. The time is so long that it surpasses the time limit in my bash, and I can not see the timing for each step of my codes (importing, body, etc). Once I could narrow it down to something, I will share the timing with you.

I have shared this with the NERSC help desk, and they said that 
> 2016-10-24 09:44:38 PDT - Zhengji ZhaoAdditional comments
We had users reporting a slow startup time on Edison, and we are investigating the cause now.

I will keep you posted. Thanks so much again!

**Comment by mehdirezaie** [comment]
For instance this is one of the examples that used to be very fast, 2-3 hours ago.
But now, it is like it does not even make it to run.

This is the batch script I use to submit my run
```
mehdi@edison07:~/work/85> cat batch.job
#!/bin/bash
#SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH --job-name=my_job
#SBATCH --error=error%j.out
##SBATCH --output=output%j.txt
#SBATCH --mail-type=END
#SBATCH --mail-user=mehdirezaie1990@gmail.com
#SBATCH --workdir=.
module load python-hpcp
module load desitarget
time srun -n 1 python ./importtime.py
```
and this is the main code
```
mehdi@edison07:~/work/85> cat importtime.py 
from __future__ import print_function, division
from time import time

start = time()
# start importing
import numpy as np
from desitarget import io
from desitarget.cuts import select_targets
import warnings
warnings.simplefilter('error')
import multiprocessing
nproc = multiprocessing.cpu_count() // 2
from argparse import ArgumentParser
#end importing
end1 = time() 
np.random.seed(1234)
x = np.random.random(size=100)
end2 = time()

print ('##################################')
print (' A simple test to show the time required for importing')
print ('mean of randoms : {}'.format(np.mean(x)))
print ('std of randoms : {}'.format(np.std(x)))
print ('time for total: {}'.format(end2-start))
print ('time for importing numpy: {}'.format((end1-start)))
print ('time for doing calculation: {}'.format((end2-end1)))
```

The output in the morning:
```
##################################
 A simple test to show the time required for importing
mean of randoms : 0.518362907879
std of randoms : 0.276718766801
time for total: 5.29430890083
time for importing numpy: 5.29420304298
time for doing calculation: 0.000105857849121
```
But now, the startup is taking so long that it does not write anything out, and terminates once the time limit is up. I do not what is going on with the NERSC.
I will keep you posted. Thanks again!

**Comment by dkirkby** [comment]
Thanks for the updates.  An easy way to time just the import is from ipython:
```
%time import desitarget
```
On my laptop, this reports:
```
CPU times: user 98 ms, sys: 11.1 ms, total: 109 ms
Wall time: 115 ms
```
Another issue related to slow imports is at dkirkby/speclite#24 but it doesn't sound like this is your problem.

**Comment by mehdirezaie** [comment]
> Another issue related to slow imports is at dkirkby/speclite#24 but it doesn't sound like this is your problem.

Thanks so much @dkirkby 
I agree with you that is not my issue. I think my issue is something with the NERSC python startup on computing nodes. As in the morning, I could import desitarget stuff pretty fast.

**Comment by tskisner** [comment]
I'm one of the people with an open NERSC ticket about slow job start.  The issue I see is with the batch system and has nothing to do with python.  I ran a small slurm script which just dumped the environment (with /usr/bin/env) at the start of the slurm script and then also calling it from srun.  I ran that job and found these results:

  job 2414812 node nid00804 : finished
  job 2414872 node nid02856 : finished
  job 2415569 node nid00351 : started, timed out
  job 2415631 node nid00397 : never started, timed out
  job 2415638 node nid00288 : never started, timed out
  job 2415673 node nid00289 : finished
  job 2415717 node nid00023 : finished
  job 2415746 node nid00293 : finished
  job 2416179 node nid00392 : never started, timed out
  job 2416248 node nid00290 : never started, timed out
  job 2416288 node nid00294 : finished
  job 2416327 node nid00419 : finished
  job 2416360 node nid00270 : finished
  job 2416444 node nid00437 : finished
  job 2416492 node nid00090 : finished
  job 2416950 node nid00250 : started, timed out
  job 2417393 node nid05918 : finished
  job 2417662 node nid00233 : finished
  job 2417730 node nid00250 : finished

So that is what I reported to NERSC.

**Comment by mehdirezaie** [comment]
Thank you very much @tskisner :)

**Comment by geordie666** [comment]
@mehdirezaie If it's a batching issue, I wonder if the code might actually run _quicker_ for you if you forced nproc=1 and just ran on a single processor on the login node!

Also, you can probably close this issue. I don't think it's a desitarget issue...

**Comment by mehdirezaie** [comment]
Thanks everyone! I really appreciate your help.
I am going to close this issue!
